//! Golden tests for the [`Corrections`] word-correction port.
//!
//! These replay fixtures generated by the reference JS in
//! `goldens/gen/corrections_ref.mjs` — a DOM-free reimplementation of the EXACT
//! index.html `applyCorrections` / `applyCorrectionsToTranscript` policy — and
//! assert the Rust port produces byte-identical output for every input line,
//! with the corrections applied in the same insertion order. This is what makes
//! the port verifiable rather than vibes: the JS behavior is captured first as
//! goldens, then the Rust must match it byte-for-byte.
//!
//! Native-only; the policy is pure Rust (the test target is kept off the wasm
//! build for consistency with the workspace's other golden tests).
#![cfg(not(target_arch = "wasm32"))]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests use unwrap/expect as the assertion mechanism (PRD lint config)"
)]

use serde::Deserialize;
use silent_core::corrections::Correction;
use silent_notes::corrections::Corrections;
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct Fixture {
    #[allow(
        dead_code,
        reason = "description is echoed in the golden for readability"
    )]
    description: String,
    /// `[wrong, right]` pairs in insertion order.
    corrections: Vec<(String, String)>,
    cases: Vec<Case>,
}

#[derive(Debug, Deserialize)]
struct Case {
    input: String,
    output: String,
}

fn goldens_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("goldens")
}

fn load(rel: &str) -> Fixture {
    let path = goldens_dir().join(rel);
    let bytes =
        std::fs::read(&path).unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()));
    serde_json::from_slice(&bytes)
        .unwrap_or_else(|e| panic!("parse fixture {}: {e}", path.display()))
}

fn replay(rel: &str) {
    let fx = load(rel);

    // Build the corrections map in the SAME insertion order the JS object had
    // (Object.entries order == array order in the golden).
    let mut corr = Corrections::new();
    for (wrong, right) in &fx.corrections {
        corr.add(wrong, right);
    }

    // The map entries must round-trip in insertion order.
    let entries: Vec<Correction> = corr.entries();
    assert_eq!(
        entries.len(),
        fx.corrections.len(),
        "[{rel}] correction count mismatch (empty/dup pairs?)"
    );
    for (got, (wrong, right)) in entries.iter().zip(&fx.corrections) {
        assert_eq!(&got.wrong, wrong, "[{rel}] wrong-key order mismatch");
        assert_eq!(&got.right, right, "[{rel}] right-value mismatch");
    }

    // Every input line must correct to the JS-produced output, byte-for-byte.
    for (i, case) in fx.cases.iter().enumerate() {
        let produced = corr.apply(&case.input);
        assert_eq!(
            produced, case.output,
            "[{rel}] case {i}: BYTE-IDENTICAL correction broken\n  input:    {:?}\n  expected: {:?}\n  produced: {:?}",
            case.input, case.output, produced
        );
    }
}

#[test]
fn basic() {
    replay("corrections/basic.json");
}

#[test]
fn global_all_case() {
    replay("corrections/global_all_case.json");
}

/// Regex metacharacters in the `wrong` word must be escaped to literals
/// (`c++`, `node.js`, `a(b)`, `$var`, `a|b`, `x[1]`).
#[test]
fn regex_special_escaped() {
    replay("corrections/regex_special_escaped.json");
}

/// Corrections apply in insertion order; a later correction acts on an earlier
/// one's output.
#[test]
fn insertion_order_chaining() {
    replay("corrections/insertion_order_chaining.json");
}

/// No word-boundary guard: the pattern matches inside larger words too (a
/// faithfully-preserved imperfection of the shipping JS).
#[test]
fn substring_no_boundary() {
    replay("corrections/substring_no_boundary.json");
}

#[test]
fn multi_pair() {
    replay("corrections/multi_pair.json");
}

/// Unicode (BMP) case-insensitive matching (`MÜNCHEN`/`münchen`, `cafe`/`café`)
/// — pins that Rust `(?i)` folds the same code points JS `i` does.
#[test]
fn unicode() {
    replay("corrections/unicode.json");
}

#[test]
fn edge_empty() {
    replay("corrections/edge_empty.json");
}
