//! Golden tests for the [`NoteExtractor`] / [`OpenQuestions`] port.
//!
//! These replay fixtures generated by the reference JS in
//! `goldens/gen/notes_ref.mjs` — a DOM-free reimplementation of the EXACT
//! index.html `NoteEngine` + `OpenQs` policy — and assert the Rust port
//! reproduces every emitted note (id, category, text, the byte-identical
//! `triggerPhrase`), the four live counters after every step, and the final
//! open-question texts. This is what makes the port verifiable rather than
//! vibes: the JS behavior is captured first as goldens, then the Rust must match
//! it byte-for-byte.
//!
//! The replay mirrors the index.html live pipeline EXACTLY:
//!   per final line:  `analyze(line)` then `OpenQs.consider(line)`, then for each
//!                     note assign the next id; a question goes to `OpenQs.add`,
//!                     anything else bumps its category counter.
//!   at stop:          `flush()`, then for each note assign the next id and bump
//!                     its category counter (flushed questions are NOT added to
//!                     `OpenQs`, matching index.html).
//!
//! Native-only; the policy is pure Rust (the test target is kept off the wasm
//! build for consistency with the workspace's other golden tests).
#![cfg(not(target_arch = "wasm32"))]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests use unwrap/expect as the assertion mechanism (PRD lint config)"
)]

use serde::Deserialize;
use silent_core::notes::NoteCategory;
use silent_notes::extractor::{NoteExtractor, OpenQuestions, TriggerNote};
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct Fixture {
    description: String,
    lines: Vec<String>,
    expected: Expected,
}

#[derive(Debug, Deserialize)]
struct Expected {
    trace: Vec<TraceItem>,
    #[serde(rename = "finalCounters")]
    final_counters: Counters,
    #[serde(rename = "openQuestions")]
    open_questions: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(tag = "op", rename_all = "lowercase")]
enum TraceItem {
    Analyze {
        #[allow(dead_code, reason = "the line is echoed in the golden for readability")]
        line: String,
        emitted: Vec<EmittedNote>,
        counters: Counters,
    },
    Flush {
        emitted: Vec<EmittedNote>,
        counters: Counters,
    },
}

#[derive(Debug, Deserialize)]
struct EmittedNote {
    id: u64,
    category: String,
    text: String,
    #[serde(rename = "triggerPhrase")]
    trigger_phrase: String,
}

#[derive(Debug, Deserialize, PartialEq, Eq)]
struct Counters {
    decisions: u32,
    actions: u32,
    keypoints: u32,
    questions: u32,
}

fn goldens_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("goldens")
}

fn load(rel: &str) -> Fixture {
    let path = goldens_dir().join(rel);
    let bytes =
        std::fs::read(&path).unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()));
    serde_json::from_slice(&bytes)
        .unwrap_or_else(|e| panic!("parse fixture {}: {e}", path.display()))
}

fn cat_key(c: NoteCategory) -> &'static str {
    match c {
        NoteCategory::Decisions => "decisions",
        NoteCategory::Actions => "actions",
        NoteCategory::Keypoints => "keypoints",
        NoteCategory::Questions => "questions",
        // `#[non_exhaustive]` escape hatch: a future category would be a new
        // golden, not a silent pass.
        _ => "unknown",
    }
}

/// The live note pipeline state, reproducing the index.html `addTranscript` /
/// `stop` bookkeeping: a monotonic note-id counter, the running
/// decisions/actions/keypoints counts, and the [`OpenQuestions`] tracker (which
/// owns the questions counter). Bundled into one struct so the per-step check is
/// a method, not an 8-argument free function.
struct LivePipeline {
    next_id: u64,
    decisions: u32,
    actions: u32,
    keypoints: u32,
    open_qs: OpenQuestions,
}

impl LivePipeline {
    fn new() -> Self {
        Self {
            next_id: 1,
            decisions: 0,
            actions: 0,
            keypoints: 0,
            open_qs: OpenQuestions::new(),
        }
    }

    /// The four live counters, with the questions count sourced from
    /// [`OpenQuestions::open_count`] (the index.html `OpenQs` semantics).
    fn counters(&self) -> Counters {
        Counters {
            decisions: self.decisions,
            actions: self.actions,
            keypoints: self.keypoints,
            questions: self.open_qs.open_count(),
        }
    }

    /// Assert one batch of emitted notes equals the golden and advance the live
    /// id / counter bookkeeping exactly as index.html does. `is_flush` selects
    /// the stop-path (flushed questions are NOT added to `OpenQs`).
    fn check_emitted(
        &mut self,
        desc: &str,
        op: &str,
        produced: &[TriggerNote],
        expected: &[EmittedNote],
        is_flush: bool,
    ) {
        assert_eq!(
            produced.len(),
            expected.len(),
            "[{desc}] {op}: emitted-note count mismatch (got {produced:?}, want {expected:?})"
        );
        for (got, want) in produced.iter().zip(expected) {
            let id = self.next_id;
            self.next_id += 1;
            assert_eq!(id, want.id, "[{desc}] {op}: note id mismatch");
            assert_eq!(
                cat_key(got.category),
                want.category,
                "[{desc}] {op}: category mismatch for id {id}"
            );
            assert_eq!(
                got.text, want.text,
                "[{desc}] {op}: text mismatch for id {id}"
            );
            assert_eq!(
                got.trigger_phrase, want.trigger_phrase,
                "[{desc}] {op}: triggerPhrase mismatch for id {id} \
                 (BYTE-IDENTICAL port broken)"
            );
            // Bookkeeping: questions go to OpenQuestions (live path only — flushed
            // questions are NOT added to OpenQs in index.html); others bump counts.
            match got.category {
                NoteCategory::Questions if !is_flush => self.open_qs.add(id, &got.text),
                NoteCategory::Questions => {}
                NoteCategory::Decisions => self.decisions += 1,
                NoteCategory::Actions => self.actions += 1,
                NoteCategory::Keypoints => self.keypoints += 1,
                // `#[non_exhaustive]`: a future category would need a golden, not
                // a silent skip.
                _ => panic!("[{desc}] {op}: unhandled note category {:?}", got.category),
            }
        }
    }
}

fn replay(rel: &str) {
    let fx = load(rel);
    let desc = &fx.description;
    let mut engine = NoteExtractor::new();
    let mut pipe = LivePipeline::new();

    let mut line_iter = fx.lines.iter();
    for item in &fx.expected.trace {
        match item {
            TraceItem::Analyze {
                emitted, counters, ..
            } => {
                let line = line_iter
                    .next()
                    .unwrap_or_else(|| panic!("[{desc}] more analyze trace items than lines"));
                // index.html order: analyze(text) THEN OpenQs.consider(text)
                // THEN the add loop.
                let produced = engine.analyze(line);
                pipe.open_qs.consider(line);
                pipe.check_emitted(desc, "analyze", &produced, emitted, false);
                assert_eq!(
                    &pipe.counters(),
                    counters,
                    "[{desc}] analyze: live counters mismatch"
                );
            }
            TraceItem::Flush { emitted, counters } => {
                let produced = engine.flush();
                pipe.check_emitted(desc, "flush", &produced, emitted, true);
                assert_eq!(
                    &pipe.counters(),
                    counters,
                    "[{desc}] flush: live counters mismatch"
                );
            }
        }
    }

    // Final counters and open-question texts must match the golden.
    assert_eq!(
        &pipe.counters(),
        &fx.expected.final_counters,
        "[{desc}] final: live counters mismatch"
    );
    assert_eq!(
        pipe.open_qs.open_texts(),
        fx.expected.open_questions,
        "[{desc}] final open-question texts mismatch"
    );
}

#[test]
fn one_per_category() {
    replay("extractor/one_per_category.json");
}

#[test]
fn open_question_resolution() {
    replay("extractor/open_question_resolution.json");
}

#[test]
fn multiple_open_questions() {
    replay("extractor/multiple_open_questions.json");
}

#[test]
fn cross_line_buffering() {
    replay("extractor/cross_line_buffering.json");
}

#[test]
fn long_unpunctuated_flush() {
    replay("extractor/long_unpunctuated_flush.json");
}

#[test]
fn skips_and_no_triggers() {
    replay("extractor/skips_and_no_triggers.json");
}

#[test]
fn flush_trigger_at_stop() {
    replay("extractor/flush_trigger_at_stop.json");
}

#[test]
fn precedence_and_question_skip() {
    replay("extractor/precedence_and_question_skip.json");
}

/// Adversarial sweep: `\b` boundaries (disagreed must NOT match `\bagreed\b`),
/// case-insensitivity, contraction alternations, the weekday action pattern, the
/// metric keypoint, the literal-dot `highest.leverage` wildcard, and an
/// open-question resolved by a later line. The byte-identity proof beyond the
/// curated one-per-category rows.
#[test]
fn stress_sweep() {
    replay("extractor/stress_sweep.json");
}
