//! Golden tests for the meeting-history search.
//!
//! These replay fixtures generated by the reference JS in
//! `goldens/gen/search_ref.mjs` (a DOM-/IndexedDB-free reimplementation of the
//! EXACT `index.html` `openHistory` candidate selection + `_filterHistory`
//! predicate) and assert the Rust port returns the same matched meeting ids in
//! the same order.
//!
//! Regenerate goldens: `node crates/silent-storage/goldens/gen/search_ref.mjs`.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests use unwrap/expect as the assertion mechanism (PRD lint config)"
)]

use serde::Deserialize;
use silent_storage::search::{MeetingId, MeetingRecord, TextRow, search_history};
use std::path::PathBuf;

fn goldens_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("goldens/search")
}

#[derive(Deserialize)]
struct Fixture {
    input: Input,
    expected: Vec<MeetingId>,
}

#[derive(Deserialize)]
struct Input {
    meetings: Vec<JsMeeting>,
    notes: Vec<JsTextRow>,
    chunks: Vec<JsTextRow>,
    query: String,
    limit: usize,
}

#[derive(Deserialize)]
struct JsMeeting {
    id: MeetingId,
    title: String,
    #[serde(rename = "startTime")]
    start_time: i64,
}

#[derive(Deserialize)]
struct JsTextRow {
    #[serde(rename = "meetingId")]
    meeting_id: MeetingId,
    text: String,
}

fn load(name: &str) -> Fixture {
    let path = goldens_dir().join(name);
    let bytes =
        std::fs::read(&path).unwrap_or_else(|e| panic!("read golden {}: {e}", path.display()));
    serde_json::from_slice(&bytes)
        .unwrap_or_else(|e| panic!("parse golden {}: {e}", path.display()))
}

fn replay(name: &str) {
    let f = load(name);
    let meetings: Vec<MeetingRecord> = f
        .input
        .meetings
        .into_iter()
        .map(|j| MeetingRecord {
            id: j.id,
            title: j.title,
            start_time: j.start_time,
        })
        .collect();
    // The JS checks notes then transcript chunks; both reduce to TextRow with the
    // identical substring predicate, so they concatenate into one slice.
    let text_rows: Vec<TextRow> = f
        .input
        .notes
        .into_iter()
        .chain(f.input.chunks)
        .map(|j| TextRow {
            meeting_id: j.meeting_id,
            text: j.text,
        })
        .collect();

    let got = search_history(&meetings, &text_rows, &f.input.query, f.input.limit);
    assert_eq!(got, f.expected, "{name}: search result mismatch");
}

#[test]
fn order_newest_first() {
    replay("order_newest_first.json");
}
#[test]
fn title_match() {
    replay("title_match.json");
}
#[test]
fn title_case_insensitive() {
    replay("title_case_insensitive.json");
}
#[test]
fn notes_match() {
    replay("notes_match.json");
}
#[test]
fn transcript_match() {
    replay("transcript_match.json");
}
#[test]
fn multi_field_order() {
    replay("multi_field_order.json");
}
#[test]
fn no_match() {
    replay("no_match.json");
}
#[test]
fn whitespace_query_is_empty() {
    replay("whitespace_query_is_empty.json");
}
#[test]
fn limit_50_cap() {
    replay("limit_50_cap.json");
}
