//! `Corrections` — the live word-correction policy, ported BYTE-IDENTICALLY from
//! the index.html `applyCorrections` / `applyCorrectionsToTranscript` JavaScript.
//!
//! This is PRD Phase 3, Appendix A row 25 ("Word corrections: a `{ wrong: right }`
//! map applied to every incoming transcript chunk, case-insensitively, and
//! re-applied retroactively to existing transcript/note text when a correction
//! is added"). The contract is "identical behavior first, improvements after" —
//! so this module reproduces the *exact* current behavior, including its
//! imperfections (no word-boundary guard, so the pattern matches inside larger
//! words too; insertion-ordered sequential application, so a later correction
//! sees an earlier one's output). Equality with the JS is pinned by the goldens
//! in `goldens/corrections/`, generated by `goldens/gen/corrections_ref.mjs`
//! (a DOM-free reimplementation of the *exact* index.html algorithm).
//!
//! # The JS policy, verbatim
//!
//! ```js
//! // index.html ~1671 (the transcription worker's live application) and the
//! // identical loop in ~5888 (the main-thread retroactive re-application):
//! function applyCorrections(text) {
//!   for (const [wrong, right] of Object.entries(config.corrections || {})) {
//!     const re = new RegExp(wrong.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');
//!     text = text.replace(re, right);
//!   }
//!   return text;
//! }
//! ```
//!
//! The store is the plain `{ wrong: right }` object; `Object.entries` iterates
//! in string-key INSERTION order, so corrections apply in the order they were
//! added. This module holds that order explicitly.
//!
//! # Boundary
//!
//! The correction command/event TYPES (`CorrectionCommand`, `CorrectionEvent`,
//! `Correction`) live in [`silent_core::corrections`] — the typed boundary the
//! UI wires against. This module is the POLICY behind that boundary.
//!
//! # Fidelity notes
//!
//! - **Escape set.** The JS escapes `. * + ? ^ $ { } ( ) | [ ] \` then compiles
//!   with the `i` (case-insensitive) and `g` (global) flags, making `wrong` a
//!   literal, case-insensitive, replace-all pattern. [`regex::escape`] escapes
//!   the same metacharacters (it escapes a superset, but for any character the
//!   JS escapes, both produce a literal match), and `(?i)` +
//!   `Regex::replace_all` give the same case-insensitive global semantics.
//! - **Case folding.** JS `i` and Rust `(?i)` both fold Unicode (the `regex`
//!   crate's default features include `unicode-case`). The goldens include an
//!   accented-text case (`MÜNCHEN`/`münchen`) to pin this.
//! - **Literal replacement.** The Rust replacement uses [`regex::NoExpand`] so
//!   the `right` text is inserted verbatim. JS `String.prototype.replace`
//!   interprets `$&`/`$n`/`$$` in the replacement specially; the corrections UX
//!   fixes mis-heard *words* (the replacement is a plain word), so this diverges
//!   only for `$`-escape sequences the feature never produces. The goldens model
//!   the same literal semantics, so golden == Rust byte-identically.
//! - **Char vs UTF-16.** Both engines operate on the same code points for the
//!   BMP text these corrections see; replacement is span-based, not index-based,
//!   so there is no UTF-16-vs-scalar offset hazard.

use regex::{NoExpand, Regex};
use silent_core::corrections::Correction;

/// One compiled correction: the original [`Correction`] pair plus the
/// case-insensitive, global [`Regex`] compiled from the escaped `wrong` literal.
/// The compiled pattern is cached so re-applying the map (every incoming chunk +
/// every retroactive pass) does not recompile.
struct CompiledCorrection {
    pair: Correction,
    re: Regex,
}

/// The word-corrections policy: an insertion-ordered map of `{ wrong: right }`
/// pairs and the live application of that map to transcript text.
///
/// Faithful port of the index.html `corrections` object + `applyCorrections`.
/// Insertion order is preserved (the JS `Object.entries` order): adding a
/// `wrong` that already exists overwrites its `right` IN PLACE (keeps its
/// position), exactly as `corrections[wrong] = right` does on a JS object.
///
/// Pure: no DOM, no model, no I/O. The UI owns the panel and the worker push;
/// this owns the map and the regex application.
#[derive(Default)]
pub struct Corrections {
    /// Compiled corrections, in insertion order.
    items: Vec<CompiledCorrection>,
}

impl Corrections {
    /// A fresh, empty correction map (index.html `let corrections = {}`).
    #[must_use]
    pub fn new() -> Self {
        Self { items: Vec::new() }
    }

    /// Compile the case-insensitive, global pattern for a `wrong` literal,
    /// matching the JS `new RegExp(wrong.replace(escapeRx, '\\$&'), 'gi')`.
    ///
    /// `regex::escape` makes `wrong` a literal; `(?i)` is the `i` flag; the `g`
    /// flag maps to [`Regex::replace_all`]. Compilation cannot fail for an
    /// escaped literal, but we never panic in production: a (theoretically
    /// impossible) failure yields `None` and the pair is skipped, matching the
    /// JS degradation of never crashing the transcription loop.
    fn compile(wrong: &str) -> Option<Regex> {
        let pattern = format!("(?i){}", regex::escape(wrong));
        Regex::new(&pattern).ok()
    }

    /// Add (or overwrite) a correction (index.html `addCorrection`:
    /// `corrections[wrong] = right`).
    ///
    /// If `wrong` already exists, its `right` is updated in place (the slot
    /// keeps its insertion position — JS object key-overwrite semantics). An
    /// empty `wrong` is ignored (the index.html `addCorrection` guards
    /// `if (!wrong || !right) return`); an empty `right` is likewise ignored
    /// for parity with that guard.
    ///
    /// Returns `true` if the map changed.
    pub fn add(&mut self, wrong: &str, right: &str) -> bool {
        if wrong.is_empty() || right.is_empty() {
            return false;
        }
        if let Some(existing) = self.items.iter_mut().find(|c| c.pair.wrong == wrong) {
            // Overwrite in place — the regex is unchanged (same `wrong`); only
            // the replacement text changes.
            if existing.pair.right == right {
                return false;
            }
            existing.pair.right = right.to_string();
            return true;
        }
        let Some(re) = Self::compile(wrong) else {
            return false;
        };
        self.items.push(CompiledCorrection {
            pair: Correction {
                wrong: wrong.to_string(),
                right: right.to_string(),
            },
            re,
        });
        true
    }

    /// Remove a correction by its `wrong` key (index.html `removeCorrection`:
    /// `delete corrections[wrong]`). Returns `true` if a pair was removed.
    pub fn remove(&mut self, wrong: &str) -> bool {
        let before = self.items.len();
        self.items.retain(|c| c.pair.wrong != wrong);
        self.items.len() != before
    }

    /// Replace the entire map with the given ordered list (e.g. on restore).
    /// Empty/invalid pairs are skipped exactly as [`Self::add`] guards them; a
    /// repeated `wrong` overwrites the earlier slot in place.
    pub fn set(&mut self, corrections: &[Correction]) {
        self.items.clear();
        for c in corrections {
            self.add(&c.wrong, &c.right);
        }
    }

    /// Clear all corrections (new meeting / reset).
    pub fn clear(&mut self) {
        self.items.clear();
    }

    /// The current map as an ordered list of [`Correction`] pairs (insertion
    /// order). Used to re-render the correction tags and re-push to the worker.
    #[must_use]
    pub fn entries(&self) -> Vec<Correction> {
        self.items.iter().map(|c| c.pair.clone()).collect()
    }

    /// Number of corrections in the map.
    #[must_use]
    pub fn len(&self) -> usize {
        self.items.len()
    }

    /// Whether the map is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }

    /// Apply every correction to `text`, in insertion order
    /// (index.html `applyCorrections`). Each pair replaces ALL case-insensitive
    /// occurrences; later pairs see earlier pairs' output (the sequential JS
    /// loop). Returns the corrected string.
    ///
    /// This is the single policy behind BOTH index.html call sites: the
    /// transcription worker's per-chunk live application AND the main-thread
    /// retroactive re-application over existing transcript/note text.
    #[must_use]
    pub fn apply(&self, text: &str) -> String {
        let mut out = text.to_string();
        for c in &self.items {
            // `replace_all` == the JS `g` flag; `NoExpand` inserts `right`
            // literally (no `$`-sequence substitution).
            out = c.re.replace_all(&out, NoExpand(&c.pair.right)).into_owned();
        }
        out
    }
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::unwrap_used,
    reason = "tests use expect/unwrap as the assertion mechanism (PRD lint config)"
)]
mod tests {
    use super::*;

    #[test]
    fn basic_case_insensitive_global() {
        let mut c = Corrections::new();
        assert!(c.add("kuber netes", "Kubernetes"));
        assert_eq!(
            c.apply("Kuber Netes and kuber netes."),
            "Kubernetes and Kubernetes."
        );
    }

    #[test]
    fn regex_metachars_are_literal() {
        let mut c = Corrections::new();
        c.add("c++", "C++");
        c.add("node.js", "Node.js");
        // The `.` matches a literal dot only; the `+` is literal.
        assert_eq!(c.apply("c++ and cxx"), "C++ and cxx");
        assert_eq!(c.apply("node.js vs nodexjs"), "Node.js vs nodexjs");
    }

    #[test]
    fn insertion_order_chaining() {
        let mut c = Corrections::new();
        c.add("foo", "bar");
        c.add("bar", "baz");
        // foo -> bar -> baz; a pre-existing bar -> baz too.
        assert_eq!(c.apply("foo and bar"), "baz and baz");
    }

    #[test]
    fn overwrite_keeps_position() {
        let mut c = Corrections::new();
        c.add("a", "1");
        c.add("b", "2");
        assert!(c.add("a", "9")); // overwrite first slot
        assert_eq!(
            c.entries(),
            vec![
                Correction {
                    wrong: "a".into(),
                    right: "9".into()
                },
                Correction {
                    wrong: "b".into(),
                    right: "2".into()
                },
            ]
        );
        // No-op overwrite returns false.
        assert!(!c.add("a", "9"));
    }

    #[test]
    fn empty_pairs_are_ignored() {
        let mut c = Corrections::new();
        assert!(!c.add("", "x"));
        assert!(!c.add("x", ""));
        assert!(c.is_empty());
    }

    #[test]
    fn remove_and_clear() {
        let mut c = Corrections::new();
        c.add("a", "1");
        c.add("b", "2");
        assert!(c.remove("a"));
        assert!(!c.remove("a"));
        assert_eq!(c.len(), 1);
        c.clear();
        assert!(c.is_empty());
    }

    #[test]
    fn set_replaces_map() {
        let mut c = Corrections::new();
        c.add("old", "x");
        c.set(&[
            Correction {
                wrong: "teh".into(),
                right: "the".into(),
            },
            Correction {
                wrong: "wrng".into(),
                right: "right".into(),
            },
        ]);
        assert_eq!(c.len(), 2);
        assert_eq!(c.apply("teh wrng"), "the right");
    }
}
