//! `NoteExtractor` — the live trigger-detection policy, ported BYTE-IDENTICALLY
//! from the index.html `NoteEngine` + `OpenQs` JavaScript.
//!
//! This is PRD Phase 3 row 16 ("Live trigger notes: decisions, actions, key
//! points, open questions + live counters"). The contract is "identical
//! behavior first, improvements after" — so this module reproduces the *exact*
//! current behavior, including its imperfections (no stemming in the
//! open-question keyword overlap, first-pattern-wins category precedence, the
//! `< 8`-char sentence skip, the `> 300`-char unpunctuated flush). Equality with
//! the JS is pinned by the goldens in `goldens/extractor/`, generated by
//! `goldens/gen/notes_ref.mjs` (a DOM-free reimplementation of the *exact*
//! index.html algorithm).
//!
//! # Boundary
//!
//! The note command/event TYPES (`NoteCommand`, `NoteEvent`, `NoteCategory`,
//! `NoteCounters`) live in [`silent_core::notes`] — the typed boundary the UI
//! wires against. This module is the POLICY behind that boundary.
//!
//! # Fidelity notes
//!
//! - **Regexes.** Each trigger is a Rust [`regex::Regex`] compiled from a pattern
//!   translated to the `regex` crate dialect, paired with the *JavaScript*
//!   source string. The emitted `trigger_phrase` is the JS source string
//!   (`pattern.source`), preserved byte-for-byte so the goldens match. The two
//!   dialects agree on every construct these patterns use (`\b`, `\w`, `\d`,
//!   `\s`, alternation, anchored `$`, the literal-ish `.` in `highest.leverage`);
//!   case-insensitivity is applied per-pattern exactly as the JS `i` flag is
//!   (every trigger is `/i` EXCEPT `questions[0]` = `/\?$/`).
//! - **Char vs UTF-16.** JS `String.length` / `.slice` count UTF-16 code units;
//!   this port counts Unicode scalar values (`char`s). They agree for the BMP
//!   text these heuristics see; the difference would only surface on astral-plane
//!   input (emoji), which the regexes never trigger on. The buffer thresholds
//!   (`< 8`, `> 300`) are deliberately the same scalar counts as the JS.

use silent_core::notes::{NoteCategory, NoteCounters};

mod triggers;

pub use triggers::TriggerSet;

/// One categorized trigger note produced by [`NoteExtractor::analyze`] /
/// [`NoteExtractor::flush`]. Mirrors the JS `noteEngine.analyze` result objects
/// (`{ category, text, triggerPhrase, timestamp }`) minus the timestamp, which
/// the orchestrator stamps (the JS used `Date.now()` purely for
/// jump-to-transcript; it is not part of the categorization policy).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TriggerNote {
    /// The category the matching trigger assigned.
    pub category: NoteCategory,
    /// The triggering sentence (already `trim`med, as the JS stored it).
    pub text: String,
    /// The JS regex source string that matched (`pattern.source`), preserved
    /// byte-for-byte.
    pub trigger_phrase: String,
}

/// The trigger-extraction engine: a faithful port of the index.html
/// `NoteEngine` class. Accumulates final transcript lines, splits them into
/// sentences on terminal punctuation, and categorizes each sentence by the first
/// matching trigger (in `decisions` → `actions` → `questions` → `keypoints`
/// order, first pattern wins).
///
/// Pure policy: no model, no DOM, no I/O. Deterministic and unit-testable
/// without a browser (PRD R2).
#[derive(Debug)]
pub struct NoteExtractor {
    triggers: TriggerSet,
    buffer: String,
}

impl Default for NoteExtractor {
    fn default() -> Self {
        Self::new()
    }
}

impl NoteExtractor {
    /// Create a fresh extractor with an empty buffer (index.html
    /// `new NoteEngine()`).
    #[must_use]
    pub fn new() -> Self {
        Self {
            triggers: TriggerSet::new(),
            buffer: String::new(),
        }
    }

    /// Categorize a final transcript line. Faithful port of `NoteEngine.analyze`:
    ///
    /// 1. Append `" " + text` to the buffer.
    /// 2. Split the buffer into sentences on `/[^.!?]*[.!?]+/g`, keeping the
    ///    trailing remainder in the buffer.
    /// 3. If the remainder exceeds 300 chars with no terminator, flush it as a
    ///    sentence and clear the buffer.
    /// 4. For each sentence ≥ 8 chars (after trim), assign the first matching
    ///    category (first pattern wins within a category; categories in
    ///    insertion order). Sentences that match nothing are skipped (they are
    ///    just transcript).
    pub fn analyze(&mut self, text: &str) -> Vec<TriggerNote> {
        // this.buffer += ' ' + text;
        self.buffer.push(' ');
        self.buffer.push_str(text);

        // Split on /[^.!?]*[.!?]+/g, tracking the index past the last match so
        // the remainder stays buffered — exactly as the JS exec() loop does.
        let mut sentences: Vec<String> = Vec::new();
        let last_index = split_sentences(&self.buffer, &mut sentences);

        // this.buffer = this.buffer.slice(lastIndex).trimStart();
        let remainder: String = self.buffer.chars().skip(last_index).collect();
        self.buffer = trim_start(&remainder).to_string();

        // if (this.buffer.length > 300) { sentences.push(this.buffer.trim()); this.buffer=''; }
        if self.buffer.chars().count() > 300 {
            sentences.push(self.buffer.trim().to_string());
            self.buffer.clear();
        }

        let mut results = Vec::new();
        for sentence in sentences {
            // if (sentence.trim().length < 8) continue;
            if sentence.trim().chars().count() < 8 {
                continue;
            }
            if let Some((category, trigger_phrase)) = self.triggers.categorize(&sentence) {
                results.push(TriggerNote {
                    category,
                    // results.push({ ..., text: sentence.trim(), ... })
                    text: sentence.trim().to_string(),
                    trigger_phrase: trigger_phrase.to_string(),
                });
            }
        }
        results
    }

    /// Force-flush the trailing sentence buffer at stop. Faithful port of
    /// `NoteEngine.flush`: if the remaining buffer trims to fewer than 8 chars,
    /// clear it and emit nothing; otherwise clear the buffer and re-run
    /// [`analyze`](Self::analyze) on `remaining + "."` so the dangling sentence
    /// gets a terminator and is categorized.
    pub fn flush(&mut self) -> Vec<TriggerNote> {
        if self.buffer.trim().chars().count() < 8 {
            self.buffer.clear();
            return Vec::new();
        }
        let text = self.buffer.trim().to_string();
        self.buffer.clear();
        let mut with_period = text;
        with_period.push('.');
        self.analyze(&with_period)
    }
}

/// Split `buf` into sentences exactly as the JS
/// `while ((match = /[^.!?]*[.!?]+/g.exec(buffer)) !== null)` loop does:
/// each match is `[^.!?]*[.!?]+` (run of non-terminators then ≥1 terminator),
/// trimmed and pushed. Returns the char index past the last match (the JS
/// `sentenceRx.lastIndex`), which is where the remainder begins. Operates on
/// `char`s so the returned index is a scalar count matching JS UTF-16 indices
/// for BMP text.
fn split_sentences(buf: &str, out: &mut Vec<String>) -> usize {
    let chars: Vec<char> = buf.chars().collect();
    let n = chars.len();
    let is_term = |c: char| c == '.' || c == '!' || c == '?';
    let mut i = 0usize;
    let mut last_index = 0usize;
    while i < n {
        let start = i;
        // [^.!?]*  — greedily consume non-terminators
        while i < n && !is_term(chars[i]) {
            i += 1;
        }
        // [.!?]+   — require ≥1 terminator; if none, no match from here on
        if i >= n || !is_term(chars[i]) {
            // The JS regex would fail to match at this position and exec()
            // returns null — the loop ends, remainder = from `start`.
            last_index = start;
            return last_index;
        }
        while i < n && is_term(chars[i]) {
            i += 1;
        }
        let sentence: String = chars[start..i].iter().collect();
        out.push(sentence.trim().to_string());
        last_index = i;
    }
    last_index
}

/// JS `String.prototype.trimStart` — strip leading whitespace. The JS regex set
/// and this port treat the ASCII/Unicode whitespace `char::is_whitespace`
/// covers; for the transcripts here it is leading spaces inserted by the
/// `" " + text` accumulation.
fn trim_start(s: &str) -> &str {
    s.trim_start()
}

/// Open-question tracking — a faithful port of the index.html `OpenQs` object.
///
/// Questions detected by the [`NoteExtractor`] are registered here via
/// [`add`](Self::add); a later declarative line that shares ≥ 2 content words
/// with an open question marks it resolved (struck through in the UI). The Open
/// Questions counter reflects only the still-open ones. This is the cheap live
/// heuristic; the WebGPU recap does a fuller pass at stop (out of scope here).
///
/// DOM-free: the JS read question text from the DOM in `openTexts()`; here each
/// item stores its text, giving the identical observable result.
#[derive(Debug, Default)]
pub struct OpenQuestions {
    items: Vec<OpenQuestion>,
}

#[derive(Debug, Clone)]
struct OpenQuestion {
    id: u64,
    text: String,
    keywords: Vec<String>,
    resolved: bool,
}

impl OpenQuestions {
    /// New, empty tracker (`OpenQs.reset()` initial state).
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Clear all tracked questions (`OpenQs.reset`). Called on new meeting /
    /// recording start.
    pub fn reset(&mut self) {
        self.items.clear();
    }

    /// Register a newly-detected open question (`OpenQs.add(id, text)`). The
    /// content-word keyword set is computed once at add time, matching the JS.
    pub fn add(&mut self, id: u64, text: &str) {
        self.items.push(OpenQuestion {
            id,
            text: text.trim().to_string(),
            keywords: content_keywords(text),
            resolved: false,
        });
    }

    /// Consider a transcript line as a potential answer to open questions
    /// (`OpenQs.consider`). Skips lines that are themselves questions (end with
    /// `?`). Any open question sharing ≥ 2 content words with the line is marked
    /// resolved. Returns the ids newly resolved by this line (for emitting
    /// [`NoteEvent::QuestionResolved`](silent_core::notes::NoteEvent::QuestionResolved)).
    pub fn consider(&mut self, text: &str) -> Vec<u64> {
        let mut resolved_now = Vec::new();
        // if (!this.items.length || /\?\s*$/.test(text.trim())) return;
        if self.items.is_empty() || ends_with_question(text) {
            return resolved_now;
        }
        let line_kws: std::collections::HashSet<String> =
            content_keywords(text).into_iter().collect();
        // if (!kws.size) return;
        if line_kws.is_empty() {
            return resolved_now;
        }
        for q in &mut self.items {
            if q.resolved {
                continue;
            }
            let overlap = q.keywords.iter().filter(|k| line_kws.contains(*k)).count();
            if overlap >= 2 {
                q.resolved = true;
                resolved_now.push(q.id);
            }
        }
        resolved_now
    }

    /// The texts of the still-open questions, in insertion order
    /// (`OpenQs.openTexts`). Empty strings are dropped (the JS `.filter(Boolean)`).
    #[must_use]
    pub fn open_texts(&self) -> Vec<String> {
        self.items
            .iter()
            .filter(|q| !q.resolved)
            .map(|q| q.text.clone())
            .filter(|t| !t.is_empty())
            .collect()
    }

    /// The number of still-open (unresolved) questions (`OpenQs._updateCount`'s
    /// `open`). This is the value the Open Questions section counter shows.
    #[must_use]
    pub fn open_count(&self) -> u32 {
        u32::try_from(self.items.iter().filter(|q| !q.resolved).count()).unwrap_or(u32::MAX)
    }
}

/// Content-word keyword extraction, shared by [`OpenQuestions`] (the JS
/// `OpenQs._kw`). Lowercases, matches `/\b[a-z][a-z']{2,}\b/g` (a letter then ≥2
/// letters-or-apostrophes — i.e. words of length ≥ 3), de-duplicates preserving
/// first-seen order, and drops stopwords. Order matters only for determinism;
/// the overlap test is set-based.
fn content_keywords(text: &str) -> Vec<String> {
    let lower = text.to_lowercase();
    let mut seen = std::collections::HashSet::new();
    let mut out = Vec::new();
    for w in word_matches(&lower) {
        if !STOPWORDS.contains(&w.as_str()) && seen.insert(w.clone()) {
            out.push(w);
        }
    }
    out
}

/// Faithful port of the JS `/\b[a-z][a-z']{2,}\b/g` match over a lowercased
/// string: ASCII-letter runs (with apostrophes inside) of total length ≥ 3,
/// bounded by `\b`. The JS class `[a-z]` is ASCII-only (the string is already
/// lowercased), so the leading char is `a..=z` and the rest are `a..=z` or `'`.
/// `\b` is a word boundary against the JS `\w` class (`[A-Za-z0-9_]`); an
/// apostrophe is a non-word char, so `it's` yields `it` then would need ≥3
/// total — matching the JS, which would capture `it's` as one token because the
/// inner class includes `'`. We reproduce that: a run is `[a-z][a-z']*` and we
/// keep it only if ≥ 3 chars; word boundaries are handled by scanning maximal
/// runs of `[A-Za-z0-9_']`-ish neighborhoods exactly as the regex `\b` does.
fn word_matches(lower: &str) -> Vec<String> {
    // The JS regex, on a lowercased string, effectively finds maximal substrings
    // of the form  (?<![\w'])[a-z][a-z']{2,}(?![\w'])  ... but JS `\b` uses `\w`
    // (no apostrophe). To match byte-for-byte we replicate the engine: walk the
    // string, and at each `\b`-preceded position try to match `[a-z][a-z']{2,}`.
    let chars: Vec<char> = lower.chars().collect();
    let n = chars.len();
    let is_word = |c: char| c.is_ascii_alphanumeric() || c == '_';
    let is_az = |c: char| c.is_ascii_lowercase();
    let is_inner = |c: char| c.is_ascii_lowercase() || c == '\'';

    let mut out = Vec::new();
    let mut i = 0usize;
    while i < n {
        // A `\b` boundary before position i where a word char begins: the JS
        // first atom is `[a-z]`, which is itself a word char, so the boundary is
        // "previous char is not a word char".
        let at_boundary = i == 0 || !is_word(chars[i - 1]);
        if at_boundary && is_az(chars[i]) {
            // Greedily consume [a-z']* after the mandatory leading [a-z].
            let start = i;
            i += 1;
            while i < n && is_inner(chars[i]) {
                i += 1;
            }
            // The match is chars[start..i]; the `\b` trailing boundary is
            // automatically satisfied because we stopped at a non-`[a-z']` char,
            // and the last consumed char is `[a-z']`. The JS trailing `\b` uses
            // `\w`; a trailing apostrophe (e.g. "rockin'") leaves `'` as the last
            // char, which is NOT `\w`, so the JS `\b` requires the char before it
            // to be `\w` — it is (a letter), so the boundary holds and the whole
            // run including a trailing apostrophe matches, exactly as here.
            let run: String = chars[start..i].iter().collect();
            // {2,} after the leading char ⇒ total length ≥ 3.
            if run.chars().count() >= 3 {
                out.push(run);
            }
        } else {
            i += 1;
        }
    }
    out
}

/// `true` if the trimmed text ends with `?` possibly followed by whitespace —
/// the JS `/\?\s*$/.test(text.trim())`. Since `.trim()` strips trailing
/// whitespace first, this is "the trimmed line's last char is `?`".
fn ends_with_question(text: &str) -> bool {
    text.trim().ends_with('?')
}

/// The `OPENQ_STOP` stopword set, verbatim from index.html (~line 2494). Used to
/// drop function words from the open-question keyword overlap.
static STOPWORDS: std::sync::LazyLock<std::collections::HashSet<&'static str>> =
    std::sync::LazyLock::new(|| {
        // Exact string from index.html, split on spaces.
        STOPWORDS_SRC.split(' ').collect()
    });

/// The raw `OPENQ_STOP` source, byte-identical to index.html so the keyword
/// filter matches the JS exactly.
const STOPWORDS_SRC: &str = "the a an and or but if then of to in on at for with from by is are was were be been being this that these those we you they it i he she them us our your their will would can could should do does did not as so about into over under more most very just also out up down off than too what how why when where who which whats hows";

/// Aggregate the per-category note counters (decisions / actions / keypoints) and
/// the open-question count into the boundary [`NoteCounters`]. The questions
/// count is the *open* count (the index.html `OpenQs._updateCount` overwrites the
/// raw question-section count with the open count).
#[must_use]
pub fn counters(decisions: u32, actions: u32, keypoints: u32, open_questions: u32) -> NoteCounters {
    NoteCounters {
        decisions,
        actions,
        keypoints,
        questions: open_questions,
    }
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests use unwrap/expect as the assertion mechanism (PRD lint config)"
)]
mod tests {
    use super::*;

    #[test]
    fn ends_with_question_matches_js() {
        assert!(ends_with_question("is this open?"));
        assert!(ends_with_question("is this open?   "));
        assert!(!ends_with_question("this is closed."));
        assert!(!ends_with_question("no terminator"));
    }

    #[test]
    fn keywords_drop_stopwords_and_short_words() {
        // "we should migrate the database" → drop we/should/the (stop) and any
        // < 3-char words; keep migrate, database. "we" is 2 chars (skipped by
        // the {2,} length rule too) and a stopword.
        let kw = content_keywords("We should migrate the database");
        assert_eq!(kw, vec!["migrate".to_string(), "database".to_string()]);
    }

    #[test]
    fn keywords_dedupe_preserving_first_seen() {
        let kw = content_keywords("plan plan PLAN review");
        assert_eq!(kw, vec!["plan".to_string(), "review".to_string()]);
    }

    #[test]
    fn open_questions_resolution_needs_two_overlap() {
        let mut oq = OpenQuestions::new();
        oq.add(1, "How should we handle authentication for the mobile app?");
        assert_eq!(oq.open_count(), 1);
        // One overlap ("authentication") does not resolve.
        let r = oq.consider("authentication is hard generally speaking here");
        assert!(r.is_empty());
        assert_eq!(oq.open_count(), 1);
        // Two overlaps ("authentication", "mobile") resolve it.
        let r = oq.consider("For authentication on mobile we will reuse OAuth tokens.");
        assert_eq!(r, vec![1]);
        assert_eq!(oq.open_count(), 0);
        assert!(oq.open_texts().is_empty());
    }

    #[test]
    fn consider_skips_question_lines() {
        let mut oq = OpenQuestions::new();
        oq.add(1, "What database should we migrate to?");
        // A line that is itself a question must not resolve anything, even with
        // overlap.
        let r = oq.consider("which database should we migrate to instead?");
        assert!(r.is_empty());
        assert_eq!(oq.open_count(), 1);
    }

    #[test]
    fn flush_under_eight_chars_emits_nothing() {
        let mut ex = NoteExtractor::new();
        // "Hi" never terminates; buffer holds " Hi" (3 chars > ... trim → "Hi"
        // = 2 < 8) → flush clears and emits nothing.
        let live = ex.analyze("Hi");
        assert!(live.is_empty());
        let flushed = ex.flush();
        assert!(flushed.is_empty());
    }
}
