//! Notes, smart-questions, and corrections policy (Phase 3).
//!
//! Houses the `NoteExtractor` trigger policy (decisions / actions / key points /
//! open questions — ported with byte-identical goldens from the current regexes
//! before any improvement), open-question tracking, word-correction application,
//! smart-question scheduling ([`questions`]: type rotation, reroll, recap,
//! new-question badge), and the Qwen final-notes pipeline ([`qwen`]: ~500-char
//! chunking up to 22 chunks, dedup, `TAG|` parsing) driving the Qwen worker
//! through the typed boundary. The worker stays the executor; this crate is the
//! policy. The notes slot is **optional**: the orchestrator handles `None`
//! (transcript-only mode) as a first-class state (PRD R3 /
//! `silent_core::engine::NotesEngine`).
//!
//! # What lives here (Phase 3)
//!
//! - [`extractor`] — the [`extractor::NoteExtractor`] (the index.html
//!   `NoteEngine` trigger policy) and [`extractor::OpenQuestions`] (the
//!   `OpenQs` open-question tracker), ported byte-identically and pinned by the
//!   goldens in `goldens/extractor/` (generated by `goldens/gen/notes_ref.mjs`,
//!   a DOM-free reimplementation of the exact JS). The note command/event TYPES
//!   live in [`silent_core::notes`] — the typed boundary the UI wires against.
//! - [`questions`] — smart-question scheduling (Task G2).
//! - [`qwen`] — the Qwen final-notes chunk/dedup/`TAG|` parsing policy (Task G2).
//! - [`corrections`] — the [`corrections::Corrections`] word-correction policy
//!   (the index.html `applyCorrections` / `applyCorrectionsToTranscript` regex
//!   application), ported byte-identically and pinned by the goldens in
//!   `goldens/corrections/` (generated by `goldens/gen/corrections_ref.mjs`).
//!   The correction command/event TYPES live in [`silent_core::corrections`].
#![forbid(unsafe_code)]

pub mod corrections;
pub mod extractor;
pub mod questions;
pub mod qwen;

pub use corrections::Corrections;
pub use extractor::{NoteExtractor, OpenQuestions, TriggerNote, TriggerSet, counters};
