//! Notes, smart-questions, and corrections policy (stub — Phase 3).
//!
//! Will house the `NoteExtractor` trigger policy (decisions / actions / key
//! points / open questions — ported with byte-identical goldens from the
//! current regexes before any improvement), open-question tracking,
//! word-correction application, and smart-question scheduling (type rotation,
//! reroll, recap) driving the Qwen worker through the typed boundary. The
//! notes slot is **optional**: the orchestrator handles `None` (transcript-only
//! mode) as a first-class state (PRD R3 / `silent_core::engine::NotesEngine`).
//!
//! # What lives here (Phase 3, Task G1 — the trigger policy)
//!
//! - [`extractor`] — the [`extractor::NoteExtractor`] (the index.html
//!   `NoteEngine` trigger policy) and [`extractor::OpenQuestions`] (the
//!   `OpenQs` open-question tracker), ported byte-identically and pinned by the
//!   goldens in `goldens/extractor/` (generated by `goldens/gen/notes_ref.mjs`,
//!   a DOM-free reimplementation of the exact JS). The note command/event TYPES
//!   live in [`silent_core::notes`] — the typed boundary the UI wires against.
//!
//! Smart-question scheduling, word-correction application, and the Qwen
//! chunking/dedup/`TAG|` parsing (Tasks G2–G4) land in later modules here.
#![forbid(unsafe_code)]

pub mod extractor;

pub use extractor::{NoteExtractor, OpenQuestions, TriggerNote, TriggerSet, counters};
