//! Smart-question scheduling policy (PRD Phase 3, Appendix A row 21).
//!
//! Pure Rust port of the `SmartQ` teleprompter controller and the stop-time
//! question-recap cleaning from index.html. The Qwen worker
//! (`question-worker.js`) stays the executor: this policy owns the timing gates,
//! the rolling transcript window, the clarify/risk/follow-up/coverage/deepen
//! type rotation, the dedup ring, the reroll/minimize/badge state, and the recap
//! line cleaning. The worker only runs the model when this policy asks it to via
//! a [`QuestionEvent::GenerateRequest`].
//!
//! Determinism: the only two non-pure inputs in the JS — `Date.now()` and the
//! async model output — are made explicit. The scheduler takes the clock as a
//! `now_ms` argument (supporting command-log replay, PRD "The UI boundary"), and
//! the model output arrives as a separate [`Scheduler::on_worker_result`] call.
//! Everything here is therefore deterministic and proven equivalent to the
//! shipping JS by the goldens in `goldens/questions/` (generated by
//! `goldens/questions/reference/questions_reference.mjs`).

use silent_core::questions::{QuestionEvent, QuestionType};

/// ms between auto-generations (`SmartQ.MIN_INTERVAL`, index.html `~2192`).
pub const MIN_INTERVAL_MS: u64 = 60_000;
/// New transcript chars before a fresh auto-question (`SmartQ.MIN_CHARS`).
pub const MIN_CHARS: usize = 220;
/// Rolling context cap (`SmartQ.WINDOW_CHARS`).
pub const WINDOW_CHARS: usize = 1200;
/// Minimum window length before `_maybeGenerate` will fire (`this._win.length >= 120`).
const GEN_WINDOW_MIN: usize = 120;
/// Minimum window length `_generate` itself requires (`this._win.length < 40` guard).
const GENERATE_WINDOW_MIN: usize = 40;
/// Cap on the dedup ring (`if (this._recent.length > 8) this._recent.shift()`).
const RECENT_CAP: usize = 8;
/// Number of generation attempts per `_generate` (`attempt < 2`).
const MAX_ATTEMPTS: u8 = 2;

/// The default type rotation, in order (`SmartQ.TYPES`, index.html `~2201`).
pub const DEFAULT_TYPES: [QuestionType; 5] = [
    QuestionType::Clarify,
    QuestionType::Risk,
    QuestionType::Followup,
    QuestionType::Coverage,
    QuestionType::Deepen,
];

/// What the scheduler decided after an input.
///
/// Either it accumulated without generating (a gate blocked it), or it wants the
/// worker to run a generation — in which case the orchestrator emits the carried
/// [`QuestionEvent::GenerateRequest`] and later calls
/// [`Scheduler::on_worker_result`] with the reply.
#[derive(Debug, Clone, PartialEq)]
pub enum ScheduleOutcome {
    /// No generation: the window/char/time gate was not satisfied. The scheduler
    /// simply accumulated the text.
    Accumulated,
    /// A generation should run. The orchestrator forwards `request` to the worker
    /// and routes the reply back via [`Scheduler::on_worker_result`].
    Generate {
        /// The event to emit to the worker (carries the request id, window, and
        /// type to generate).
        request: QuestionEvent,
    },
}

/// One pending generation the scheduler is waiting on a worker reply for. Mirrors
/// the `myGen`/two-attempt loop in `SmartQ._generate`: the policy issues a
/// request, the worker replies, and the policy may issue a SECOND request (next
/// type) if the first reply duplicates a recent question.
#[derive(Debug, Clone)]
struct Pending {
    /// The request id last sent to the worker.
    request_id: u32,
    /// The generation epoch this pending belongs to (`myGen`); a [`Scheduler::reset`]
    /// or a newer generation supersedes older replies.
    epoch: u64,
    /// The transcript window this generation conditions on (fixed for both
    /// attempts, as in the JS where `this._win` is read once into the loop).
    window: String,
    /// Which attempt (0-based) this request is.
    attempt: u8,
    /// The type chosen for this attempt (already rotated `_typeIdx`).
    kind: QuestionType,
}

/// The result of feeding a worker reply back into the scheduler.
#[derive(Debug, Clone, PartialEq)]
pub enum WorkerOutcome {
    /// The reply was unique (or it was the final attempt): the question is ready
    /// to render. Carries the [`QuestionEvent::QuestionReady`] the UI displays.
    Ready(QuestionEvent),
    /// The reply duplicated a recent question and an attempt remains: a second
    /// generation (next type) should run. Carries its
    /// [`QuestionEvent::GenerateRequest`].
    Retry(QuestionEvent),
    /// The reply was for a superseded generation (a reset/newer gen happened) and
    /// is dropped (`if (myGen !== this._gen) return`).
    Superseded,
}

/// The `SmartQ` teleprompter scheduler — pure policy.
///
/// Owns the rolling window, timing gates, type rotation, dedup ring, and the
/// minimize/badge UI state. Issues [`QuestionEvent`]s; the worker executes.
#[derive(Debug, Clone)]
pub struct Scheduler {
    enabled_types: Vec<QuestionType>,
    win: String,
    last_gen_at: u64,
    chars_since_gen: usize,
    recent: Vec<String>,
    type_idx: usize,
    epoch: u64,
    seq: u32,
    pending: Option<Pending>,
    minimized: bool,
    has_new: bool,
    shown: Option<(String, QuestionType)>,
}

impl Default for Scheduler {
    fn default() -> Self {
        Self::new(&DEFAULT_TYPES)
    }
}

impl Scheduler {
    /// Construct a scheduler with the given enabled types (empty falls back to
    /// the full [`DEFAULT_TYPES`] rotation, matching `_enabledTypes`).
    #[must_use]
    pub fn new(enabled_types: &[QuestionType]) -> Self {
        let types = if enabled_types.is_empty() {
            DEFAULT_TYPES.to_vec()
        } else {
            enabled_types.to_vec()
        };
        Self {
            enabled_types: types,
            win: String::new(),
            last_gen_at: 0,
            chars_since_gen: 0,
            recent: Vec::new(),
            type_idx: 0,
            epoch: 0,
            seq: 0,
            pending: None,
            minimized: true,
            has_new: false,
            shown: None,
        }
    }

    /// Whether the teleprompter is minimized (mirrors the bar's `minimized` class).
    #[must_use]
    pub fn is_minimized(&self) -> bool {
        self.minimized
    }

    /// Whether the new-question badge dot is raised (`has-new`).
    #[must_use]
    pub fn has_new_badge(&self) -> bool {
        self.has_new
    }

    /// The currently-shown question + type, if any (for re-render / tests).
    #[must_use]
    pub fn shown(&self) -> Option<(&str, QuestionType)> {
        self.shown.as_ref().map(|(q, t)| (q.as_str(), *t))
    }

    /// Current rolling-window length in chars (`this._win.length`). Exposed for
    /// diagnostics and golden parity assertions.
    #[must_use]
    pub fn window_len(&self) -> usize {
        js_len(&self.win)
    }

    /// A snapshot of the dedup ring (`this._recent`), oldest first. Exposed for
    /// diagnostics and golden parity assertions.
    #[must_use]
    pub fn recent_snapshot(&self) -> Vec<String> {
        self.recent.clone()
    }

    /// Reset all scheduling state for a new meeting (`SmartQ.reset`). Bumps the
    /// generation epoch so any in-flight worker reply is dropped.
    pub fn reset(&mut self) {
        self.win.clear();
        self.last_gen_at = 0;
        self.chars_since_gen = 0;
        self.recent.clear();
        self.type_idx = 0;
        self.epoch += 1;
        self.pending = None;
        self.shown = None;
        self.has_new = false;
    }

    /// Accumulate a finalized transcript fragment at time `now_ms`
    /// (`SmartQ.accumulate` → `_maybeGenerate`). Returns whether a generation
    /// should run.
    ///
    /// Empty/whitespace-only text is ignored (`if (!t) return`). The window grows
    /// then tail-caps at [`WINDOW_CHARS`]; `chars_since_gen` grows by the
    /// fragment's length.
    pub fn accumulate(&mut self, text: &str, now_ms: u64) -> ScheduleOutcome {
        let t = js_trim(text);
        if t.is_empty() {
            return ScheduleOutcome::Accumulated;
        }
        // `this._win = (this._win + ' ' + t).slice(-WINDOW_CHARS)`
        let mut combined = String::with_capacity(self.win.len() + 1 + t.len());
        combined.push_str(&self.win);
        combined.push(' ');
        combined.push_str(t);
        self.win = slice_tail(&combined, WINDOW_CHARS);
        // `this._charsSinceGen += t.length`
        self.chars_since_gen += js_len(t);
        if self.should_generate(now_ms) {
            self.start_generation(now_ms)
        } else {
            ScheduleOutcome::Accumulated
        }
    }

    /// `SmartQ._maybeGenerate` gate: not busy, enough new chars, enough elapsed
    /// time, and the window is long enough.
    fn should_generate(&self, now_ms: u64) -> bool {
        if self.pending.is_some() {
            return false; // `if (this._busy) return`
        }
        let enough_new = self.chars_since_gen >= MIN_CHARS;
        let enough_time = self.last_gen_at == 0 || (now_ms - self.last_gen_at) >= MIN_INTERVAL_MS;
        js_len(&self.win) >= GEN_WINDOW_MIN && enough_new && enough_time
    }

    /// `SmartQ.reroll`: expand the bar if minimized (clearing the badge), then
    /// force a generation regardless of the gates. Returns the
    /// [`ScheduleOutcome`]; the caller should also emit a
    /// [`QuestionEvent::MinimizeChanged`] when `expanded` is true (see
    /// [`Scheduler::was_just_expanded`] is not needed — the return tells you).
    pub fn reroll(&mut self, now_ms: u64) -> RerollOutcome {
        let expanded = if self.minimized {
            self.minimized = false;
            self.has_new = false;
            true
        } else {
            false
        };
        let outcome = self.start_generation(now_ms);
        RerollOutcome { expanded, outcome }
    }

    /// `_generate` start: guard on the 40-char window floor, stamp `last_gen_at`,
    /// reset `chars_since_gen`, bump the gen epoch, rotate to the first type, and
    /// issue the first [`QuestionEvent::GenerateRequest`].
    fn start_generation(&mut self, now_ms: u64) -> ScheduleOutcome {
        // `if (this._busy || this._win.length < 40) return`
        if self.pending.is_some() || js_len(&self.win) < GENERATE_WINDOW_MIN {
            return ScheduleOutcome::Accumulated;
        }
        self.last_gen_at = now_ms;
        self.chars_since_gen = 0;
        self.epoch += 1; // `const myGen = ++this._gen`
        let kind = self.next_type();
        let window = self.win.clone();
        let request_id = self.next_seq();
        self.pending = Some(Pending {
            request_id,
            epoch: self.epoch,
            window: window.clone(),
            attempt: 0,
            kind,
        });
        ScheduleOutcome::Generate {
            request: QuestionEvent::GenerateRequest {
                request_id,
                window,
                kind,
            },
        }
    }

    /// Feed a worker reply back into the scheduler (`SmartQ._generate`'s loop body
    /// after each `await sharedQuestionGenerator.generate(...)`).
    ///
    /// Applies the dedup rule: a unique question (not in the `_recent` ring, by
    /// [`norm`]) is accepted and rendered; a duplicate triggers a second attempt
    /// (next type) if one remains, else the duplicate is rendered anyway (the JS
    /// `best` fallback). Replies for a superseded generation are dropped.
    pub fn on_worker_result(&mut self, request_id: u32, text: &str) -> WorkerOutcome {
        let Some(pending) = self.pending.clone() else {
            return WorkerOutcome::Superseded; // no generation in flight
        };
        if pending.request_id != request_id || pending.epoch != self.epoch {
            // `if (myGen !== this._gen) return` — superseded by reset/newer gen,
            // or a stale reply for an earlier request id.
            return WorkerOutcome::Superseded;
        }
        let is_unique = !text.is_empty() && !self.recent.iter().any(|r| r == &norm(text));
        let last_attempt = pending.attempt + 1 >= MAX_ATTEMPTS;
        if is_unique || last_attempt {
            // Accept this reply (`best`). Push to the recent ring and render.
            self.pending = None;
            self.recent.push(norm(text));
            if self.recent.len() > RECENT_CAP {
                self.recent.remove(0); // `this._recent.shift()`
            }
            let kind = pending.kind;
            self.shown = Some((text.to_owned(), kind));
            let badge = self.minimized; // `if (b.classList.contains('minimized')) add('has-new')`
            if badge {
                self.has_new = true;
            }
            WorkerOutcome::Ready(QuestionEvent::QuestionReady {
                text: text.to_owned(),
                kind,
                badge,
            })
        } else {
            // Duplicate and an attempt remains: rotate type, re-issue against the
            // SAME window (the JS reads `this._win` once at loop entry).
            let kind = self.next_type();
            let request_id = self.next_seq();
            self.pending = Some(Pending {
                request_id,
                epoch: pending.epoch,
                window: pending.window.clone(),
                attempt: pending.attempt + 1,
                kind,
            });
            WorkerOutcome::Retry(QuestionEvent::GenerateRequest {
                request_id,
                window: pending.window,
                kind,
            })
        }
    }

    /// `toggleSmartQ`: flip minimize; expanding clears the badge.
    pub fn toggle_minimize(&mut self) -> QuestionEvent {
        self.minimized = !self.minimized;
        if !self.minimized {
            self.has_new = false; // seen → clear dot
        }
        QuestionEvent::MinimizeChanged {
            minimized: self.minimized,
        }
    }

    /// `const type = types[this._typeIdx++ % types.length]` — return the current
    /// rotation type and advance the index.
    fn next_type(&mut self) -> QuestionType {
        let idx = self.type_idx % self.enabled_types.len();
        self.type_idx += 1;
        self.enabled_types[idx]
    }

    /// `++this._seq` — monotonic request id.
    fn next_seq(&mut self) -> u32 {
        self.seq += 1;
        self.seq
    }
}

/// The outcome of [`Scheduler::reroll`]: whether the bar expanded plus the
/// generation outcome.
#[derive(Debug, Clone, PartialEq)]
pub struct RerollOutcome {
    /// `true` if the reroll expanded a minimized bar (the UI should emit a
    /// [`QuestionEvent::MinimizeChanged`] with `minimized: false`).
    pub expanded: bool,
    /// The scheduling outcome (the generation that reroll forces).
    pub outcome: ScheduleOutcome,
}

/// Normalize a question for the dedup ring (`SmartQ._norm`): lowercase, then
/// collapse every run of non-`[a-z0-9]` to a single space, then trim.
///
/// Byte-identical port of `q.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()`.
#[must_use]
pub fn norm(q: &str) -> String {
    let lower = q.to_lowercase();
    let mut out = String::with_capacity(lower.len());
    let mut in_run = false;
    for ch in lower.chars() {
        if ch.is_ascii_lowercase() || ch.is_ascii_digit() {
            out.push(ch);
            in_run = false;
        } else if !in_run {
            out.push(' ');
            in_run = true;
        }
    }
    // `.trim()` — and since the only inserted char is a single ASCII space,
    // trimming ASCII whitespace suffices.
    out.trim().to_owned()
}

/// Clean one per-type recap group's raw model output
/// (`generateQuestionRecap`, index.html `~4829`): split on newlines, strip a
/// leading run of whitespace / `-` / digits / `.` / `)`, strip a single leading
/// and trailing quote, trim, drop lines of length ≤ 6, dedup (insertion order),
/// keep the first 3.
#[must_use]
pub fn recap_clean_group(raw: &str) -> Vec<String> {
    let mut seen: Vec<String> = Vec::new();
    for line in raw.split('\n') {
        // `.replace(/^[\s\-\d.\)]+/, '')`
        let stripped = line.trim_start_matches(|c: char| {
            c.is_whitespace()
                || c == '\u{feff}'
                || c == '-'
                || c.is_ascii_digit()
                || c == '.'
                || c == ')'
        });
        // `.replace(/^["']|["']$/g, '')` — strips ONE leading and ONE trailing
        // quote (a single global pass over two anchored alternations).
        let stripped = strip_one_edge_quote(stripped);
        // `.trim()`
        let cleaned = js_trim(&stripped);
        // `.filter(x => x.length > 6)`
        if js_len(cleaned) <= 6 {
            continue;
        }
        let cleaned = cleaned.to_owned();
        if !seen.contains(&cleaned) {
            seen.push(cleaned);
        }
    }
    seen.truncate(3);
    seen
}

/// `.replace(/^["']|["']$/g, '')`: remove at most one leading and one trailing
/// quote character (`"` or `'`). The global flag with anchored alternations
/// removes the first match at the start and the last match at the end, each at
/// most once.
fn strip_one_edge_quote(s: &str) -> String {
    let mut chars: Vec<char> = s.chars().collect();
    if matches!(chars.first(), Some('"' | '\'')) {
        chars.remove(0);
    }
    if matches!(chars.last(), Some('"' | '\'')) {
        chars.pop();
    }
    chars.into_iter().collect()
}

// ── Shared JS-string helpers (kept module-local; `qwen.rs` has its own copies
// because the two modules are independent ports and must each stand alone for
// review). ─────────────────────────────────────────────────────────────────

/// JS `String.prototype.trim()` (ECMAScript whitespace + BOM).
fn js_trim(s: &str) -> &str {
    s.trim_matches(|c: char| c.is_whitespace() || c == '\u{feff}')
}

/// JS `.length` (UTF-16 code units approximated by `char` count for BMP text).
fn js_len(s: &str) -> usize {
    s.chars().count()
}

/// JS `str.slice(-n)`: the last `n` chars. Used for the [`WINDOW_CHARS`] tail cap.
fn slice_tail(s: &str, n: usize) -> String {
    let total = s.chars().count();
    if total <= n {
        return s.to_owned();
    }
    s.chars().skip(total - n).collect()
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests use unwrap/expect as the assertion mechanism (PRD lint config)"
)]
mod tests {
    use super::*;

    #[test]
    fn norm_collapses_punctuation() {
        assert_eq!(norm("Hello, World!"), "hello world");
        assert_eq!(norm("  Spaces   and—dashes  "), "spaces and dashes");
        assert_eq!(norm("???"), "");
    }

    #[test]
    fn short_window_does_not_generate() {
        let mut s = Scheduler::default();
        assert_eq!(s.accumulate("short", 1000), ScheduleOutcome::Accumulated);
    }

    #[test]
    fn first_generation_rotates_to_clarify() {
        let mut s = Scheduler::default();
        let long = "word ".repeat(50); // 250 chars > MIN_CHARS, window > 120
        match s.accumulate(&long, 5000) {
            ScheduleOutcome::Generate {
                request: QuestionEvent::GenerateRequest { kind, .. },
            } => assert_eq!(kind, QuestionType::Clarify),
            other => panic!("expected generate, got {other:?}"),
        }
    }

    #[test]
    fn dedup_retry_advances_type() {
        let mut s = Scheduler::default();
        let long = "word ".repeat(50);
        // First generation → clarify; reply "Repeat?" accepted, lands in recent.
        let ScheduleOutcome::Generate {
            request: QuestionEvent::GenerateRequest { request_id, .. },
        } = s.accumulate(&long, 0)
        else {
            panic!("expected generate")
        };
        assert!(matches!(
            s.on_worker_result(request_id, "Repeat question?"),
            WorkerOutcome::Ready(_)
        ));
        // Second generation (after the interval). First attempt duplicates → retry.
        let ScheduleOutcome::Generate {
            request:
                QuestionEvent::GenerateRequest {
                    request_id, kind, ..
                },
        } = s.accumulate(&long, 61_000)
        else {
            panic!("expected generate")
        };
        assert_eq!(kind, QuestionType::Risk); // type advanced from clarify
        let WorkerOutcome::Retry(QuestionEvent::GenerateRequest {
            request_id, kind, ..
        }) = s.on_worker_result(request_id, "Repeat question?")
        else {
            panic!("expected retry on duplicate")
        };
        assert_eq!(kind, QuestionType::Followup); // advanced again
        assert!(matches!(
            s.on_worker_result(request_id, "Fresh question?"),
            WorkerOutcome::Ready(_)
        ));
    }

    #[test]
    fn reset_supersedes_in_flight_reply() {
        let mut s = Scheduler::default();
        let long = "word ".repeat(50);
        let ScheduleOutcome::Generate {
            request: QuestionEvent::GenerateRequest { request_id, .. },
        } = s.accumulate(&long, 0)
        else {
            panic!("expected generate")
        };
        s.reset();
        assert_eq!(
            s.on_worker_result(request_id, "late reply"),
            WorkerOutcome::Superseded
        );
    }
}
