//! Qwen final-notes policy (PRD Phase 3, Appendix A row 19).
//!
//! Pure Rust port of the Qwen note-extraction pipeline from index.html
//! (`parseQwenNotes`, `chunkTranscript`, `dedupeNotes`, and the
//! `generateFinalNotes` chunk-target + 22-chunk cap). The Qwen worker
//! (`question-worker.js`) stays the executor: this policy decides the chunks and
//! the system prompt, the worker runs the model, and this policy parses + dedups
//! what comes back. No model, no DOM, no I/O — every function here is
//! deterministic and proven byte-identical to the shipping JS by the goldens in
//! `goldens/qwen/` (generated by `goldens/qwen/reference/qwen_reference.mjs`).
//!
//! # Why hand-rolled, not `regex`
//!
//! The JS source uses three small regexes. They are reproduced by hand (with the
//! exact source regex quoted at each site) rather than pulling in the `regex`
//! crate, so this pure-policy crate stays dependency-light on its
//! `wasm32-unknown-unknown` target. The golden parity tests are the proof the
//! hand-rolled matchers behave identically to the JS regexes for the captured
//! behavior.

use silent_core::questions::QwenNote;

/// The note category each Qwen tag maps to (the UI list id). VERBATIM from
/// `NOTE_CAT_MAP` in index.html (`~2430`).
fn note_cat(tag: &str) -> &'static str {
    match tag {
        "DECISION" => "decisions",
        "ACTION" => "actions",
        "KEYPOINT" => "keypoints",
        "QUESTION" => "questions",
        // Only the five tags below ever reach here (TOPIC is handled before this
        // call); the parser never constructs a note for an unknown tag.
        _ => "",
    }
}

/// JS `String.prototype.trim()`: strip leading/trailing whitespace.
///
/// `parseQwenNotes` and `chunkTranscript` lean on `.trim()`. JS trims the
/// ECMAScript `WhiteSpace` + `LineTerminator` set; for the characters that appear in
/// transcript/model text this coincides with Rust's `char::is_whitespace` plus
/// the BOM (`U+FEFF`), which Rust does not classify as whitespace. We include the
/// BOM explicitly so the behavior matches JS exactly.
fn js_trim(s: &str) -> &str {
    let is_js_ws = |c: char| c.is_whitespace() || c == '\u{feff}';
    s.trim_matches(is_js_ws)
}

/// The leading bullet/space strip `^[-*\s]*` from the `parseQwenNotes` line
/// regex: skip any run of `-`, `*`, or whitespace at the start of the line.
fn strip_leading_bullets(s: &str) -> &str {
    s.trim_start_matches(|c: char| c == '-' || c == '*' || c.is_whitespace() || c == '\u{feff}')
}

/// One of the five recognized tags at the start of `rest` (case-insensitive),
/// returning the canonical uppercase tag and the remainder after it. Mirrors the
/// `(TOPIC|DECISION|ACTION|KEYPOINT|QUESTION)` alternation (the regex tries them
/// in this order; only the longest-matching token matters and none is a prefix
/// of another, so iteration order is immaterial).
fn match_tag(rest: &str) -> Option<(&'static str, &str)> {
    const TAGS: [&str; 5] = ["TOPIC", "DECISION", "ACTION", "KEYPOINT", "QUESTION"];
    for tag in TAGS {
        // Compare the leading bytes, never slicing a string. `rest[..tag.len()]`
        // would PANIC when `tag.len()` lands inside a multi-byte char (e.g. a
        // line like "ACTION – text": at the `–` (en-dash, 3 bytes) the 8-byte
        // "KEYPOINT" probe would split it). The tags are pure ASCII, so an
        // ASCII-case-insensitive byte-prefix compare is exact and panic-free.
        let tb = tag.as_bytes();
        let rb = rest.as_bytes();
        if rb.len() >= tb.len() && rb[..tb.len()].eq_ignore_ascii_case(tb) {
            return Some((tag, &rest[tag.len()..]));
        }
    }
    None
}

/// The separator `\s*[|:\-–]\s*` between the tag and the note text: optional
/// whitespace, then exactly one of `|`, `:`, `-`, or `–` (en-dash U+2013), then
/// optional whitespace. Returns the text after the separator, or `None` if no
/// valid separator is present.
fn match_separator(rest: &str) -> Option<&str> {
    let after_ws = rest.trim_start_matches(|c: char| c.is_whitespace() || c == '\u{feff}');
    let mut chars = after_ws.char_indices();
    let (_, sep) = chars.next()?;
    if !matches!(sep, '|' | ':' | '-' | '–') {
        return None;
    }
    let after_sep = &after_ws[sep.len_utf8()..];
    Some(after_sep.trim_start_matches(|c: char| c.is_whitespace() || c == '\u{feff}'))
}

/// Strip a `<think>…</think>` block (non-greedy, dot-all), matching the JS
/// `.replace(/<think>[\s\S]*?<\/think>/g, '')`. Repeats for every occurrence.
fn strip_think(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(start) = rest.find("<think>") {
        out.push_str(&rest[..start]);
        let after_open = &rest[start + "<think>".len()..];
        if let Some(end) = after_open.find("</think>") {
            rest = &after_open[end + "</think>".len()..];
        } else {
            // No closing tag: JS leaves the unmatched "<think>" in place.
            out.push_str("<think>");
            rest = after_open;
        }
    }
    out.push_str(rest);
    out
}

/// JS `.replace(/^["'\s]+|["'\s]+$/g, '')`: strip leading/trailing runs of
/// quotes and whitespace.
fn strip_edge_quotes_ws(s: &str) -> &str {
    let is_qws = |c: char| c == '"' || c == '\'' || c.is_whitespace() || c == '\u{feff}';
    s.trim_matches(is_qws)
}

/// JS regex `/^none\.?$/i` test: the whole string is `none` optionally followed
/// by a single `.`, case-insensitive.
fn is_none_line(s: &str) -> bool {
    let lower = s.to_ascii_lowercase();
    lower == "none" || lower == "none."
}

/// Count `char`s the way JS `String.prototype.length` counts UTF-16 code units —
/// for the all-ASCII / BMP text these notes carry, `chars().count()` matches.
/// The length floors/caps below (`< 4`, `> 60`, `> 160`) use this so truncation
/// happens at the same boundary as the JS.
///
/// Note: JS `.length` is UTF-16 units, so an astral char counts as 2. Transcript
/// note text is overwhelmingly BMP; if an astral char ever appears, the cap
/// would differ by one position. This is accepted as out-of-scope for the parity
/// contract (no golden exercises astral text, mirroring real Qwen note output).
fn js_len(s: &str) -> usize {
    s.chars().count()
}

/// Take the first `n` chars (JS `.slice(0, n)` for BMP text).
fn js_slice(s: &str, n: usize) -> &str {
    match s.char_indices().nth(n) {
        Some((idx, _)) => &s[..idx],
        None => s,
    }
}

/// Parse Qwen note output. Accepts `TAG| text`, `TAG: text`, `TAG - text`, or
/// `TAG – text`; drops `NONE`/empties. `TOPIC` lines set the outline heading
/// carried by every following note from the same chunk.
///
/// Byte-identical port of `parseQwenNotes` (index.html `~2434`).
#[must_use]
pub fn parse_qwen_notes(raw: &str) -> Vec<QwenNote> {
    let mut out = Vec::new();
    let mut topic: Option<String> = None;
    let cleaned = strip_think(raw);
    for line in cleaned.split('\n') {
        let line = js_trim(line);
        if line.is_empty() || is_none_line(line) {
            continue;
        }
        // `^[-*\s]*(TAG)\s*[|:\-–]\s*(.+)$`
        let after_bullets = strip_leading_bullets(line);
        let Some((tag, after_tag)) = match_tag(after_bullets) else {
            continue;
        };
        let Some(text_part) = match_separator(after_tag) else {
            continue;
        };
        // The regex group `(.+)` requires at least one char after the separator;
        // an empty remainder means the line did not match.
        if text_part.is_empty() {
            continue;
        }
        let text = strip_edge_quotes_ws(text_part);
        let text = js_trim(text); // the JS does `.replace(...).trim()`
        if js_len(text) < 4 || is_none_line(text) {
            continue;
        }
        if tag == "TOPIC" {
            // `topic = text.length > 60 ? text.slice(0,59).trim() + '…' : text`
            topic = Some(if js_len(text) > 60 {
                format!("{}…", js_trim(js_slice(text, 59)))
            } else {
                text.to_owned()
            });
            continue;
        }
        // `if (text.length > 160) text = text.slice(0,159).trim() + '…'`
        let final_text = if js_len(text) > 160 {
            format!("{}…", js_trim(js_slice(text, 159)))
        } else {
            text.to_owned()
        };
        out.push(QwenNote {
            cat: note_cat(tag).to_owned(),
            text: final_text,
            topic: topic.clone(),
        });
    }
    out
}

/// Split `text` into sentences the way the JS regex
/// `/[^.!?]+[.!?]+|\S[^.!?]*$/g` does: greedily take a run of non-terminators
/// followed by one-or-more terminators (`.!?`); else, at end of input, take a
/// trailing run that starts with a non-space and has no terminator.
fn split_sentences(text: &str) -> Vec<&str> {
    let bytes = text.as_bytes();
    let is_term = |b: u8| b == b'.' || b == b'!' || b == b'?';
    let mut matches = Vec::new();
    let mut i = 0;
    let n = bytes.len();
    while i < n {
        // Alternative 1: `[^.!?]+[.!?]+`
        let start = i;
        let mut j = i;
        while j < n && !is_term(bytes[j]) {
            j += 1;
        }
        if j < n && is_term(bytes[j]) {
            // We have at least one non-terminator? `[^.!?]+` requires ≥1. If the
            // run of non-terminators was empty (j == start), this alternative
            // fails and we fall through to skip the leading terminator(s).
            if j > start {
                let mut k = j;
                while k < n && is_term(bytes[k]) {
                    k += 1;
                }
                matches.push(&text[start..k]);
                i = k;
                continue;
            }
            // Leading terminator with no preceding non-terminator char: the JS
            // regex's global scan advances past it (neither alternative matches
            // an empty `[^.!?]+` nor `\S` on a terminator), so we skip one char.
            i = j + 1;
            continue;
        }
        // Reached end of input with no terminator in `[start..n]`.
        // Alternative 2: `\S[^.!?]*$` — a trailing run that must START with a
        // non-space char. JS's scanner, having consumed up to `start`, tries to
        // match at successive positions; the first position whose char is
        // non-space anchors the trailing match.
        let tail = &text[start..];
        let trimmed_start = tail.trim_start_matches(|c: char| c.is_whitespace() || c == '\u{feff}');
        if !trimmed_start.is_empty() {
            matches.push(trimmed_start);
        }
        break;
    }
    matches
}

/// Split a transcript into ~`target`-char chunks on sentence boundaries.
///
/// Byte-identical port of `chunkTranscript` (index.html `~2452`). When there are
/// no sentence matches, the JS falls back to `[String(text)]` (the whole text as
/// one segment); the packing loop then trims it and packs it as one chunk.
#[must_use]
pub fn chunk_transcript(text: &str, target: usize) -> Vec<String> {
    let sentences = split_sentences(text);
    // JS: `const sentences = text.match(re) || [text]`
    let owned_fallback;
    let sentences: &[&str] = if sentences.is_empty() {
        owned_fallback = [text];
        &owned_fallback
    } else {
        &sentences
    };

    let mut chunks: Vec<String> = Vec::new();
    let mut cur = String::new();
    for s in sentences {
        let seg = js_trim(s);
        if seg.is_empty() {
            continue;
        }
        // `if (cur && (cur.length + seg.length + 1) > target) { push; cur = '' }`
        if !cur.is_empty() && (js_len(&cur) + js_len(seg) + 1) > target {
            chunks.push(std::mem::take(&mut cur));
        }
        // `cur += (cur ? ' ' : '') + seg`
        if !cur.is_empty() {
            cur.push(' ');
        }
        cur.push_str(seg);
    }
    if !cur.is_empty() {
        chunks.push(cur);
    }
    chunks
}

/// The content-word stopword set (`OPENQ_STOP`, index.html `~2494`), reused by
/// the note dedup.
const OPENQ_STOP: &[&str] = &[
    "the", "a", "an", "and", "or", "but", "if", "then", "of", "to", "in", "on", "at", "for",
    "with", "from", "by", "is", "are", "was", "were", "be", "been", "being", "this", "that",
    "these", "those", "we", "you", "they", "it", "i", "he", "she", "them", "us", "our", "your",
    "their", "will", "would", "can", "could", "should", "do", "does", "did", "not", "as", "so",
    "about", "into", "over", "under", "more", "most", "very", "just", "also", "out", "up", "down",
    "off", "than", "too", "what", "how", "why", "when", "where", "who", "which", "whats", "hows",
];

/// Content-word set for dedup, lowercased: `/\b[a-z][a-z']{2,}\b/g` minus
/// stopwords (`_noteKw`, index.html `~2466`).
///
/// The JS regex matches, in the lowercased string, a word boundary, then a
/// `[a-z]` start, then 2+ of `[a-z']`, then a word boundary. Crucially `'` is in
/// the inner class but NOT a word char for `\b`, so a trailing apostrophe is
/// excluded by the closing `\b` (it would not sit on a word boundary). We
/// reproduce that: collect maximal runs of `[a-z']` whose first char is `[a-z]`
/// and length ≥ 3, then trim a trailing `'` (the `\b` cannot fall after it).
fn note_kw(t: &str) -> std::collections::HashSet<String> {
    let lower = t.to_lowercase();
    let bytes = lower.as_bytes();
    let n = bytes.len();
    let is_az = |b: u8| b.is_ascii_lowercase();
    let is_inner = |b: u8| b.is_ascii_lowercase() || b == b'\'';
    let mut set = std::collections::HashSet::new();
    let mut i = 0;
    while i < n {
        if is_az(bytes[i]) {
            // Maximal `[a-z'][a-z']*` run anchored on a `[a-z]` start.
            let start = i;
            let mut j = i + 1;
            while j < n && is_inner(bytes[j]) {
                j += 1;
            }
            let mut word = &lower[start..j];
            // `\b` after the run: a trailing `'` is not a word-boundary edge, so
            // the regex's closing `\b` excludes it from the match.
            word = word.trim_end_matches('\'');
            // The JS requires total length ≥ 3 (`[a-z]` + `{2,}`). Apostrophes
            // inside count toward the inner `{2,}`. Measure AFTER trimming the
            // trailing apostrophe because that char was never part of the match.
            if word.len() >= 3 && !OPENQ_STOP.contains(&word) {
                set.insert(word.to_owned());
            }
            i = j;
        } else {
            i += 1;
        }
    }
    set
}

/// Drop near-duplicate notes (same category, ≥60% keyword overlap) from
/// overlapping chunks. Byte-identical port of `dedupeNotes` (index.html
/// `~2470`); order of survivors is preserved.
#[must_use]
pub fn dedupe_notes(notes: Vec<QwenNote>) -> Vec<QwenNote> {
    let mut kept: Vec<QwenNote> = Vec::new();
    let mut kept_kw: Vec<std::collections::HashSet<String>> = Vec::new();
    for n in notes {
        let kw = note_kw(&n.text);
        let mut dup = false;
        for (k, kkw) in kept.iter().zip(kept_kw.iter()) {
            if k.cat != n.cat {
                continue;
            }
            if kw.is_empty() || kkw.is_empty() {
                // Empty-keyword path: only an exact (case-insensitive) text match
                // counts as a duplicate.
                if k.text.to_lowercase() == n.text.to_lowercase() {
                    dup = true;
                    break;
                }
                continue;
            }
            let inter = kw.iter().filter(|w| kkw.contains(*w)).count();
            let min = kw.len().min(kkw.len());
            // `inter / Math.min(...) >= 0.6` in JS float math.
            #[allow(
                clippy::cast_precision_loss,
                reason = "keyword counts are small (≤ a few dozen); f64 represents \
                          them exactly, matching the JS Number division"
            )]
            if (inter as f64) / (min as f64) >= 0.6 {
                dup = true;
                break;
            }
        }
        if !dup {
            kept_kw.push(kw);
            kept.push(n);
        }
    }
    kept
}

/// The final-notes chunking the `generateFinalNotes` method performs before
/// dispatching chunks to the worker: `target = max(500, ceil(len / 18))`, then
/// `chunkTranscript(transcript, target).slice(0, 22)` (index.html `~4866`).
///
/// Returned chunks are the per-chunk inputs the policy hands the Qwen worker;
/// the worker runs the model on each and replies, and the policy then
/// [`parse_qwen_notes`] + [`dedupe_notes`] the aggregate.
#[must_use]
pub fn final_notes_chunks(transcript: &str) -> Vec<String> {
    let len = js_len(transcript);
    // `Math.ceil(len / 18)` over integers = (len + 17) / 18.
    let target = std::cmp::max(500, len.div_ceil(18));
    let mut chunks = chunk_transcript(transcript, target);
    chunks.truncate(22);
    chunks
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests use unwrap/expect as the assertion mechanism (PRD lint config)"
)]
mod tests {
    use super::*;

    #[test]
    fn note_cat_maps_each_tag() {
        assert_eq!(note_cat("DECISION"), "decisions");
        assert_eq!(note_cat("ACTION"), "actions");
        assert_eq!(note_cat("KEYPOINT"), "keypoints");
        assert_eq!(note_cat("QUESTION"), "questions");
    }

    #[test]
    fn parses_pipe_separator() {
        let notes = parse_qwen_notes("DECISION| We will ship on Friday");
        assert_eq!(notes.len(), 1);
        assert_eq!(notes[0].cat, "decisions");
        assert_eq!(notes[0].text, "We will ship on Friday");
        assert!(notes[0].topic.is_none());
    }

    #[test]
    fn topic_carries_to_following_notes() {
        let notes = parse_qwen_notes("TOPIC| Roadmap\nDECISION| Ship v2");
        assert_eq!(notes.len(), 1);
        assert_eq!(notes[0].topic.as_deref(), Some("Roadmap"));
    }

    #[test]
    fn drops_short_text() {
        assert!(parse_qwen_notes("ACTION| ok").is_empty());
    }

    #[test]
    fn en_dash_separator_does_not_panic_on_tag_probe() {
        // Regression: `match_tag` must not byte-slice a multi-byte char. The
        // en-dash (`–`, 3 bytes) sits where the 8-byte "KEYPOINT" probe length
        // lands inside it, which previously panicked. The `–` is a supported
        // separator, so this line MUST parse to one action note.
        let notes = parse_qwen_notes("ACTION – do the thing here");
        assert_eq!(notes.len(), 1, "got: {notes:?}");
        assert_eq!(notes[0].cat, "actions");
        assert_eq!(notes[0].text, "do the thing here");
        // And the en-dash can also appear in the note TEXT without breaking the
        // tag probe (a non-ASCII byte before any tag length boundary).
        let notes2 = parse_qwen_notes("KEYPOINT| margin — 12 percent");
        assert_eq!(notes2.len(), 1);
        assert_eq!(notes2[0].text, "margin — 12 percent");
    }

    #[test]
    fn final_chunks_use_500_floor_and_cap_22() {
        // Short transcript → target floors at 500 → a single chunk.
        let chunks = final_notes_chunks("Short. Two sentences.");
        assert_eq!(chunks.len(), 1);
    }
}
