//! Golden test for the Dual-mode draft/refine coordinator.
//!
//! Replays the fixture generated by the reference JS in
//! `goldens/gen/dual_ref.mjs` — a DOM-free reimplementation of the EXACT
//! `index.html` dual-mode interleaving (`handlePartial`/`handleFinal` dual
//! branches; Appendix A row 11) — and asserts the Rust [`DualCoordinator`]
//! reproduces every transcript-list state, **event-for-event**.
//!
//! This is what makes the port verifiable rather than hand-asserted: the JS
//! behavior is captured FIRST (committed JSON, regenerable with
//! `node goldens/gen/dual_ref.mjs`), then the Rust must match it. The per-case
//! unit tests in `dual.rs` document the intent; THIS test proves the provenance —
//! every expected list state here came out of the actual JS interleaving rule.
//!
//! Native-only: the fixture is loaded from disk via `serde_json` (a native
//! dev-dependency); the production crate and the wasm build carry no such dep.
#![cfg(not(target_arch = "wasm32"))]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests use unwrap/expect as the assertion mechanism (PRD lint config)"
)]

use serde::Deserialize;
use silent_inference::dual::{DualCoordinator, TranscriptItem};
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct Fixture {
    cases: Vec<Case>,
}

#[derive(Debug, Deserialize)]
struct Case {
    name: String,
    events: Vec<Event>,
    steps: Vec<Step>,
    #[serde(rename = "final")]
    final_items: Vec<Item>,
}

#[derive(Debug, Deserialize, Clone)]
struct Event {
    kind: String,
    text: String,
}

#[derive(Debug, Deserialize)]
struct Step {
    items: Vec<Item>,
}

#[derive(Debug, Deserialize, Clone, PartialEq, Eq)]
struct Item {
    text: String,
    draft: bool,
}

impl From<&Item> for TranscriptItem {
    fn from(i: &Item) -> Self {
        TranscriptItem {
            text: i.text.clone(),
            draft: i.draft,
        }
    }
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("goldens")
        .join("dual")
        .join("interleavings.json")
}

#[test]
fn dual_interleavings_match_the_js_reference() {
    let raw = std::fs::read_to_string(fixture_path()).expect("read dual fixture");
    let fixture: Fixture = serde_json::from_str(&raw).expect("parse dual fixture");
    assert!(!fixture.cases.is_empty(), "fixture has cases");

    for case in &fixture.cases {
        assert_eq!(
            case.events.len(),
            case.steps.len(),
            "case `{}`: one snapshot per event",
            case.name
        );

        let mut coord = DualCoordinator::new();

        // Replay each event; after EACH, the authoritative list must equal the JS
        // snapshot — divergence is caught at the exact event that diverged.
        for (i, (event, step)) in case.events.iter().zip(case.steps.iter()).enumerate() {
            match event.kind.as_str() {
                "moonshine" => {
                    coord.on_moonshine_final(&event.text);
                }
                "sensevoice" => {
                    coord.on_sensevoice_final(&event.text);
                }
                other => panic!("case `{}`: unknown event kind `{other}`", case.name),
            }

            let expected: Vec<TranscriptItem> = step.items.iter().map(Into::into).collect();
            assert_eq!(
                coord.items(),
                expected.as_slice(),
                "case `{}`: list mismatch after event #{i} ({} {:?})",
                case.name,
                event.kind,
                event.text
            );
        }

        // And the final state, redundantly (catches a fixture/step desync).
        let expected_final: Vec<TranscriptItem> = case.final_items.iter().map(Into::into).collect();
        assert_eq!(
            coord.items(),
            expected_final.as_slice(),
            "case `{}`: final list mismatch",
            case.name
        );
    }
}
