// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataCapability } from "./DataCapability";
import type { NetworkGrant } from "./NetworkGrant";
import type { UiCapability } from "./UiCapability";

/**
 * The `capabilities` object of a manifest.
 *
 * Every axis defaults to empty. An extension that declares nothing gets
 * nothing — network is denied, no data crosses the boundary, no UI surface is
 * available.
 */
export type Capabilities = { 
/**
 * Requested meeting-data surfaces. Unknown tokens fail to decode.
 */
data: Array<DataCapability>, 
/**
 * Requested UI surfaces.
 */
ui: Array<UiCapability>, 
/**
 * Requested network origins. Empty = network denied (the default).
 */
network: Array<NetworkGrant>, };
