// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A meeting-data capability: a single readable data surface.
 *
 * `#[non_exhaustive]` so new *safe* data surfaces can be added without a
 * breaking change. Crucially, the enum contains **no** variant for raw audio,
 * embeddings, mel tensors, or model activations — those are not part of the
 * extension API surface at any version (PRD R7 acceptance: "an extension
 * requesting raw audio is rejected at manifest validation"; here it is
 * rejected one step earlier — it cannot even be represented).
 */
export type DataCapability = "transcript.text" | "transcript.segments" | "notes.decisions" | "notes.actions" | "notes.keypoints" | "notes.questions" | "speaker.labels" | "meeting.metadata";
