// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionName } from "./ExtensionName";

/**
 * The shared envelope around every message in either direction.
 *
 * `T` is the direction-specific body ([`HostMessage`] or [`ExtensionMessage`]).
 * The envelope binds a message to a protocol version and to the extension it
 * concerns, so the receiver can reject a version mismatch and route by id
 * before inspecting the body.
 */
export type Envelope<T> = { 
/**
 * Protocol version the sender speaks. Compared against [`PROTOCOL_VERSION`].
 */
protocolVersion: number, 
/**
 * The extension this message is to/from (the manifest `name`).
 */
extensionId: ExtensionName, 
/**
 * The direction-specific body.
 */
message: T, };
