// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteItem } from "./NoteItem";
import type { SpeakerLabel } from "./SpeakerLabel";
import type { TranscriptSegment } from "./TranscriptSegment";

/**
 * A pull-style snapshot of the meeting data an extension is entitled to.
 *
 * Each field is `None` unless the extension both requested it and is granted
 * the matching [`DataCapability`]. There is, by construction, no audio /
 * embedding / tensor field to populate.
 */
export type ExportSnapshot = { 
/**
 * Transcript segments, present only if a transcript capability is granted.
 */
transcript: Array<TranscriptSegment> | null, 
/**
 * Notes, present only if at least one `notes.*` capability is granted.
 */
notes: Array<NoteItem> | null, 
/**
 * Speaker rename map, present only if `speaker.labels` is granted.
 */
speakers: Array<SpeakerLabel> | null, };
