// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A validated extension name (the manifest `name`).
 *
 * The wire form is a bare string. Construction goes through [`ExtensionName::parse`]
 * (or `serde`, which routes through it), so an in-memory [`ExtensionName`] is
 * always a legal id: 1..=64 chars, ASCII, lowercase letters / digits / `-` /
 * `_` / `.`, starting with a letter. This keeps a name safe to use as an
 * IndexedDB key, a CSP nonce label, and a postMessage `extensionId` without
 * escaping (`docs/EXTENSIONS.md` §1, §4 envelope).
 */
export type ExtensionName = string;
