// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataCapability } from "./DataCapability";

/**
 * Extension -> host messages (requests the host validates against grants).
 *
 * `#[non_exhaustive]`; tagged by `type` to match `docs/EXTENSIONS.md` §5.
 */
export type ExtensionMessage = { "type": "render.panel", "payload": { 
/**
 * HTML to render inside the sandboxed panel iframe.
 */
html: string, } } | { "type": "render.notification", "payload": { 
/**
 * Toast text. Plain text; no HTML.
 */
text: string, } } | { "type": "export.request", "payload": { 
/**
 * Data surfaces the extension would like. Anything outside its grants
 * is omitted from the response without error.
 */
include: Array<DataCapability>, } };
