// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataCapability } from "./DataCapability";
import type { ExtensionName } from "./ExtensionName";
import type { NetworkGrant } from "./NetworkGrant";
import type { UiCapability } from "./UiCapability";

/**
 * The set of capabilities a user has granted one extension.
 *
 * Stored per extension (keyed by [`ExtensionName`]). The sets are sorted
 * (`BTreeSet`) so the serialized form is canonical and byte-stable for
 * persistence and diffing. A [`GrantSet`] built with [`GrantSet::new`] grants
 * nothing — the deny-by-default posture is the empty-set state. There is
 * deliberately no `Default` impl: a grant set is always bound to a specific
 * extension, never a nameless one.
 */
export type GrantSet = { 
/**
 * The extension these grants apply to.
 */
extension: ExtensionName, 
/**
 * Granted data surfaces.
 */
data: Array<DataCapability>, 
/**
 * Granted UI surfaces.
 */
ui: Array<UiCapability>, 
/**
 * Granted network origins. These — and only these — are the per-extension
 * `connect-src` additions.
 */
network: Array<NetworkGrant>, };
