// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportSnapshot } from "./ExportSnapshot";
import type { NoteItem } from "./NoteItem";
import type { TranscriptSegment } from "./TranscriptSegment";

/**
 * Host -> extension messages (push + export reply).
 *
 * `#[non_exhaustive]` so adding a message type is a minor-version change.
 * Tagged by `type` to match the `docs/EXTENSIONS.md` §4 envelope on the wire.
 */
export type HostMessage = { "type": "transcript.update", "payload": TranscriptSegment } | { "type": "notes.update", "payload": NoteItem } | { "type": "speaker.rename", "payload": { 
/**
 * Raw diarization label, for example `S1`.
 */
raw: string, 
/**
 * New display name, for example `Alice`.
 */
display: string, } } | { "type": "meeting.start", "payload": { 
/**
 * Stable meeting id.
 */
meetingId: string, 
/**
 * Meeting title.
 */
title: string, 
/**
 * Wall-clock start, epoch milliseconds.
 */
startMs: bigint, } } | { "type": "meeting.stop", "payload": { 
/**
 * Stable meeting id.
 */
meetingId: string, 
/**
 * Total duration, milliseconds.
 */
durationMs: bigint, } } | { "type": "export.response", "payload": ExportSnapshot };
