// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { ExtensionName } from "./ExtensionName";
import type { Version } from "./Version";

/**
 * A parsed `manifest.json`.
 *
 * `#[serde(deny_unknown_fields)]` is deliberate: an unrecognised top-level key
 * is a malformed manifest, not a forward-compatible one. The privacy story
 * requires that a manifest cannot smuggle meaning through fields the host does
 * not understand.
 */
export type Manifest = { 
/**
 * Machine-readable id; no spaces. Validated by [`ExtensionName`].
 */
name: ExtensionName, 
/**
 * Human-facing name shown in the extension manager UI. Optional in the
 * schema; the host falls back to `name`.
 */
display_name: string | null, 
/**
 * Semver version string. Validated by [`Version`].
 */
version: Version, 
/**
 * One-line description shown at install.
 */
description: string | null, 
/**
 * Relative path to the worker entrypoint, for example `index.js`. Loaded
 * in a Worker by the host (j2/j3); this crate only records and shape-checks
 * it.
 */
entrypoint: string, 
/**
 * The capabilities this extension declares it needs.
 */
capabilities: Capabilities, };
