// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a manifest is rejected.
 *
 * `#[non_exhaustive]`; callers must include a wildcard arm. Each variant is a
 * precise, self-contained message suitable for an install error or a log line.
 * Forbidden-capability and wildcard-origin requests do **not** appear here as
 * runtime variants — they are rejected one layer earlier, at decode, and
 * surface as [`ManifestError::Decode`] carrying serde's message (which names
 * the unknown token / bad origin).
 */
export type ManifestError = { "kind": "too_large", "detail": { 
/**
 * Actual size.
 */
len: number, 
/**
 * Allowed maximum.
 */
max: number, } } | { "kind": "decode", "detail": { 
/**
 * The serde error message (names the offending field / token).
 */
reason: string, } } | { "kind": "empty_entrypoint" } | { "kind": "absolute_entrypoint", "detail": { 
/**
 * The offending entrypoint.
 */
entrypoint: string, } } | { "kind": "entrypoint_traversal", "detail": { 
/**
 * The offending entrypoint.
 */
entrypoint: string, } } | { "kind": "duplicate_data_capability", "detail": { 
/**
 * The duplicated capability token.
 */
capability: string, } } | { "kind": "duplicate_ui_capability", "detail": { 
/**
 * The duplicated capability token.
 */
capability: string, } } | { "kind": "duplicate_network_grant", "detail": { 
/**
 * The duplicated origin.
 */
origin: string, } } | { "kind": "too_many_network_grants", "detail": { 
/**
 * Actual count.
 */
count: number, 
/**
 * Allowed maximum.
 */
max: number, } };
