// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an extension name is invalid.
 *
 * `#[non_exhaustive]`; callers must include a wildcard arm.
 */
export type NameError = { "kind": "empty" } | { "kind": "too_long", "detail": { 
/**
 * Actual length.
 */
len: number, 
/**
 * Allowed maximum.
 */
max: number, } } | { "kind": "bad_start", "detail": { 
/**
 * The offending first character.
 */
ch: string, } } | { "kind": "bad_char", "detail": { 
/**
 * The offending character.
 */
ch: string, } };
