// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a string is not a valid origin grant.
 *
 * `#[non_exhaustive]`; callers must include a wildcard arm. Each variant
 * carries the offending origin so the message is self-contained at the install
 * consent screen and in logs.
 */
export type NetworkGrantError = { "kind": "missing_scheme", "detail": { 
/**
 * The rejected grant string.
 */
origin: string, } } | { "kind": "insecure_scheme", "detail": { 
/**
 * The rejected grant string.
 */
origin: string, } } | { "kind": "unsupported_scheme", "detail": { 
/**
 * The rejected grant string.
 */
origin: string, 
/**
 * The offending scheme.
 */
scheme: string, } } | { "kind": "missing_host", "detail": { 
/**
 * The rejected grant string.
 */
origin: string, } } | { "kind": "wildcard", "detail": { 
/**
 * The rejected grant string.
 */
origin: string, } } | { "kind": "has_path", "detail": { 
/**
 * The rejected grant string.
 */
origin: string, 
/**
 * The offending suffix (path/query/fragment).
 */
trailing: string, } } | { "kind": "has_userinfo", "detail": { 
/**
 * The rejected grant string.
 */
origin: string, } } | { "kind": "bad_port", "detail": { 
/**
 * The rejected grant string.
 */
origin: string, 
/**
 * The offending port substring.
 */
port: string, } };
