// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An origin-scoped network grant.
 *
 * Network is denied by default. A grant is a single full origin
 * (`https://api.notion.com`) — never a wildcard, never a bare host, never a
 * path. The grant is shown to the user at install and is revocable
 * (`docs/EXTENSIONS.md` §1.3). The contained string is validated by
 * [`NetworkGrant::parse`]; the only way to obtain a [`NetworkGrant`] is through that
 * constructor (or `serde`, which routes through the same validation), so an
 * in-memory [`NetworkGrant`] is always a well-formed, wildcard-free origin.
 */
export type NetworkGrant = string;
