// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteCategory } from "./NoteCategory";

/**
 * A single extracted note delivered to an extension. Text only.
 */
export type NoteItem = { 
/**
 * Stable note id, for example `note-017`.
 */
noteId: string, 
/**
 * Which section this note belongs to.
 */
category: NoteCategory, 
/**
 * The note text.
 */
text: string, 
/**
 * Attributed speaker, if known.
 */
speaker: string | null, 
/**
 * When the note was surfaced, milliseconds from session start.
 */
timestampMs: bigint, };
