// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The category of an extracted note.
 */
export type NoteCategory = "decision" | "action" | "keypoint" | "question";
