// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of the `S1 -> "Alice"` rename map.
 */
export type SpeakerLabel = { 
/**
 * Raw diarization label, for example `S1`.
 */
raw: string, 
/**
 * Display name the user assigned.
 */
display: string, };
