// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single transcript segment delivered to an extension.
 *
 * Plain text and timing only. No audio, no embedding, no confidence vector —
 * just the committed words and where they sit in the meeting timeline.
 */
export type TranscriptSegment = { 
/**
 * Stable segment id, for example `seg-042`.
 */
segmentId: string, 
/**
 * The committed transcript text for this segment.
 */
text: string, 
/**
 * Resolved display speaker (from the rename map), if known.
 */
speaker: string | null, 
/**
 * Raw diarization label (`S1`), if available.
 */
speaker_raw: string | null, 
/**
 * Start offset, milliseconds from session start.
 */
startMs: bigint, 
/**
 * End offset, milliseconds from session start.
 */
endMs: bigint, };
