// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A UI-surface capability.
 *
 * `#[non_exhaustive]` for future safe surfaces. Extensions never get free-form
 * DOM injection — a panel is a host-controlled sandboxed iframe slot
 * (`docs/EXTENSIONS.md` §1.2).
 */
export type UiCapability = "panel" | "notification";
