// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A validated semantic version (`MAJOR.MINOR.PATCH`).
 *
 * A deliberately small, dependency-free semver: three non-negative integers.
 * Pre-release / build metadata (`-rc.1`, `+build`) is *rejected* rather than
 * parsed — extension versions are kept simple, and a strict parser keeps the
 * stored form canonical. The wire form is the bare `"1.2.3"` string.
 */
export type Version = string;
