// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a version string is invalid.
 *
 * `#[non_exhaustive]`; callers must include a wildcard arm.
 */
export type VersionError = { "kind": "malformed", "detail": { 
/**
 * The rejected version string.
 */
version: string, } } | { "kind": "bad_field", "detail": { 
/**
 * The rejected version string.
 */
version: string, 
/**
 * The offending field.
 */
field: string, } } | { "kind": "leading_zero", "detail": { 
/**
 * The rejected version string.
 */
version: string, 
/**
 * The offending field.
 */
field: string, } };
