//! Golden tests for the crash-diagnostics ring buffer port (Appendix A row 34).
//!
//! These replay the fixture generated by the reference JS in
//! `goldens/gen/diag_ref.mjs` — a DOM/clock-free reimplementation of the EXACT
//! `index.html` `Diag` sampler (the `notetakerDiag` row shape, the
//! `+(x).toFixed(1)` / `JSON.stringify` normalization, the bounded ring, and the
//! prior-trail surfacing) — and assert the Rust port reproduces every byte.
//!
//! The contract this pins: a Rust-written `notetakerDiag` value and a
//! JS-written one are INTERCHANGEABLE. So a trail captured by the old JS survives
//! into the Rust core (prior-trail recovery across the cutover), and a Rust trail
//! is still parseable by the legacy `window.dumpDiag()`. That is only true if the
//! serialized bytes are identical, which is what the byte-equality assertions
//! below prove against the actual JS `JSON.stringify` output.
//!
//! Regenerate with: `node crates/silent-core/goldens/gen/diag_ref.mjs`.
//!
//! Native-only: the fixture is loaded via `serde_json`, a native dev-dependency;
//! the production crate (and the wasm build) carry no JSON-codec dependency — the
//! ring policy in `silent-core::diag` operates on typed `DiagRow`s, and the
//! `JSON.stringify`/`localStorage` encoding is the boundary's job (`silent-web`).
//! This test stands in for that boundary to prove the bytes match.
#![cfg(not(target_arch = "wasm32"))]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests use unwrap/expect as the assertion mechanism (PRD lint config)"
)]

use serde::Deserialize;
use silent_core::diag::{HeapBytes, OneDecimal, prior_trail, push_bounded};
use silent_core::{DIAG_MAX_ROWS, Diag, DiagRow, SampleInput};
use std::path::PathBuf;

// ---------------------------------------------------------------------------
// Fixture shape (mirrors diag_ref.mjs output).
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct Fixture {
    #[serde(rename = "diagKey")]
    diag_key: String,
    #[serde(rename = "diagMaxRows")]
    diag_max_rows: usize,
    #[serde(rename = "oneDecimal")]
    one_decimal: Vec<OneDecimalCase>,
    #[serde(rename = "heapBytes")]
    heap_bytes: Vec<HeapByteCase>,
    rows: Vec<RowCase>,
    ring: RingFixture,
    trail: TrailFixture,
}

#[derive(Debug, Deserialize)]
struct OneDecimalCase {
    raw: f64,
    #[serde(rename = "outJson")]
    out_json: String,
}

#[derive(Debug, Deserialize)]
struct HeapByteCase {
    bytes: f64,
    #[serde(rename = "outJson")]
    out_json: String,
}

#[derive(Debug, Deserialize)]
struct RowCase {
    input: RowInput,
    #[serde(rename = "rowJson")]
    row_json: String,
    #[serde(rename = "arrayJson")]
    array_json: String,
}

/// The host-supplied per-tick inputs the JS fixture recorded, plus the loop
/// counters as they stood at that tick. We replay these to rebuild the row.
#[derive(Debug, Deserialize)]
struct RowInput {
    iso: String,
    #[serde(rename = "elapsedSec")]
    elapsed_sec: u64,
    mem: Option<MemInput>,
    items: u64,
    words: u64,
    #[serde(rename = "loopIter")]
    loop_iter: u64,
    recycle: u64,
    #[serde(rename = "ctxLen")]
    ctx_len: u64,
    #[serde(rename = "genStepsTotal")]
    gen_steps_total: u64,
    #[serde(rename = "inputTokens")]
    input_tokens: u64,
    #[serde(rename = "lastStepMs")]
    last_step_ms: f64,
    #[serde(rename = "deviceLost")]
    device_lost: String,
    #[serde(rename = "writeAbs")]
    write_abs: Option<u64>,
}

#[derive(Debug, Deserialize)]
struct MemInput {
    used: f64,
    total: f64,
    limit: f64,
}

#[derive(Debug, Deserialize)]
struct RingFixture {
    #[serde(rename = "smallMax")]
    small_max: usize,
    #[serde(rename = "smallCount")]
    small_count: usize,
    #[serde(rename = "smallRingJson")]
    small_ring_json: String,
    #[serde(rename = "smallFirstElapsed")]
    small_first_elapsed: u64,
    #[serde(rename = "smallLastElapsed")]
    small_last_elapsed: u64,
    #[serde(rename = "bigMax")]
    big_max: usize,
    #[serde(rename = "bigCount")]
    big_count: usize,
    #[serde(rename = "bigLen")]
    big_len: usize,
    #[serde(rename = "bigFirstElapsed")]
    big_first_elapsed: u64,
    #[serde(rename = "bigLastElapsed")]
    big_last_elapsed: u64,
}

#[derive(Debug, Deserialize)]
struct TrailFixture {
    #[serde(rename = "rowCount")]
    row_count: usize,
    headline: String,
    #[serde(rename = "summaryLines")]
    summary_lines: Vec<String>,
    #[serde(rename = "allSummaryLines")]
    all_summary_lines: Vec<String>,
}

// ---------------------------------------------------------------------------
// Helpers: build a DiagRow from the recorded host inputs + counter snapshot.
// ---------------------------------------------------------------------------

/// The JS row carries the counter values inline. The Rust `Diag::build_row`
/// reads them off the live sampler state, so to replay a fixture row we drive a
/// `Diag` to exactly those counter values, then build with the host inputs. The
/// loop counters (`loop_iter`, `recycle`, `ctx_len`, `gen_steps_total`,
/// `input_tokens`) and `last_step_ms` come from the recorded input; the rest is
/// the per-tick `SampleInput`.
fn row_from_case(c: &RowInput) -> DiagRow {
    // SampleInput = the host-supplied values.
    let input = SampleInput {
        iso: c.iso.clone(),
        elapsed_sec: c.elapsed_sec,
        heap: c.mem.as_ref().map(|m| HeapBytes {
            used: m.used,
            total: m.total,
            limit: m.limit,
        }),
        items: c.items,
        words: c.words,
        write_abs: c.write_abs,
    };
    // Build the row directly from the recorded counter snapshot + input, so the
    // golden is a pure function of the fixture (we assert the hooks produce these
    // same counters in the diag.rs unit tests).
    DiagRow {
        iso: input.iso.clone(),
        elapsed_sec: input.elapsed_sec,
        heap_used_mb: input
            .heap
            .map(|h| OneDecimal::from_f64(h.used / 1_048_576.0)),
        heap_total_mb: input
            .heap
            .map(|h| OneDecimal::from_f64(h.total / 1_048_576.0)),
        heap_limit_mb: input
            .heap
            .map(|h| OneDecimal::from_f64(h.limit / 1_048_576.0)),
        items: input.items,
        words: input.words,
        loop_iter: c.loop_iter,
        recycle: c.recycle,
        ctx_len: c.ctx_len,
        gen_steps_total: c.gen_steps_total,
        input_tokens: c.input_tokens,
        last_step_ms: OneDecimal::from_f64(c.last_step_ms),
        device_lost: c.device_lost.clone(),
        write_abs: input.write_abs,
    }
}

fn load_fixture() -> Fixture {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("goldens/diag/diag.json");
    let raw = std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()));
    serde_json::from_str(&raw).expect("parse diag.json fixture")
}

// ---------------------------------------------------------------------------
// Tests.
// ---------------------------------------------------------------------------

#[test]
fn key_and_max_match_js() {
    let f = load_fixture();
    assert_eq!(f.diag_key, silent_core::DIAG_KEY, "localStorage key");
    assert_eq!(f.diag_max_rows, DIAG_MAX_ROWS, "ring max rows");
}

/// Every `+(x).toFixed(1)` value serializes to the exact JS `JSON.stringify`
/// token (incl. the IEEE-754 tie cases and whole-number elision).
#[test]
fn one_decimal_serialization_byte_identical() {
    let f = load_fixture();
    for case in &f.one_decimal {
        let v = OneDecimal::from_f64(case.raw);
        let got = serde_json::to_string(&v).unwrap();
        assert_eq!(
            got, case.out_json,
            "oneDecimal raw={} : Rust {got} != JS {}",
            case.raw, case.out_json
        );
    }
}

/// `bytes / 1048576` then `toFixed(1)` serializes byte-identically to JS for
/// real `performance.memory` magnitudes.
#[test]
fn heap_bytes_to_mb_byte_identical() {
    let f = load_fixture();
    for case in &f.heap_bytes {
        let v = OneDecimal::from_f64(case.bytes / 1_048_576.0);
        let got = serde_json::to_string(&v).unwrap();
        assert_eq!(
            got, case.out_json,
            "heapBytes bytes={} : Rust {got} != JS {}",
            case.bytes, case.out_json
        );
    }
}

/// Each full row serializes to the exact JS `JSON.stringify(row)` bytes (shape +
/// KEY ORDER + null heap + device-lost + one-decimal fields).
#[test]
fn row_json_byte_identical() {
    let f = load_fixture();
    for (i, case) in f.rows.iter().enumerate() {
        let row = row_from_case(&case.input);
        let got = serde_json::to_string(&row).unwrap();
        assert_eq!(
            got, case.row_json,
            "row[{i}] bytes differ:\n  Rust: {got}\n  JS:   {}",
            case.row_json
        );
    }
}

/// The cumulative ring (`JSON.stringify(rows)` after each push) is byte-identical
/// — this is the EXACT `localStorage` value the JS wrote each tick.
#[test]
fn ring_array_json_byte_identical() {
    let f = load_fixture();
    let mut rows: Vec<DiagRow> = Vec::new();
    for (i, case) in f.rows.iter().enumerate() {
        push_bounded(&mut rows, row_from_case(&case.input));
        let got = serde_json::to_string(&rows).unwrap();
        assert_eq!(
            got, case.array_json,
            "array after row[{i}] differs:\n  Rust: {got}\n  JS:   {}",
            case.array_json
        );
    }
}

/// Bounded-ring eviction (push then front-shift to max) reproduces the JS
/// `rows.shift()` behavior byte-for-byte on a small ring, and the invariants on
/// the real 200-row ring.
#[test]
fn ring_eviction_byte_identical() {
    let f = load_fixture();
    let r = &f.ring;

    // Small ring: full byte comparison.
    let mut small: Vec<DiagRow> = Vec::new();
    for i in 0..r.small_count {
        push_bounded_max(&mut small, ring_row(i), r.small_max);
    }
    assert_eq!(small.len(), r.small_max);
    assert_eq!(small[0].elapsed_sec, r.small_first_elapsed);
    assert_eq!(small[small.len() - 1].elapsed_sec, r.small_last_elapsed);
    let got = serde_json::to_string(&small).unwrap();
    assert_eq!(got, r.small_ring_json, "small ring bytes differ");

    // Big ring (max == DIAG_MAX_ROWS): invariants only (no 200-row blob).
    assert_eq!(r.big_max, DIAG_MAX_ROWS);
    let mut big: Vec<DiagRow> = Vec::new();
    for i in 0..r.big_count {
        push_bounded(&mut big, ring_row(i)); // uses the real DIAG_MAX_ROWS
    }
    assert_eq!(big.len(), r.big_len);
    assert_eq!(big[0].elapsed_sec, r.big_first_elapsed);
    assert_eq!(big[big.len() - 1].elapsed_sec, r.big_last_elapsed);
}

/// Prior-trail surfacing strings (headline + per-row summary lines, incl. the
/// `heap=nullMB` and ` DEVICE-LOST:` cases) match the JS byte-for-byte.
#[test]
fn prior_trail_surfacing_byte_identical() {
    let f = load_fixture();
    // Rebuild the trail from the 5 row cases (same rows the JS trail used).
    let trail: Vec<DiagRow> = f.rows.iter().map(|c| row_from_case(&c.input)).collect();
    assert_eq!(trail.len(), f.trail.row_count);

    assert_eq!(prior_trail::headline(&trail), f.trail.headline, "headline");

    // last-5 window.
    let got_last = prior_trail::last_summary_lines(&trail, 5);
    assert_eq!(got_last, f.trail.summary_lines, "last-5 summary lines");

    // every row (covers null-heap + device-lost rows beyond the last-5 window).
    let got_all: Vec<String> = trail.iter().map(prior_trail::summary_line).collect();
    assert_eq!(got_all, f.trail.all_summary_lines, "all summary lines");
}

/// Drive the real `Diag` sampler hooks through a `MemSink` and confirm the
/// resulting stored bytes match the JS golden — proving the END-TO-END path
/// (hooks -> sample -> sink) writes the byte-identical `notetakerDiag` value, not
/// just that a hand-built row serializes the same.
///
/// We use the first two fixture rows (the device-lost row's counter snapshot is
/// engine-specific — `ctx_len` is not a pure function of the put count once the
/// cap recycles — so it is covered by the byte goldens above; the hooks'
/// arithmetic itself is pinned in the diag.rs `hooks_drive_counters_like_js`
/// unit test). Rows 0 and 1 are reachable by a deterministic hook sequence.
#[test]
fn sampler_end_to_end_writes_golden_bytes() {
    let f = load_fixture();
    let mut sink = silent_core::MemSink::new();
    let mut d = Diag::new();

    // Row 0: baseline, no hooks fired yet.
    let c0 = &f.rows[0].input;
    let r0 = d.sample(&sample_input(c0), &mut sink);
    assert_eq!(serde_json::to_string(&r0).unwrap(), f.rows[0].row_json);
    assert_eq!(
        serde_json::to_string(sink.get(silent_core::DIAG_KEY)).unwrap(),
        f.rows[0].array_json,
        "stored ring after row 0"
    );

    // Row 1: one generate context (loop_iter=1, input_tokens=8), 37 puts summing
    // to ctx_len=37 and gen_steps_total=37, last gap = 41.27 -> 41.3.
    let c1 = &f.rows[1].input;
    d.on_loop_iter(c1.input_tokens);
    // 37 single-token puts; the LAST gap must be 41.27. Prime, then 36 dummy
    // gaps, then a final 41.27 gap so last_step_ms == 41.3.
    d.on_put(0.0, 1);
    for k in 1..(c1.gen_steps_total - 1) {
        d.on_put(f64::from(u32::try_from(k).unwrap()), 1);
    }
    // final put: gap of 41.27 from the previous integer ms.
    let prev = f64::from(u32::try_from(c1.gen_steps_total - 2).unwrap());
    d.on_put(prev + c1.last_step_ms, 1);

    let r1 = d.sample(&sample_input(c1), &mut sink);
    assert_eq!(
        serde_json::to_string(&r1).unwrap(),
        f.rows[1].row_json,
        "row 1 from live hooks"
    );
    assert_eq!(
        serde_json::to_string(sink.get(silent_core::DIAG_KEY)).unwrap(),
        f.rows[1].array_json,
        "stored ring after row 1"
    );
}

/// Build a `SampleInput` from a recorded fixture row's host inputs.
fn sample_input(c: &RowInput) -> SampleInput {
    SampleInput {
        iso: c.iso.clone(),
        elapsed_sec: c.elapsed_sec,
        heap: c.mem.as_ref().map(|m| HeapBytes {
            used: m.used,
            total: m.total,
            limit: m.limit,
        }),
        items: c.items,
        words: c.words,
        write_abs: c.write_abs,
    }
}

// ---------------------------------------------------------------------------
// Local ring helper with an explicit max (the small-ring fixture uses max=4,
// not the DIAG_MAX_ROWS push_bounded uses). Mirrors the JS `push; while > max
// shift`.
// ---------------------------------------------------------------------------
fn push_bounded_max(rows: &mut Vec<DiagRow>, row: DiagRow, max: usize) {
    rows.push(row);
    while rows.len() > max {
        rows.remove(0);
    }
}

/// The ring fixture's per-row inputs (matches `ringRun` in `diag_ref.mjs`):
/// `used = (i+1) MiB`, `items=i`, `words=i*7`, `loopIter=i`, `ctxLen=i%16`,
/// `genStepsTotal=i*4`, `inputTokens=8`, `writeAbs=i*48000`.
fn ring_row(i: usize) -> DiagRow {
    let iu = i as u64;
    // `used = (i+1) * 1 MiB`, so `used / 1048576 == i+1` exactly; the fixture
    // pushes at most 250 rows, well within an exact u32 -> f64.
    let used_mb = f64::from(u32::try_from(i + 1).unwrap());
    DiagRow {
        iso: "2026-06-04T17:00:00.000Z".into(),
        elapsed_sec: iu,
        heap_used_mb: Some(OneDecimal::from_f64(used_mb)),
        heap_total_mb: Some(OneDecimal::from_f64(134_217_728.0 / 1_048_576.0)),
        heap_limit_mb: Some(OneDecimal::from_f64(4_294_967_296.0 / 1_048_576.0)),
        items: iu,
        words: iu * 7,
        loop_iter: iu,
        recycle: 0,
        ctx_len: iu % 16,
        gen_steps_total: iu * 4,
        input_tokens: 8,
        last_step_ms: OneDecimal::from_f64(0.0),
        device_lost: String::new(),
        write_abs: Some(iu * 48_000),
    }
}
