//! Golden tests for the exporters.
//!
//! These replay fixtures generated by the reference JS in
//! `goldens/gen/export_ref.mjs` (a DOM-/Intl-free reimplementation of the EXACT
//! `index.html` export/copy formatting) and assert the Rust port produces
//! byte-identical Markdown / transcript text / executive lines.
//!
//! Regenerate goldens: `node crates/silent-core/goldens/gen/export_ref.mjs`.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests use unwrap/expect as the assertion mechanism (PRD lint config)"
)]

use serde::Deserialize;
use silent_core::export::{
    AiNoteGroup, NoteCategory, NoteRecord, TranscriptLine, executive_line, history_replay_markdown,
    notes_to_markdown, summary_markdown_with_ai, transcript_text,
};
use std::path::PathBuf;

fn goldens_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("goldens/export")
}

fn load<T: for<'de> Deserialize<'de>>(name: &str) -> T {
    let path = goldens_dir().join(name);
    let bytes =
        std::fs::read(&path).unwrap_or_else(|e| panic!("read golden {}: {e}", path.display()));
    serde_json::from_slice(&bytes)
        .unwrap_or_else(|e| panic!("parse golden {}: {e}", path.display()))
}

// The JS fixtures use camelCase note records with string categories; the silent
// -core `NoteRecord` uses snake_case category strings (which match the JS values
// `decisions`/`actions`/`keypoints`/`questions`) so serde deserializes the
// fixture note arrays directly into `Vec<NoteRecord>`.

#[derive(Deserialize)]
struct NotesFixture {
    input: NotesInput,
    expected: String,
}
#[derive(Deserialize)]
struct NotesInput {
    title: String,
    date: String,
    duration: String,
    #[serde(rename = "withTime")]
    with_time: bool,
    notes: Vec<NoteRecord>,
}

fn check_notes_to_markdown(name: &str) {
    let f: NotesFixture = load(name);
    let got = notes_to_markdown(
        &f.input.title,
        &f.input.date,
        &f.input.duration,
        &f.input.notes,
        f.input.with_time,
    );
    assert_eq!(got, f.expected, "{name}: notes_to_markdown mismatch");
}

#[test]
fn notes_with_time() {
    check_notes_to_markdown("notes_with_time.json");
}
#[test]
fn notes_no_time() {
    check_notes_to_markdown("notes_no_time.json");
}
#[test]
fn notes_empty_title() {
    check_notes_to_markdown("notes_empty_title.json");
}

#[derive(Deserialize)]
struct HistoryFixture {
    input: HistoryInput,
    expected: String,
}
#[derive(Deserialize)]
struct HistoryInput {
    title: String,
    date: String,
    duration: String,
    notes: Vec<NoteRecord>,
}

#[test]
fn history_replay() {
    let f: HistoryFixture = load("history_replay.json");
    let got = history_replay_markdown(
        &f.input.title,
        &f.input.date,
        &f.input.duration,
        &f.input.notes,
    );
    assert_eq!(got, f.expected, "history_replay markdown mismatch");
}

#[derive(Deserialize)]
struct ExecFixture {
    input: ExecInput,
    expected: String,
}
#[derive(Deserialize)]
struct ExecInput {
    duration: String,
    notes: Vec<NoteRecord>,
    #[serde(rename = "totalWords")]
    total_words: u64,
}

fn check_exec(name: &str) {
    let f: ExecFixture = load(name);
    let got = executive_line(&f.input.duration, &f.input.notes, f.input.total_words);
    assert_eq!(got, f.expected, "{name}: executive_line mismatch");
}

#[test]
fn executive_line_full() {
    check_exec("executive_line_full.json");
}
#[test]
fn executive_line_singular() {
    check_exec("executive_line_singular.json");
}
#[test]
fn executive_line_empty() {
    check_exec("executive_line_empty.json");
}

#[derive(Deserialize)]
struct TranscriptFixture {
    input: TranscriptInput,
    expected: String,
}
#[derive(Deserialize)]
struct TranscriptInput {
    #[serde(rename = "withTime")]
    with_time: bool,
    lines: Vec<TranscriptLine>,
}

fn check_transcript(name: &str) {
    let f: TranscriptFixture = load(name);
    let got = transcript_text(&f.input.lines, f.input.with_time);
    assert_eq!(got, f.expected, "{name}: transcript_text mismatch");
}

#[test]
fn transcript_with_time() {
    check_transcript("transcript_with_time.json");
}
#[test]
fn transcript_no_time() {
    check_transcript("transcript_no_time.json");
}

#[derive(Deserialize)]
struct SummaryFixture {
    input: SummaryInput,
    expected: String,
}
#[derive(Deserialize)]
struct SummaryInput {
    title: String,
    date: String,
    duration: String,
    #[serde(rename = "withTime")]
    with_time: bool,
    notes: Vec<NoteRecord>,
    #[serde(rename = "aiGroups")]
    ai_groups: Vec<AiNoteGroup>,
}

#[test]
fn summary_with_ai_notes() {
    let f: SummaryFixture = load("summary_with_ai_notes.json");
    // The JS builds the base notes markdown first, then appends AI groups; the
    // Rust port composes the same two pure functions.
    let base = notes_to_markdown(
        &f.input.title,
        &f.input.date,
        &f.input.duration,
        &f.input.notes,
        f.input.with_time,
    );
    let got = summary_markdown_with_ai(&base, &f.input.ai_groups);
    assert_eq!(got, f.expected, "summary_with_ai_notes mismatch");
}

// Sanity: the fixture category strings round-trip to the enum we expect.
#[test]
fn fixture_categories_deserialize() {
    let f: NotesFixture = load("notes_with_time.json");
    assert!(
        f.input
            .notes
            .iter()
            .any(|n| n.category == NoteCategory::Questions),
        "fixture should contain a questions note"
    );
}
