//! Golden tests for the session formatter ports.
//!
//! These replay the fixture generated by the reference JS in
//! `goldens/gen/session_ref.mjs` — a DOM-free reimplementation of the EXACT
//! index.html `formatMs` / `formatStamp` (ago + elapsed branches) /
//! `value.trim() || 'Untitled Meeting'` + `maxlength="120"` logic — and assert
//! the Rust ports (`format_ms`, `format_ago`, `resolve_title`, `clamp_title`)
//! reproduce every output byte-for-byte.
//!
//! This is what makes the ports verifiable rather than hand-asserted: the JS
//! behavior is captured FIRST (committed JSON, regenerable with
//! `node goldens/gen/session_ref.mjs`), then the Rust must match it. The
//! per-case unit tests in `session.rs` document the intent; THIS test proves the
//! provenance — every expected string here came out of the actual JS.
//!
//! Native-only: the fixture is loaded from disk via `serde_json`, which is a
//! native dev-dependency; the production crate (and the wasm build) carry no
//! such dependency.
#![cfg(not(target_arch = "wasm32"))]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests use unwrap/expect as the assertion mechanism (PRD lint config)"
)]

use serde::Deserialize;
use silent_core::session::{
    DEFAULT_TITLE, MAX_TITLE_CHARS, clamp_title, format_ago, format_ms, resolve_title,
};
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct Fixture {
    #[serde(rename = "defaultTitle")]
    default_title: String,
    #[serde(rename = "maxTitleChars")]
    max_title_chars: usize,
    #[serde(rename = "formatMs")]
    format_ms: Vec<FormatMsCase>,
    #[serde(rename = "formatAgo")]
    format_ago: Vec<FormatAgoCase>,
    #[serde(rename = "formatStampElapsed")]
    format_stamp_elapsed: Vec<FormatStampElapsedCase>,
    #[serde(rename = "resolveTitle")]
    resolve_title: Vec<TitleCase>,
    #[serde(rename = "clampTitle")]
    clamp_title: Vec<TitleCase>,
}

#[derive(Debug, Deserialize)]
struct FormatMsCase {
    ms: u64,
    out: String,
}

#[derive(Debug, Deserialize)]
struct FormatAgoCase {
    // The JS records signed deltas (it clamps negatives to 0 via `Math.max`).
    // The Rust `format_ago` takes an unsigned delta — the host computes
    // `now.saturating_sub(ts)`, which is the saturating analogue of the JS clamp.
    // We map a negative JS delta to 0 here to model that host-side saturation.
    #[serde(rename = "deltaMs")]
    delta_ms: i64,
    out: String,
}

#[derive(Debug, Deserialize)]
struct FormatStampElapsedCase {
    #[serde(rename = "tsMs")]
    ts_ms: u64,
    start: u64,
    out: String,
}

#[derive(Debug, Deserialize)]
struct TitleCase {
    raw: String,
    out: String,
    #[serde(rename = "outChars")]
    out_chars: usize,
}

fn load_fixture() -> Fixture {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("goldens")
        .join("format")
        .join("session_formatters.json");
    let bytes = std::fs::read(&path)
        .unwrap_or_else(|e| panic!("read golden fixture {}: {e}", path.display()));
    serde_json::from_slice(&bytes)
        .unwrap_or_else(|e| panic!("parse golden fixture {}: {e}", path.display()))
}

#[test]
fn format_ms_matches_js_golden() {
    let fx = load_fixture();
    assert!(!fx.format_ms.is_empty(), "fixture has formatMs cases");
    for case in &fx.format_ms {
        assert_eq!(
            format_ms(case.ms),
            case.out,
            "format_ms({}) must equal the JS golden",
            case.ms
        );
    }
}

#[test]
fn format_ago_matches_js_golden() {
    let fx = load_fixture();
    assert!(!fx.format_ago.is_empty(), "fixture has formatAgo cases");
    for case in &fx.format_ago {
        // Model host-side `now.saturating_sub(ts)`: a negative JS delta (the
        // `Math.max(0, …)` clamp) becomes 0 for the unsigned Rust port.
        let delta = u64::try_from(case.delta_ms).unwrap_or(0);
        assert_eq!(
            format_ago(delta),
            case.out,
            "format_ago({delta}) (from JS deltaMs {}) must equal the JS golden",
            case.delta_ms
        );
    }
}

#[test]
fn format_stamp_elapsed_matches_js_golden() {
    // The 'elapsed' branch of formatStamp is `format_ms(ts - start)`; replay the
    // JS-recorded (ts, start) pairs through the same Rust composition.
    let fx = load_fixture();
    assert!(
        !fx.format_stamp_elapsed.is_empty(),
        "fixture has formatStampElapsed cases"
    );
    for case in &fx.format_stamp_elapsed {
        let rust = format_ms(case.ts_ms.saturating_sub(case.start));
        assert_eq!(
            rust, case.out,
            "format_ms({} - {}) must equal the JS elapsed golden",
            case.ts_ms, case.start
        );
    }
}

#[test]
fn resolve_title_matches_js_golden() {
    let fx = load_fixture();
    // The shared constants must agree with the JS source too.
    assert_eq!(DEFAULT_TITLE, fx.default_title, "DEFAULT_TITLE matches JS");
    assert_eq!(
        MAX_TITLE_CHARS, fx.max_title_chars,
        "MAX_TITLE_CHARS matches JS"
    );
    assert!(
        !fx.resolve_title.is_empty(),
        "fixture has resolveTitle cases"
    );
    for case in &fx.resolve_title {
        let rust = resolve_title(&case.raw);
        assert_eq!(
            rust, case.out,
            "resolve_title({:?}) must equal the JS golden",
            case.raw
        );
        assert_eq!(
            rust.chars().count(),
            case.out_chars,
            "resolve_title({:?}) char count must equal the JS golden",
            case.raw
        );
    }
}

#[test]
fn clamp_title_matches_js_golden() {
    let fx = load_fixture();
    assert!(!fx.clamp_title.is_empty(), "fixture has clampTitle cases");
    for case in &fx.clamp_title {
        let rust = clamp_title(&case.raw);
        assert_eq!(
            rust, case.out,
            "clamp_title({:?}) must equal the JS golden",
            case.raw
        );
        assert_eq!(
            rust.chars().count(),
            case.out_chars,
            "clamp_title({:?}) char count must equal the JS golden",
            case.raw
        );
    }
}
