//! Table-driven golden tests for the timestamp formatters.
//!
//! These replay fixtures generated by the reference JS in
//! `goldens/gen/timestamp_ref.mjs` (a DOM-/Intl-free reimplementation of the
//! EXACT `index.html` `formatMs`/`formatStamp`/`formatDuration`) and assert the
//! Rust port reproduces every string byte-for-byte — including JS arithmetic
//! quirks (`Math.floor`, sign-preserving `%`, `padStart`) on negative deltas and
//! the en-US 12-hour clock strings produced by `Intl`.
//!
//! Regenerate goldens: `node crates/silent-core/goldens/gen/timestamp_ref.mjs`.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests use unwrap/expect as the assertion mechanism (PRD lint config)"
)]

use serde::Deserialize;
use silent_core::timestamp::{format_ago, format_clock, format_duration, format_elapsed};
use std::path::PathBuf;

fn goldens_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("goldens/timestamp")
}

fn load<T: for<'de> Deserialize<'de>>(name: &str) -> T {
    let path = goldens_dir().join(name);
    let bytes =
        std::fs::read(&path).unwrap_or_else(|e| panic!("read golden {}: {e}", path.display()));
    serde_json::from_slice(&bytes)
        .unwrap_or_else(|e| panic!("parse golden {}: {e}", path.display()))
}

#[derive(Deserialize)]
struct ElapsedFile {
    cases: Vec<ElapsedCase>,
}
#[derive(Deserialize)]
struct ElapsedCase {
    #[serde(rename = "tsMs")]
    ts_ms: i64,
    #[serde(rename = "startTime")]
    start_time: i64,
    expected: String,
}

#[test]
fn elapsed_matches_js() {
    let f: ElapsedFile = load("elapsed.json");
    assert!(!f.cases.is_empty(), "elapsed fixture is empty");
    for c in f.cases {
        let got = format_elapsed(c.ts_ms, c.start_time);
        assert_eq!(
            got, c.expected,
            "elapsed(ts={}, start={}) = {:?}, want {:?}",
            c.ts_ms, c.start_time, got, c.expected
        );
    }
}

#[derive(Deserialize)]
struct AgoFile {
    cases: Vec<AgoCase>,
}
#[derive(Deserialize)]
struct AgoCase {
    #[serde(rename = "tsMs")]
    ts_ms: i64,
    #[serde(rename = "nowMs")]
    now_ms: i64,
    expected: String,
}

#[test]
fn ago_matches_js() {
    let f: AgoFile = load("ago.json");
    assert!(!f.cases.is_empty(), "ago fixture is empty");
    for c in f.cases {
        let got = format_ago(c.ts_ms, c.now_ms);
        assert_eq!(
            got, c.expected,
            "ago(ts={}, now={}) = {:?}, want {:?}",
            c.ts_ms, c.now_ms, got, c.expected
        );
    }
}

#[derive(Deserialize)]
struct ClockFile {
    cases: Vec<ClockCase>,
}
#[derive(Deserialize)]
struct ClockCase {
    hour: u8,
    minute: u8,
    expected: String,
}

#[test]
fn clock_matches_intl() {
    let f: ClockFile = load("clock.json");
    assert!(!f.cases.is_empty(), "clock fixture is empty");
    for c in f.cases {
        let got = format_clock(c.hour, c.minute);
        assert_eq!(
            got, c.expected,
            "clock(h={}, m={}) = {:?}, want {:?}",
            c.hour, c.minute, got, c.expected
        );
    }
}

#[derive(Deserialize)]
struct DurationFile {
    cases: Vec<DurationCase>,
}
#[derive(Deserialize)]
struct DurationCase {
    ms: i64,
    expected: String,
}

#[test]
fn duration_matches_js() {
    let f: DurationFile = load("duration.json");
    assert!(!f.cases.is_empty(), "duration fixture is empty");
    for c in f.cases {
        let got = format_duration(c.ms);
        assert_eq!(
            got, c.expected,
            "duration({}) = {:?}, want {:?}",
            c.ms, got, c.expected
        );
    }
}
