/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmdiarization_free: (a: number, b: number) => void;
export const wasmdiarization_confirm_merge: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasmdiarization_create: (a: number, b: number, c: number, d: number) => any;
export const wasmdiarization_create_with_dist: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const wasmdiarization_evaluate_rename: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasmdiarization_global_recluster: (a: number, b: number) => [number, number, number];
export const wasmdiarization_identify: (a: number, b: number, c: number) => any;
export const wasmdiarization_rename: (a: number, b: number, c: number, d: number, e: number) => void;
export const wasmdiarization_reset_tracker: (a: number) => void;
export const wasmdiarization_reuse_last_speaker: (a: number) => [number, number, number];
export const wasmdiarization_speakers: (a: number) => [number, number, number];
export const __wbg_wasmtitanetembedder_free: (a: number, b: number) => void;
export const cosine_sim: (a: number, b: number, c: number, d: number) => number;
export const wasmtitanetembedder_create: (a: number, b: number, c: number, d: number) => any;
export const wasmtitanetembedder_create_with_dist: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const wasmtitanetembedder_embed: (a: number, b: number, c: number) => any;
export const wasm_bindgen__convert__closures_____invoke__h688f6568f313d5a2: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h17463b5148d2d0d6: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h688f6568f313d5a2_2: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h2d0bf8e6805a65b7: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
