//! `SpeakerTracker` — online leader-clustering speaker diarization.
//!
//! A faithful port of the JS `SpeakerTracker` in `index.html` (class at
//! ~lines 1985–2093, plus the `merge`/`rename` policy at ~6250–6301) and the
//! stop-time global recluster from `docs/DIARIZATION.md` §2. The DOM is not this
//! crate's concern: the tracker owns the *policy* (which utterance belongs to
//! which speaker, what survives a recluster) and emits a relabel map that the UI
//! layer (F2) applies to the DOM.
//!
//! # Behavior contract (golden-tested)
//!
//! The clustering math is captured as goldens generated by the reference JS in
//! `goldens/gen/tracker_ref.mjs` (a DOM-free reimplementation of the exact
//! index.html algorithm). `tests/tracker_golden.rs` replays them and asserts the
//! Rust port reproduces every label assignment, merge result, and final speaker
//! set. The port is verifiable, not vibes.
//!
//! # Config, not magic numbers
//!
//! Every constant the JS hard-codes is a field of [`TrackerConfig`] with its
//! index.html value preserved as the default:
//!
//! | Constant            | index.html | [`TrackerConfig`] field        |
//! |---------------------|-----------:|--------------------------------|
//! | live threshold      | `0.45`     | `live_threshold`               |
//! | recluster threshold | `0.65`     | `recluster_threshold`          |
//! | EMA count cap       | `50`       | `centroid_count_cap`           |
//! | min samples (1.0 s) | `16000`    | `min_samples`                  |
//! | renormalize guard   | `… \|\| 1` | applied inline (see code)      |
//!
//! The 8-color rotation is [`SPEAKER_COLORS`], byte-for-byte from index.html.

// The centroid math casts `count: u32` to f32 (EMA weights — these are small
// utterance counts, never near 2^23) and accumulates true centroids in f64
// before a final f32 cast (matching DIARIZATION.md §2.2, which uses f64 for
// accumulation precision). Both are intentional and bounded.
#![allow(
    clippy::cast_precision_loss,
    clippy::cast_possible_truncation,
    reason = "EMA weights are small utterance counts; centroids accumulate in \
              f64 and cast to f32 at the end (DIARIZATION.md §2.2)"
)]

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// The 8-color rotation, byte-for-byte from `index.html`
/// (`this.colors` in the `SpeakerTracker` constructor). Speakers are assigned
/// `colors[speakers.len() % 8]` at creation, matching the JS exactly.
pub const SPEAKER_COLORS: [&str; 8] = [
    "#00d4aa", "#ff6b6b", "#7b68ee", "#ffd700", "#ff8c42", "#4ecdc4", "#c678dd", "#61afef",
];

/// Tunable clustering constants. Defaults are the index.html values verbatim.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TrackerConfig {
    /// Cosine similarity above which a new embedding joins an existing speaker
    /// (live leader clustering). index.html default: `0.45`.
    pub live_threshold: f32,
    /// Cosine similarity above which two clusters merge in the stop-time
    /// recluster. index.html / DIARIZATION.md default: `0.65`. More permissive
    /// than `live_threshold` because it compares robust full-meeting centroids.
    pub recluster_threshold: f32,
    /// EMA weight cap: `n = min(count, cap)` in the centroid update. index.html
    /// default: `50`.
    pub centroid_count_cap: u32,
    /// Minimum sample count for a confident embedding (1.0 s at 16 kHz). Shorter
    /// segments reuse the last speaker instead of minting a phantom. index.html
    /// default: `16000`. Enforced by the embedder integration, not the pure
    /// clustering path.
    pub min_samples: usize,
}

impl Default for TrackerConfig {
    fn default() -> Self {
        Self {
            live_threshold: 0.45,
            recluster_threshold: 0.65,
            centroid_count_cap: 50,
            min_samples: 16_000,
        }
    }
}

/// A tracked speaker cluster. Mirrors the JS object
/// `{ id, name, color, centroid, count }`.
#[derive(Debug, Clone)]
pub struct Speaker {
    /// Cluster id, `S1`, `S2`, … (as produced by the JS `S${nextId++}`).
    pub id: String,
    /// User-supplied display name, or empty if unnamed.
    pub name: String,
    /// Hex color from [`SPEAKER_COLORS`].
    pub color: String,
    /// L2-normalized 192-d centroid (the online EMA centroid).
    pub centroid: Vec<f32>,
    /// Number of utterances assigned to this speaker.
    pub count: u32,
}

/// One accumulated utterance: a raw embedding plus the live id it was assigned.
/// Mirrors the JS `this.utterances` array used by the stop-time recluster.
#[derive(Debug, Clone)]
pub struct Utterance {
    /// Raw L2-normalized 192-d embedding (kept for the recluster; the live path
    /// discards everything but the centroid, so we retain these in parallel —
    /// DIARIZATION.md §2.1).
    pub emb: Vec<f32>,
    /// The live speaker id this utterance was assigned (rewritten by recluster).
    pub assigned_id: String,
}

/// The outcome of [`SpeakerTracker::identify_embedding`]. Mirrors the JS
/// `{ id, name, color, isNew }` return.
#[derive(Debug, Clone, PartialEq)]
pub struct Identified {
    /// Assigned speaker id.
    pub id: String,
    /// Display name (empty if unnamed).
    pub name: String,
    /// Hex color.
    pub color: String,
    /// `true` if this call created a new speaker cluster.
    pub is_new: bool,
}

/// Online leader-clustering speaker tracker with a stop-time global recluster.
#[derive(Debug, Clone)]
pub struct SpeakerTracker {
    config: TrackerConfig,
    speakers: Vec<Speaker>,
    utterances: Vec<Utterance>,
    next_id: u32,
    last_speaker_id: Option<String>,
}

impl Default for SpeakerTracker {
    fn default() -> Self {
        Self::new(TrackerConfig::default())
    }
}

/// Cosine of two L2-normalized vectors (a plain dot product, matching the JS
/// `cosine(a, b)` which assumes both inputs are unit length).
#[must_use]
pub fn cosine_normalized(a: &[f32], b: &[f32]) -> f32 {
    a.iter().zip(b).map(|(x, y)| x * y).sum()
}

/// L2-normalize a vector in place; a zero vector is left unchanged (the JS uses
/// `norm || 1`, so dividing by 1 leaves it as-is).
fn l2_normalize(v: &mut [f32]) {
    let norm: f32 = v.iter().map(|x| x * x).sum::<f32>().sqrt();
    let denom = if norm == 0.0 { 1.0 } else { norm };
    for x in v.iter_mut() {
        *x /= denom;
    }
}

impl SpeakerTracker {
    /// Construct with the given config. Use [`SpeakerTracker::default`] for the
    /// index.html defaults.
    #[must_use]
    pub fn new(config: TrackerConfig) -> Self {
        Self {
            config,
            speakers: Vec::new(),
            utterances: Vec::new(),
            next_id: 1,
            last_speaker_id: None,
        }
    }

    /// The active config.
    #[must_use]
    pub fn config(&self) -> &TrackerConfig {
        &self.config
    }

    /// The current speaker clusters (read-only).
    #[must_use]
    pub fn speakers(&self) -> &[Speaker] {
        &self.speakers
    }

    /// The accumulated per-utterance embeddings (read-only).
    #[must_use]
    pub fn utterances(&self) -> &[Utterance] {
        &self.utterances
    }

    /// The id of the last speaker assigned (mirrors `lastSpeakerId`).
    #[must_use]
    pub fn last_speaker_id(&self) -> Option<&str> {
        self.last_speaker_id.as_deref()
    }

    /// Assign a speaker to a pre-computed L2-normalized embedding.
    ///
    /// This is the pure clustering path — exactly the JS `identify()` body after
    /// the embedder has run, minus the too-short-segment branch (which the
    /// embedder integration handles via `reuse_last_speaker`). It accumulates the
    /// raw embedding for the stop-time recluster (DIARIZATION.md §2.1).
    ///
    /// # Panics
    ///
    /// Never panics. (The embedding length is whatever the caller passes; the
    /// centroid update tolerates any length, matching the JS.)
    pub fn identify_embedding(&mut self, emb: &[f32]) -> Identified {
        // Leader clustering: nearest centroid above threshold, else a new speaker.
        let mut best: Option<usize> = None;
        let mut best_sim = f32::NEG_INFINITY;
        for (i, sp) in self.speakers.iter().enumerate() {
            let sim = cosine_normalized(emb, &sp.centroid);
            if sim > best_sim {
                best_sim = sim;
                best = Some(i);
            }
        }

        if let Some(idx) = best
            && best_sim >= self.config.live_threshold
        {
            // Capped-EMA centroid update + renormalize (JS lines 2041–2046).
            let cap = self.config.centroid_count_cap;
            let sp = &mut self.speakers[idx];
            let n = sp.count.min(cap) as f32;
            for (c, &e) in sp.centroid.iter_mut().zip(emb.iter()) {
                *c = (*c * n + e) / (n + 1.0);
            }
            l2_normalize(&mut sp.centroid);
            sp.count += 1;
            let id = sp.id.clone();
            let name = sp.name.clone();
            let color = sp.color.clone();
            self.last_speaker_id = Some(id.clone());
            self.utterances.push(Utterance {
                emb: emb.to_vec(),
                assigned_id: id.clone(),
            });
            return Identified {
                id,
                name,
                color,
                is_new: false,
            };
        }

        // New speaker (JS lines 2051–2055).
        let id = format!("S{}", self.next_id);
        self.next_id += 1;
        let color = SPEAKER_COLORS[self.speakers.len() % SPEAKER_COLORS.len()].to_string();
        self.speakers.push(Speaker {
            id: id.clone(),
            name: String::new(),
            color: color.clone(),
            centroid: emb.to_vec(),
            count: 1,
        });
        self.last_speaker_id = Some(id.clone());
        self.utterances.push(Utterance {
            emb: emb.to_vec(),
            assigned_id: id.clone(),
        });
        Identified {
            id,
            name: String::new(),
            color,
            is_new: true,
        }
    }

    /// Reuse the last speaker without embedding (the too-short-segment branch of
    /// the JS `identify()`). Returns `None` when there is no prior speaker.
    pub fn reuse_last_speaker(&mut self) -> Option<Identified> {
        let id = self.last_speaker_id.clone()?;
        let sp = self.speakers.iter().find(|s| s.id == id)?;
        Some(Identified {
            id: sp.id.clone(),
            name: sp.name.clone(),
            color: sp.color.clone(),
            is_new: false,
        })
    }

    /// Rename a speaker (JS `rename()`). No-op if the id is unknown.
    pub fn rename(&mut self, speaker_id: &str, new_name: &str) {
        if let Some(sp) = self.speakers.iter_mut().find(|s| s.id == speaker_id) {
            sp.name = new_name.to_string();
        }
    }

    /// Fold `from_id` into `to_id` (JS `merge()`). Combines centroids weighted by
    /// their capped counts (the same bounded-influence rule `identify` uses),
    /// renormalizes, transfers the count, drops the absorbed speaker, and
    /// rewrites `last_speaker_id`. Returns `false` on self-merge or unknown id.
    ///
    /// Also rewrites accumulated utterance assignments from `from_id` to `to_id`
    /// so a later recluster sees a consistent history (the JS keeps the DOM as
    /// the source of truth; here the utterance log is, so it must stay coherent).
    pub fn merge(&mut self, from_id: &str, to_id: &str) -> bool {
        if from_id == to_id {
            return false;
        }
        let from_idx = self.speakers.iter().position(|s| s.id == from_id);
        let to_idx = self.speakers.iter().position(|s| s.id == to_id);
        let (Some(from_idx), Some(to_idx)) = (from_idx, to_idx) else {
            return false;
        };

        let cap = self.config.centroid_count_cap;
        let wf = self.speakers[from_idx].count.min(cap) as f32;
        let wt = self.speakers[to_idx].count.min(cap) as f32;
        let from_centroid = self.speakers[from_idx].centroid.clone();
        let from_count = self.speakers[from_idx].count;

        {
            let to = &mut self.speakers[to_idx];
            for (c, &f) in to.centroid.iter_mut().zip(from_centroid.iter()) {
                *c = (*c * wt + f * wf) / (wt + wf);
            }
            l2_normalize(&mut to.centroid);
            to.count += from_count;
        }

        self.speakers.retain(|s| s.id != from_id);
        if self.last_speaker_id.as_deref() == Some(from_id) {
            self.last_speaker_id = Some(to_id.to_string());
        }
        // NB: the JS `merge()` deliberately does NOT rewrite the `utterances`
        // log — it updates `speakers` (+ the DOM) only. A subsequent
        // `global_recluster` rebuilds centroids from ALL utterances but only
        // relabels ids that are still live speakers (its `active_ids` filter), so
        // utterances stamped with the absorbed id contribute to no live cluster
        // and are left as-is. We match that exactly so the golden holds; rewriting
        // them here would diverge from index.html.
        true
    }

    /// Display name for a speaker (JS `displayName()`): the user name if set,
    /// else the raw id; the id itself if unknown.
    #[must_use]
    pub fn display_name(&self, speaker_id: &str) -> String {
        self.speakers
            .iter()
            .find(|s| s.id == speaker_id)
            .map_or_else(
                || speaker_id.to_string(),
                |s| {
                    if s.name.is_empty() {
                        s.id.clone()
                    } else {
                        s.name.clone()
                    }
                },
            )
    }

    /// Stop-time global recluster (DIARIZATION.md §2). Agglomerative
    /// centroid-merge over the accumulated raw embeddings: build a robust true
    /// (unweighted) centroid per live speaker, repeatedly merge the most-similar
    /// pair above `recluster_threshold`, then stable-relabel survivors to
    /// `S1..Sn` by their original numeric order.
    ///
    /// Returns the `oldId → newId` relabel map that was applied (empty if no
    /// merge was needed). **User renames survive**: a non-empty name on any id
    /// that maps into a survivor is re-applied to the survivor (DIARIZATION.md
    /// §2.4) — a PRD exit criterion.
    ///
    /// `threshold` overrides `config.recluster_threshold` when `Some`.
    #[must_use]
    pub fn global_recluster(&mut self, threshold: Option<f32>) -> HashMap<String, String> {
        let th = threshold.unwrap_or(self.config.recluster_threshold);
        let empty = HashMap::new();
        if self.utterances.len() < 2 || self.speakers.len() < 2 {
            return empty;
        }

        let dim = self.utterances[0].emb.len();

        // Step 1: true (unweighted) centroids from raw utterance embeddings.
        let mut true_centroids = build_true_centroids(&self.utterances, dim);

        // Only ids we actually know about and have a centroid for.
        let active_ids: Vec<String> = self
            .speakers
            .iter()
            .map(|s| s.id.clone())
            .filter(|id| true_centroids.contains_key(id))
            .collect();
        if active_ids.len() < 2 {
            return empty;
        }

        // Snapshot user renames before touching anything (DIARIZATION.md §2.4).
        let renames: HashMap<String, String> = self
            .speakers
            .iter()
            .filter(|s| !s.name.is_empty())
            .map(|s| (s.id.clone(), s.name.clone()))
            .collect();

        // Step 2: agglomerative centroid merge via union-find.
        let mut merged_into: HashMap<String, String> = active_ids
            .iter()
            .map(|id| (id.clone(), id.clone()))
            .collect();

        loop {
            let best_pair = most_similar_pair(&active_ids, &merged_into, &true_centroids);
            let Some((best_sim, best_i, best_j)) = best_pair else {
                break;
            };
            if best_sim < th {
                break;
            }

            // Redirect best_j's utterances into best_i, then recompute best_i's
            // true centroid from all utterances now under it.
            for u in &mut self.utterances {
                if find(&merged_into, &u.assigned_id) == best_j {
                    u.assigned_id.clone_from(&best_i);
                }
            }
            merged_into.insert(best_j.clone(), best_i.clone());

            let new_centroid = recompute_centroid(&self.utterances, &merged_into, &best_i, dim);
            true_centroids.insert(best_i.clone(), new_centroid);
            true_centroids.remove(&best_j);
        }

        // Step 3: surviving canonical ids, sorted by original numeric suffix.
        let mut survivors: Vec<String> = active_ids
            .iter()
            .map(|id| find(&merged_into, id))
            .collect::<std::collections::BTreeSet<_>>()
            .into_iter()
            .collect();
        survivors.sort_by_key(|id| numeric_suffix(id));

        // Step 3b: oldId → newId (S1..Sn in survivor order).
        let mut old_to_new: HashMap<String, String> = HashMap::new();
        for (idx, survivor) in survivors.iter().enumerate() {
            let new_id = format!("S{}", idx + 1);
            for orig in &active_ids {
                if &find(&merged_into, orig) == survivor {
                    old_to_new.insert(orig.clone(), new_id.clone());
                }
            }
        }

        // Bail if nothing changed (JS `anyChange`).
        let any_change = old_to_new.iter().any(|(k, v)| k != v);
        if !any_change {
            return empty;
        }

        // Step 4: rebuild self.speakers with new ids, re-applying renames and
        // carrying color from the survivor (DIARIZATION.md §2.3/§2.4).
        let mut new_speakers = Vec::with_capacity(survivors.len());
        for (idx, survivor) in survivors.iter().enumerate() {
            let new_id = format!("S{}", idx + 1);
            let orig = self.speakers.iter().find(|s| &s.id == survivor);
            // First rename whose old id maps to this new id wins (JS order).
            let name = renames
                .iter()
                .find(|(old_id, _)| old_to_new.get(*old_id) == Some(&new_id))
                .map(|(_, n)| n.clone())
                .unwrap_or_default();
            let color = orig.map_or_else(
                || SPEAKER_COLORS[idx % SPEAKER_COLORS.len()].to_string(),
                |s| s.color.clone(),
            );
            let centroid = true_centroids
                .get(survivor)
                .cloned()
                .or_else(|| orig.map(|s| s.centroid.clone()))
                .unwrap_or_else(|| vec![0.0; dim]);
            let count = orig.map_or(1, |s| s.count);
            new_speakers.push(Speaker {
                id: new_id,
                name,
                color,
                centroid,
                count,
            });
        }
        self.speakers = new_speakers;

        // NB: the JS `globalRecluster` rewrites `u.assignedId` ONLY during the
        // union-find merge loop (`u.assignedId = bestI`, i.e. to the original
        // canonical id), and it never applies the final `oldToNew` compaction
        // (S1..Sn) to the utterance log — only to `this.speakers` and the DOM. So
        // a survivor that was renamed by the survivor-sort (e.g. S7 → S4) leaves
        // its utterances stamped with the pre-compaction id (S7). We match that
        // exactly (the merge loop above already did `u.assigned_id = best_i`);
        // applying `old_to_new` here would diverge from index.html. The relabel
        // map is the contract the UI (F2) applies to the DOM.
        old_to_new
    }
}

/// Find the most-similar pair of distinct canonical clusters. Returns
/// `(similarity, canonical_i, canonical_j)`, or `None` if fewer than two
/// distinct live clusters remain. This is the inner O(k²) scan of the
/// agglomerative merge loop, extracted so `global_recluster` stays readable.
fn most_similar_pair(
    active_ids: &[String],
    merged_into: &HashMap<String, String>,
    true_centroids: &HashMap<String, Vec<f32>>,
) -> Option<(f32, String, String)> {
    let mut best: Option<(f32, String, String)> = None;
    for (a, id_a) in active_ids.iter().enumerate() {
        let ra = find(merged_into, id_a);
        let Some(ca) = true_centroids.get(&ra) else {
            continue;
        };
        for id_b in &active_ids[a + 1..] {
            let rb = find(merged_into, id_b);
            if ra == rb {
                continue;
            }
            let Some(cb) = true_centroids.get(&rb) else {
                continue;
            };
            let sim = cosine_normalized(ca, cb);
            if best.as_ref().is_none_or(|(b, ..)| sim > *b) {
                best = Some((sim, ra.clone(), rb.clone()));
            }
        }
    }
    best
}

/// Resolve the canonical representative of `id` under the union-find map.
fn find(merged_into: &HashMap<String, String>, id: &str) -> String {
    let mut cur = id.to_string();
    while let Some(parent) = merged_into.get(&cur) {
        if parent == &cur {
            break;
        }
        cur.clone_from(parent);
    }
    cur
}

/// Numeric suffix of an `Sxx` id (`0` if none), for the stable survivor sort.
fn numeric_suffix(id: &str) -> u32 {
    id.chars()
        .filter(char::is_ascii_digit)
        .collect::<String>()
        .parse()
        .unwrap_or(0)
}

/// Build a true (unweighted) L2-normalized centroid per assigned id from the raw
/// utterance embeddings. f64 accumulation for precision (DIARIZATION.md §2.2).
fn build_true_centroids(utterances: &[Utterance], dim: usize) -> HashMap<String, Vec<f32>> {
    let mut sums: HashMap<String, Vec<f64>> = HashMap::new();
    let mut counts: HashMap<String, u32> = HashMap::new();
    for u in utterances {
        let acc = sums
            .entry(u.assigned_id.clone())
            .or_insert_with(|| vec![0.0; dim]);
        for (a, &e) in acc.iter_mut().zip(u.emb.iter()) {
            *a += f64::from(e);
        }
        *counts.entry(u.assigned_id.clone()).or_insert(0) += 1;
    }
    sums.into_iter()
        .map(|(id, mut acc)| {
            let n = f64::from(counts[&id]);
            let mut norm = 0.0_f64;
            for a in &mut acc {
                *a /= n;
                norm += *a * *a;
            }
            let norm = norm.sqrt().max(f64::MIN_POSITIVE);
            let v: Vec<f32> = acc.iter().map(|&a| (a / norm) as f32).collect();
            (id, v)
        })
        .collect()
}

/// Recompute the true centroid for canonical id `canon` from all utterances that
/// resolve to it under the union-find map.
fn recompute_centroid(
    utterances: &[Utterance],
    merged_into: &HashMap<String, String>,
    canon: &str,
    dim: usize,
) -> Vec<f32> {
    let mut acc = vec![0.0_f64; dim];
    let mut cnt = 0_u32;
    for u in utterances {
        if find(merged_into, &u.assigned_id) == canon {
            for (a, &e) in acc.iter_mut().zip(u.emb.iter()) {
                *a += f64::from(e);
            }
            cnt += 1;
        }
    }
    let n = f64::from(cnt.max(1));
    let mut norm = 0.0_f64;
    for a in &mut acc {
        *a /= n;
        norm += *a * *a;
    }
    let norm = norm.sqrt().max(f64::MIN_POSITIVE);
    acc.iter().map(|&a| (a / norm) as f32).collect()
}

// ---------------------------------------------------------------------------
// Merge-by-rename policy (port of index.html maybeMergeOnRename ~6268–6281 +
// the nemotron-rust merge-on-rename semantics). The UI decision (the confirm()
// dialog) stays in the UI; this is the *policy* that decides whether a committed
// rename is really a merge, which target it merges into, and applies it.
// ---------------------------------------------------------------------------

/// The result of evaluating a committed speaker rename against the tracker
/// (`maybeMergeOnRename` policy, sans the UI `confirm()` dialog).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum RenameOutcome {
    /// The value matched another speaker's id or name → this is a merge. The UI
    /// should confirm, then call [`SpeakerTracker::merge`]`(from, target)`.
    Merge {
        /// The speaker being folded away.
        from: String,
        /// The surviving speaker the rename matched.
        target: String,
    },
    /// The value did not match another speaker → a plain rename.
    Rename {
        /// The speaker to rename.
        id: String,
        /// The new name.
        name: String,
    },
}

impl SpeakerTracker {
    /// Decide whether a committed rename of `from_id` to `value` is a
    /// merge-by-rename (the value equals another speaker's id or current name,
    /// case-insensitive) or a plain rename. This is the index.html
    /// `maybeMergeOnRename` matching logic, returning a [`RenameOutcome`] the UI
    /// acts on (it owns the `confirm()` dialog; declining falls back to the
    /// `Rename` arm). A blank value yields a `Rename` no-op the UI can ignore.
    #[must_use]
    pub fn evaluate_rename(&self, from_id: &str, value: &str) -> RenameOutcome {
        let v = value.trim().to_lowercase();
        if !v.is_empty() {
            let target = self.speakers.iter().find(|s| {
                s.id != from_id
                    && (s.id.to_lowercase() == v
                        || (!s.name.is_empty() && s.name.trim().to_lowercase() == v))
            });
            if let Some(target) = target {
                // Only a merge if `from` actually exists (JS guards this too).
                if self.speakers.iter().any(|s| s.id == from_id) {
                    return RenameOutcome::Merge {
                        from: from_id.to_string(),
                        target: target.id.clone(),
                    };
                }
            }
        }
        RenameOutcome::Rename {
            id: from_id.to_string(),
            name: value.trim().to_string(),
        }
    }
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    reason = "tests use unwrap as the assertion mechanism (PRD lint config)"
)]
#[allow(
    clippy::match_wildcard_for_single_variants,
    reason = "test `other => panic!()` arms document the unexpected case; \
              RenameOutcome is non-exhaustive in spirit (more arms may come)"
)]
mod tests {
    use super::*;

    fn unit(seed: u32, dim: usize) -> Vec<f32> {
        // Deterministic pseudo-random unit vector.
        let mut s = seed.wrapping_mul(2_654_435_761).wrapping_add(1);
        let mut v: Vec<f32> = (0..dim)
            .map(|_| {
                s = s.wrapping_mul(1_103_515_245).wrapping_add(12_345);
                ((s >> 8) & 0xffff) as f32 / 32_768.0 - 1.0
            })
            .collect();
        l2_normalize(&mut v);
        v
    }

    #[test]
    fn colors_match_index_html() {
        assert_eq!(SPEAKER_COLORS.len(), 8);
        assert_eq!(SPEAKER_COLORS[0], "#00d4aa");
        assert_eq!(SPEAKER_COLORS[7], "#61afef");
    }

    #[test]
    fn first_identify_mints_s1() {
        let mut t = SpeakerTracker::default();
        let r = t.identify_embedding(&unit(1, 192));
        assert_eq!(r.id, "S1");
        assert!(r.is_new);
        assert_eq!(r.color, "#00d4aa");
    }

    #[test]
    fn identical_embeddings_share_a_speaker() {
        let mut t = SpeakerTracker::default();
        let e = unit(1, 192);
        let a = t.identify_embedding(&e);
        let b = t.identify_embedding(&e);
        assert_eq!(a.id, b.id);
        assert!(!b.is_new);
        assert_eq!(t.speakers().len(), 1);
        assert_eq!(t.speakers()[0].count, 2);
    }

    #[test]
    fn merge_self_and_unknown_fail() {
        let mut t = SpeakerTracker::default();
        t.identify_embedding(&unit(1, 8));
        assert!(!t.merge("S1", "S1"), "self-merge must fail");
        assert!(!t.merge("S9", "S1"), "unknown from must fail");
    }

    #[test]
    fn evaluate_rename_detects_merge_by_id() {
        let mut t = SpeakerTracker::default();
        t.identify_embedding(&unit(1, 8)); // S1
        // Force a second speaker.
        let mut far = unit(2, 8);
        for x in &mut far {
            *x = -*x;
        }
        t.identify_embedding(&far); // S2 (anti-correlated → below threshold)
        // Renaming S2 to "S1" is a merge into S1.
        match t.evaluate_rename("S2", "S1") {
            RenameOutcome::Merge { from, target } => {
                assert_eq!(from, "S2");
                assert_eq!(target, "S1");
            }
            other => panic!("expected merge, got {other:?}"),
        }
    }

    #[test]
    fn evaluate_rename_plain_when_no_match() {
        let mut t = SpeakerTracker::default();
        t.identify_embedding(&unit(1, 8));
        match t.evaluate_rename("S1", "Alice") {
            RenameOutcome::Rename { id, name } => {
                assert_eq!(id, "S1");
                assert_eq!(name, "Alice");
            }
            other => panic!("expected rename, got {other:?}"),
        }
    }

    #[test]
    fn display_name_prefers_user_name() {
        let mut t = SpeakerTracker::default();
        t.identify_embedding(&unit(1, 8));
        assert_eq!(t.display_name("S1"), "S1");
        t.rename("S1", "Alice");
        assert_eq!(t.display_name("S1"), "Alice");
        assert_eq!(t.display_name("S9"), "S9"); // unknown → echoes id
    }
}
