//! Golden tests for the [`SpeakerTracker`] port.
//!
//! These replay fixtures generated by the reference JS in
//! `goldens/gen/tracker_ref.mjs` (a DOM-free reimplementation of the EXACT
//! index.html algorithm) and assert the Rust port reproduces every label
//! assignment, merge result, and final speaker set. This is what makes the port
//! verifiable rather than vibes: the JS behavior is captured first, then the
//! Rust must match it.
//!
//! Native-only (the tracker is pure Rust, but ts-rs/ort gating keeps the test
//! target out of the wasm build for consistency with the crate's other tests).
#![cfg(not(target_arch = "wasm32"))]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "tests use unwrap/expect as the assertion mechanism (PRD lint config)"
)]
#![allow(
    clippy::match_wildcard_for_single_variants,
    reason = "`other => panic!()` arms document the unexpected RenameOutcome case"
)]

use serde::Deserialize;
use silent_diarization::tracker::{RenameOutcome, SpeakerTracker, TrackerConfig};
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct Fixture {
    description: String,
    threshold: f32,
    #[serde(rename = "reclusterThreshold")]
    recluster_threshold: f32,
    steps: Vec<Step>,
    expected: Expected,
}

#[derive(Debug, Deserialize)]
#[serde(tag = "op", rename_all = "lowercase")]
enum Step {
    Identify { emb: Vec<f32> },
    Rename { id: String, name: String },
    Merge { from: String, to: String },
    Recluster { threshold: Option<f32> },
}

#[derive(Debug, Deserialize)]
struct Expected {
    trace: Vec<TraceItem>,
    #[serde(rename = "finalSpeakers")]
    final_speakers: Vec<FinalSpeaker>,
    #[serde(rename = "utteranceLabels")]
    utterance_labels: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(tag = "op", rename_all = "lowercase")]
enum TraceItem {
    Identify {
        result: IdResult,
    },
    Rename {
        id: String,
        name: String,
    },
    Merge {
        from: String,
        to: String,
        ok: bool,
    },
    Recluster {
        #[serde(default)]
        map: std::collections::HashMap<String, String>,
    },
}

#[derive(Debug, Deserialize)]
struct IdResult {
    id: String,
    #[serde(rename = "isNew")]
    is_new: bool,
}

#[derive(Debug, Deserialize)]
struct FinalSpeaker {
    id: String,
    name: String,
    count: u32,
}

fn goldens_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("goldens")
}

fn load(rel: &str) -> Fixture {
    let path = goldens_dir().join(rel);
    let bytes =
        std::fs::read(&path).unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()));
    serde_json::from_slice(&bytes)
        .unwrap_or_else(|e| panic!("parse fixture {}: {e}", path.display()))
}

/// Replay a fixture against the Rust tracker and assert every observable result.
fn replay(rel: &str) {
    let fx = load(rel);
    let mut t = SpeakerTracker::new(TrackerConfig {
        live_threshold: fx.threshold,
        recluster_threshold: fx.recluster_threshold,
        ..TrackerConfig::default()
    });

    let mut trace = fx.expected.trace.iter();
    for step in &fx.steps {
        let expected = trace.next().expect("more steps than trace items");
        match (step, expected) {
            (Step::Identify { emb }, TraceItem::Identify { result }) => {
                let got = t.identify_embedding(emb);
                assert_eq!(
                    got.id, result.id,
                    "[{}] identify id mismatch",
                    fx.description
                );
                assert_eq!(
                    got.is_new, result.is_new,
                    "[{}] identify isNew mismatch on {}",
                    fx.description, result.id
                );
            }
            (
                Step::Rename { id, name },
                TraceItem::Rename {
                    id: eid,
                    name: ename,
                },
            ) => {
                assert_eq!((id, name), (eid, ename));
                t.rename(id, name);
            }
            (
                Step::Merge { from, to },
                TraceItem::Merge {
                    from: ef,
                    to: et,
                    ok,
                },
            ) => {
                assert_eq!((from, to), (ef, et));
                let got = t.merge(from, to);
                assert_eq!(
                    got, *ok,
                    "[{}] merge {from}->{to} ok mismatch",
                    fx.description
                );
            }
            (Step::Recluster { threshold }, TraceItem::Recluster { map }) => {
                let got = t.global_recluster(*threshold);
                assert_eq!(&got, map, "[{}] recluster map mismatch", fx.description);
            }
            (s, e) => panic!(
                "[{}] step/trace op mismatch: {s:?} vs {e:?}",
                fx.description
            ),
        }
    }

    // Final speaker set must match exactly (id, name, count).
    assert_eq!(
        t.speakers().len(),
        fx.expected.final_speakers.len(),
        "[{}] final speaker count",
        fx.description
    );
    for (got, exp) in t.speakers().iter().zip(&fx.expected.final_speakers) {
        assert_eq!(got.id, exp.id, "[{}] final speaker id", fx.description);
        assert_eq!(
            got.name, exp.name,
            "[{}] final speaker name",
            fx.description
        );
        assert_eq!(
            got.count, exp.count,
            "[{}] final speaker count",
            fx.description
        );
    }

    // Final per-utterance labels must match.
    let got_labels: Vec<&str> = t
        .utterances()
        .iter()
        .map(|u| u.assigned_id.as_str())
        .collect();
    let exp_labels: Vec<&str> = fx
        .expected
        .utterance_labels
        .iter()
        .map(String::as_str)
        .collect();
    assert_eq!(
        got_labels, exp_labels,
        "[{}] final utterance labels",
        fx.description
    );
}

#[test]
fn clean_two_speaker() {
    replay("tracker/clean_two_speaker.json");
}

#[test]
fn rename_then_merge() {
    replay("tracker/rename_then_merge.json");
}

#[test]
fn merge_edge_cases() {
    replay("tracker/merge_edge_cases.json");
}

/// The merge-by-rename POLICY (`evaluate_rename`) must return a `Merge` when a
/// committed rename matches another speaker's id/name, and a plain `Rename`
/// otherwise. This is the index.html `maybeMergeOnRename` decision, sans the UI
/// `confirm()` dialog. We exercise it on the clean two-speaker fixture state.
#[test]
fn evaluate_rename_policy_matches_index_html() {
    let fx = load("tracker/clean_two_speaker.json");
    let mut t = SpeakerTracker::new(TrackerConfig {
        live_threshold: fx.threshold,
        recluster_threshold: fx.recluster_threshold,
        ..TrackerConfig::default()
    });
    for step in &fx.steps {
        if let Step::Identify { emb } = step {
            t.identify_embedding(emb);
        }
    }
    assert!(t.speakers().len() >= 2, "fixture should have 2 speakers");
    let s1 = t.speakers()[0].id.clone();
    let s2 = t.speakers()[1].id.clone();

    // Renaming S2 to "S1" (another speaker's id) is a merge into S1.
    match t.evaluate_rename(&s2, &s1) {
        RenameOutcome::Merge { from, target } => {
            assert_eq!(from, s2);
            assert_eq!(target, s1);
        }
        other => panic!("expected merge by id, got {other:?}"),
    }

    // Rename S1 to a human name, then renaming S2 to that name is a merge.
    t.rename(&s1, "Alice");
    match t.evaluate_rename(&s2, "alice") {
        RenameOutcome::Merge { from, target } => {
            assert_eq!(from, s2);
            assert_eq!(target, s1);
        }
        other => panic!("expected merge by name (case-insensitive), got {other:?}"),
    }

    // A genuinely new name is a plain rename.
    match t.evaluate_rename(&s2, "Bob") {
        RenameOutcome::Rename { id, name } => {
            assert_eq!(id, s2);
            assert_eq!(name, "Bob");
        }
        other => panic!("expected plain rename, got {other:?}"),
    }
}
