// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Declared capabilities of an engine, used by the selection policy.
 */
export type AsrCapabilities = { 
/**
 * Whether the engine emits [`EngineEvent::Partial`] events (streaming) as
 * opposed to only [`EngineEvent::Final`] segments.
 */
streaming: boolean, 
/**
 * Whether the engine emits [`EngineEvent::Draft`] events (Dual / draft
 * mode).
 */
drafts: boolean, 
/**
 * Whether the engine requires WebGPU (Voxtral) versus running on CPU/WASM.
 */
requires_webgpu: boolean, 
/**
 * Sample rate the engine expects on [`crate::engine::AudioChunk`], in hertz
 * (16 000 for every current engine).
 */
sample_rate_hz: number, };
