// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelResolveError } from "./ModelResolveError";

/**
 * The single error type returned by every [`crate::engine::AsrEngine`] method.
 *
 * `#[non_exhaustive]` so new failure modes can be added without a breaking
 * change; callers must include a wildcard arm.
 */
export type AsrError = { "kind": "model_resolution", "detail": ModelResolveError } | { "kind": "device_unsupported", "detail": { 
/**
 * Human-readable reason, for example `"WebGPU adapter not available"`.
 */
reason: string, } } | { "kind": "load", "detail": { 
/**
 * Engine-reported message.
 */
message: string, } } | { "kind": "inference", "detail": { 
/**
 * Engine-reported message.
 */
message: string, } } | { "kind": "invalid_audio", "detail": { 
/**
 * What was wrong with the audio.
 */
message: string, } } | { "kind": "host", "detail": { 
/**
 * Host-reported message.
 */
message: string, } } | { "kind": "invalid_state", "detail": { 
/**
 * Description of the lifecycle violation.
 */
message: string, } };
