// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The action the JS executor must take in response to a lifecycle event.
 *
 * The policy never touches the socket; it returns one of these and the
 * executor performs it. `None` means "do nothing" (idempotent events, or a
 * close with no auto-reconnect).
 */
export type BridgeAction = { "action": "connect" } | { "action": "schedule_reconnect", 
/**
 * The backoff delay before the next attempt, in milliseconds.
 */
delay_ms: number, } | { "action": "none" };
