// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user-visible connection status of the Claude bridge.
 *
 * The status dot (`#claudeDot`) and label (`#claudeLabel`) render from this:
 * only [`Connected`](BridgeStatus::Connected) lights the dot and shows "Claude
 * connected"; every other status shows the offline dot and "Claude offline" —
 * pixel-identical to the JS `updateIndicator(connected)` which only ever
 * distinguished connected-vs-not. The richer non-connected variants exist so
 * the policy (and tests, and a future setup-panel detail line) can reason about
 * *why* it is not connected, without changing what the dot shows today.
 */
export type BridgeStatus = "disconnected" | "connecting" | "connected" | "reconnecting";
