// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheStore } from "./CacheStore";

/**
 * Cache + hash-verification policy (PRD R4 `cache`).
 */
export type Cache = { 
/**
 * Where artifacts are cached.
 */
store: CacheStore, 
/**
 * Hash-verification policy: verify once per revision, record it, and do
 * **not** re-hash multi-GB files on every load. `true` is the default;
 * set `false` only for tiny fixtures where per-load verification is cheap.
 */
verify_once_per_revision: boolean, };
