// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cache backend (PRD R4: `cache-api` or `transformers-idb`).
 */
export type CacheStore = "cache-api" | "transformers-idb";
