// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Correction } from "./Correction";

/**
 * A command the UI issues to the corrections core (UI → core). The corrections
 * panel (Appendix A row 25) drives these; the core applies them to incoming
 * transcript text and echoes the updated map back via
 * [`CorrectionEvent::CorrectionsChanged`].
 */
export type CorrectionCommand = { "tag": "add_correction", "payload": { 
/**
 * The mis-heard word/phrase.
 */
wrong: string, 
/**
 * The replacement text.
 */
right: string, } } | { "tag": "remove_correction", "payload": { 
/**
 * The `wrong` key to remove.
 */
wrong: string, } } | { "tag": "set_corrections", "payload": { 
/**
 * The full ordered correction list.
 */
corrections: Array<Correction>, } };
