// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One word-correction pair: replace every (case-insensitive) occurrence of
 * `wrong` with `right`. Mirrors the index.html `corrections` object entry
 * (`corrections[wrong] = right`). The order corrections are *added* is
 * preserved (the JS `Object.entries` insertion order), so later corrections
 * see earlier ones' output.
 */
export type Correction = { 
/**
 * The mis-heard word/phrase to replace (matched literally, case-insensitive).
 */
wrong: string, 
/**
 * The replacement text.
 */
right: string, };
