// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Correction } from "./Correction";

/**
 * An event the corrections core emits to the UI (core → UI).
 */
export type CorrectionEvent = { "tag": "corrections_changed", "payload": { 
/**
 * The full ordered correction list, insertion order preserved.
 */
corrections: Array<Correction>, } };
