// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-tier defaults and requirements (PRD R4 `device_tiers`; encodes the Qwen
 * tier-default mechanism as data).
 */
export type DeviceTier = { 
/**
 * Whether this model is the default choice for this device tier.
 */
default_for_tier: boolean, 
/**
 * Minimum system memory required, gigabytes (Voxtral needs 16).
 */
min_memory_gb: number | null, 
/**
 * Whether this tier requires WebGPU.
 */
requires_webgpu: boolean | null, };
