// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One sampled row of the `notetakerDiag` ring.
 *
 * The **field order here is load-bearing**: serde serializes struct fields in
 * declaration order, and that order — plus the camelCase `rename_all` and the
 * `null`-eliding `Option`s — is what makes `serde_json::to_string(&rows)`
 * byte-identical to the JS `JSON.stringify(rows)`. The order matches the JS
 * `sample()` object literal verbatim:
 * `iso, elapsedSec, heapUsedMB, heapTotalMB, heapLimitMB, items, words,
 * loopIter, recycle, ctxLen, genStepsTotal, inputTokens, lastStepMs,
 * deviceLost, writeAbs`.
 *
 * Heap fields and `writeAbs` are `Option`: JS writes `null` when
 * `performance.memory` is unavailable (Firefox/Safari) or when there is no
 * Voxtral ring yet. serde renders `None` as `null` in the same slots.
 */
export type DiagRow = { 
/**
 * Wall-clock ISO-8601 timestamp of the sample (host-supplied; the core has
 * no clock). Matches `new Date(now).toISOString()`.
 */
iso: string, 
/**
 * Whole seconds since the trail started (host-supplied). Matches
 * `Math.round((now - startMs) / 1000)`.
 */
elapsedSec: bigint, 
/**
 * `performance.memory.usedJSHeapSize` in MB, `null` when unavailable.
 *
 * Explicitly renamed: the JS key is `heapUsedMB` (capital `B`), whereas
 * serde's `camelCase` of `heap_used_mb` would emit `heapUsedMb`. The
 * byte-identity contract requires the exact JS key, so it is pinned here
 * (and the ts-rs `rename` keeps the generated TypeScript field in sync).
 */
heapUsedMB: number | null, 
/**
 * `performance.memory.totalJSHeapSize` in MB, `null` when unavailable.
 */
heapTotalMB: number | null, 
/**
 * `performance.memory.jsHeapSizeLimit` in MB, `null` when unavailable.
 */
heapLimitMB: number | null, 
/**
 * DOM `.transcript-item` count (host-supplied; the core has no DOM).
 */
items: bigint, 
/**
 * DOM `.transcript-word` count (host-supplied).
 */
words: bigint, 
/**
 * Fresh `generate()` contexts started this session (outer-while count).
 */
loopIter: bigint, 
/**
 * `generate()` returns that hit the recycle cap (sawtooth events).
 */
recycle: bigint, 
/**
 * Token count emitted in the CURRENT generate context.
 */
ctxLen: bigint, 
/**
 * Total streamer `put()` calls across the whole session.
 */
genStepsTotal: bigint, 
/**
 * `input_ids` length of the current context (prompt size).
 */
inputTokens: bigint, 
/**
 * Wall-ms of the most recent `put()`-to-`put()` gap (`+(dt).toFixed(1)`).
 */
lastStepMs: number, 
/**
 * Device-lost / OOM message if observed, else empty string.
 */
deviceLost: string, 
/**
 * The Voxtral ring write cursor (host-supplied), `null` when there is no
 * ring yet. Matches `app.tm.voxtralRing.writeAbs`.
 */
writeAbs: bigint | null, };
