// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A command the UI issues to the diarization core (UI → core).
 *
 * Mirrors the index.html interactions: click-to-rename a speaker tag
 * (`renameSpeaker`), merge a mis-split speaker (`mergeSpeaker` /
 * `maybeMergeOnRename`), and the stop-time recluster the app runs on Stop.
 */
export type DiarizationCommand = { "tag": "rename_speaker", "payload": { 
/**
 * The speaker cluster id (for example `S2`).
 */
speaker_id: string, 
/**
 * The new display name (empty clears the name back to the raw id).
 */
name: string, } } | { "tag": "confirm_merge", "payload": { 
/**
 * The speaker being folded away.
 */
from_id: string, 
/**
 * The surviving speaker it folds into.
 */
to_id: string, } } | { "tag": "global_recluster", "payload": { 
/**
 * Cosine merge threshold override, or `None` for the configured default.
 */
threshold: number | null, } };
