// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelabelEntry } from "./RelabelEntry";
import type { SpeakerDescriptor } from "./SpeakerDescriptor";

/**
 * An event the diarization core emits to the UI (core → UI).
 */
export type DiarizationEvent = { "tag": "speaker_assigned", "payload": { 
/**
 * The assigned speaker.
 */
speaker: SpeakerDescriptor, 
/**
 * `true` if this assignment created a brand-new speaker cluster.
 */
is_new: boolean, } } | { "tag": "speaker_renamed", "payload": { 
/**
 * The speaker cluster id.
 */
speaker_id: string, 
/**
 * The new display name (empty means show the raw id).
 */
name: string, } } | { "tag": "merge_proposed", "payload": { 
/**
 * The speaker the user was renaming (would be folded away).
 */
from_id: string, 
/**
 * The existing speaker the typed value matched (the merge target).
 */
to_id: string, } } | { "tag": "merge_applied", "payload": { 
/**
 * The folded-away speaker.
 */
from_id: string, 
/**
 * The surviving speaker.
 */
to_id: string, } } | { "tag": "reclustered", "payload": { 
/**
 * The applied relabeling (empty if nothing changed).
 */
relabel: Array<RelabelEntry>, 
/**
 * The surviving speakers after the recluster (renames preserved).
 */
speakers: Array<SpeakerDescriptor>, } };
