// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Latency / throughput telemetry for an engine (PRD R9, Appendix A row 35).
 *
 * Field semantics match `nemotron-engine.js`'s `stats()`: RTF below `1.0` is
 * faster than realtime; `ttft_ms` is the felt lag from first audio to first
 * visible text.
 */
export type EngineStats = { 
/**
 * One-time model load + warm-up cost, milliseconds.
 */
load_ms: number, 
/**
 * Number of audio chunks decoded this session.
 */
chunks: number, 
/**
 * Mean decode time per chunk, milliseconds.
 */
avg_chunk_ms: number, 
/**
 * Most recent chunk decode time, milliseconds.
 */
last_chunk_ms: number, 
/**
 * Audio seconds processed this session.
 */
audio_secs: number, 
/**
 * Real-time factor: processing-time / audio-duration. `< 1.0` beats
 * realtime. The R9 Nemotron browser gate is `<= 0.5`.
 */
rtf: number, 
/**
 * Time to first text, milliseconds (first audio → first visible text). The
 * R9 Nemotron browser gate is `<= 1000`.
 */
ttft_ms: number, 
/**
 * Samples still buffered awaiting a whole chunk; sustained growth means the
 * decoder cannot keep up.
 */
pending_samples: number, };
