// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineStats } from "./EngineStats";
import type { TimeRange } from "./TimeRange";

/**
 * An event emitted by an [`crate::engine::AsrEngine`] during its lifecycle.
 *
 * Tagged as `{ "tag": "...", "payload": ... }` (the discriminant layout the A3
 * spike validated compiles cleanly as a TypeScript discriminated union).
 */
export type EngineEvent = { "tag": "load_progress", "payload": { 
/**
 * Artifact path being fetched, for example `encoder.onnx`.
 */
file: string, 
/**
 * Bytes fetched so far.
 */
loaded: bigint, 
/**
 * Total bytes for this file (`0` if the length is unknown).
 */
total: bigint, } } | { "tag": "ready" } | { "tag": "draft", "payload": { 
/**
 * Draft transcript text.
 */
text: string, 
/**
 * The audio span this text covers.
 */
range: TimeRange, } } | { "tag": "partial", "payload": { 
/**
 * Partial transcript text.
 */
text: string, 
/**
 * The audio span this text covers.
 */
range: TimeRange, } } | { "tag": "final", "payload": { 
/**
 * Final transcript text.
 */
text: string, 
/**
 * The audio span this text covers.
 */
range: TimeRange, } } | { "tag": "stats", "payload": EngineStats } | { "tag": "warning", "payload": { 
/**
 * Human-readable warning message.
 */
message: string, } };
