// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execution provider (per host availability).
 */
export type ExecutionProvider = "cpu" | "webgpu";
