// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The runtime that executes a model (the hybrid is honest because the registry
 * records it — PRD R4).
 */
export type Host = "rust-ort-web" | "js-transformers" | "js-sherpa";
