// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the `image` field of a screenshot was stored in `IndexedDB`, discovered
 * at read time.
 *
 * Real `SilentNotetaker` data uses different layouts depending on the app
 * version and capture path. All three are proven zero-loss in the S4 spike
 * (`docs/research/spike-storage.md`):
 *
 * - [`ImageEncoding::Base64String`] — the CURRENT shipping path: `canvas.toBlob()`
 *   → `FileReader.readAsDataURL()` → a `data:image/jpeg;base64,...` STRING
 *   (index.html:2813/2820). This is what every live DB contains today.
 * - [`ImageEncoding::Blob`] — the migration-critical case. A canvas `Blob`
 *   stored directly (a plausible alternate/future capture path, and what a naive
 *   "store the `toBlob()` result" produces). Its bytes are only readable via the
 *   async `blob.arrayBuffer()` Promise, which forces the two-phase IDB read.
 * - [`ImageEncoding::Bytes`] — a `Uint8Array`/`ArrayBuffer` stored directly: the
 *   normalized layout the migration WRITES, so post-migration reads are
 *   single-phase.
 * - [`ImageEncoding::Empty`] — the `image` field was null/undefined/absent.
 */
export type ImageEncoding = "base64_string" | "blob" | "bytes" | "empty";
