// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `meetings` row.
 *
 * Dexie schema: `++id, title, startTime, endTime, duration`.
 */
export type Meeting = { 
/**
 * Auto-incrementing primary key (Dexie `++id`).
 */
id: number, 
/**
 * Human-readable title (UI caps input at 120 chars; the stored value is
 * trusted as-is — a longer legacy value is preserved, not truncated).
 */
title: string, 
/**
 * Unix epoch milliseconds at recording start.
 */
startTime: number, 
/**
 * Unix epoch milliseconds at recording end, or `None` for a meeting that
 * never reached Stop (`endTime: null` in the shipping app, index.html:3972).
 *
 * `default` accepts a row whose `endTime` key is absent entirely; it
 * serializes back as `endTime: null` (not omitted) so a re-stored backup is
 * byte-faithful to what Dexie wrote. `#[ts(rename)]` is given explicitly:
 * ts-rs's serde-compat does not pick up `#[serde(rename)]` when the field
 * also carries `default` on an `Option`, so the TS key would otherwise drift
 * to `end_time` and break the UI typing.
 */
endTime: number | null, 
/**
 * Duration in milliseconds (`0` until the meeting is stopped).
 */
duration: number, };
