// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The state of a Dexie→Rust storage migration (core → UI).
 *
 * `#[non_exhaustive]`: new phases can be added without breaking the UI, which
 * handles unknown variants with a wildcard arm (A3 escape hatch).
 */
export type MigrationStatus = "pending" | "awaiting_backup" | "migrating" | "complete" | "already_migrated";
