// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One required artifact file (PRD R4 `files`).
 */
export type ModelFile = { 
/**
 * Path within the repo, for example `encoder.onnx`.
 */
path: string, 
/**
 * File size in bytes (from the HF API LFS oid — never download multi-GB
 * files to hash). Optional only because some entries are pinned before
 * sizes are recorded; `xtask model-audit` requires it on shipped defaults.
 */
size: bigint | null, 
/**
 * sha256 of the file contents. Optional for the same reason as `size`;
 * required on shipped defaults.
 */
sha256: string | null, 
/**
 * What the artifact is for (free-form: `encoder`, `decoder`, `tokenizer`,
 * `wasm-runtime`, …). Optional.
 */
purpose: string | null, };
