// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable local identifier for a model, for example `asr.nemotron.streaming_0_6b`.
 *
 * This is a transparent newtype over `String`: it serializes as a bare string,
 * not as `{ "0": "..." }`. ts-rs cannot infer transparency from the
 * `#[serde(transparent)]` attribute and would otherwise emit a wrapper type, so
 * it is declared explicitly with `#[ts(as = "String")]` — the ts-rs 10 spelling
 * of the A3 spike's "transparent alongside serde(transparent)" guidance (the
 * `transparent` keyword the spike suggested is not a valid ts-rs 10 attribute).
 * The generated TypeScript is `type ModelId = string`.
 */
export type ModelId = string;
