// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cache } from "./Cache";
import type { DeviceTier } from "./DeviceTier";
import type { ExecutionProvider } from "./ExecutionProvider";
import type { Host } from "./Host";
import type { ModelFile } from "./ModelFile";
import type { ModelId } from "./ModelId";
import type { ModelUi } from "./ModelUi";
import type { PerfBudget } from "./PerfBudget";
import type { Provider } from "./Provider";
import type { Task } from "./Task";
import type { Validation } from "./Validation";

/**
 * One model in the registry (PRD R4 "Registry fields").
 */
export type Model = { 
/**
 * Stable local id, for example `asr.nemotron.streaming_0_6b`.
 */
id: ModelId, 
/**
 * What the model does.
 */
task: Task, 
/**
 * Artifact provider (currently always Hugging Face).
 */
provider: Provider, 
/**
 * Hugging Face repo, for example `onnx-community/Voxtral-Mini-4B-Realtime-2602-ONNX`.
 */
repo: string, 
/**
 * Exact commit SHA or immutable revision. `main` is **not acceptable** for
 * production defaults (enforced by `xtask model-audit`, not by this type —
 * the registry must still parse a bad value to report it).
 */
revision: string, 
/**
 * Which runtime executes the model.
 */
host: Host, 
/**
 * CPU or WebGPU (per host availability).
 */
execution_provider: ExecutionProvider, 
/**
 * Available dtype variants (`fp32`, `fp16`, `q8`, `q4f16`, `int8`, …).
 */
precision: Array<string>, 
/**
 * Expected peak memory budget, megabytes.
 */
memory_budget_mb: number, 
/**
 * Cache + hash-verification policy.
 */
cache: Cache, 
/**
 * Upstream license identifier (SPDX where one exists, else a descriptive
 * tag like `nvidia-open-model-license`).
 */
license: string, 
/**
 * `true` only after a human has read the license (PRD R4; A2 report). A
 * shipped default must have this `true`.
 */
license_verified: boolean, 
/**
 * Derived allowlist entries needed to fetch this model's artifacts. Feeds
 * CSP `connect-src` generation (Task D2).
 */
network_origins: Array<string>, 
/**
 * Required artifacts, each with path/size/sha256/purpose. Multi-file
 * artifact sets are first-class (Voxtral ~2.7 GB; Nemotron three files).
 */
files: Array<ModelFile>, 
/**
 * Per-tier defaults and requirements (the Qwen tier-default mechanism as
 * data). Keyed by tier name (`wasm_only`, `webgpu_high`, …).
 */
device_tiers: { [key in string]?: DeviceTier }, 
/**
 * Golden fixture ids and expected outputs for this model.
 */
validation: Validation | null, 
/**
 * R9 performance budgets enforced as regression gates.
 */
perf_budget: PerfBudget | null, 
/**
 * Settings-picker presentation, when this model is a user-selectable ASR
 * engine (PRD Phase 5 / R3; Appendix A row 7). `None` for entries that are
 * not directly user-picked in the ASR slot (TitaNet embedder, the Qwen
 * notes models — those have their own surfaces). The picker (Task I3 /
 * `silent_inference::selection`) renders one option per `Some(ui)`, ordered
 * by [`ModelUi::order`]; the label and the persisted `value` come from
 * here, so adding a Whisper size is a registry entry — zero code (R3
 * acceptance).
 */
ui: ModelUi | null, 
/**
 * For a **composite** engine (Dual = Moonshine drafts + SenseVoice refiner),
 * the ids of the underlying model entries it reuses, in policy order
 * (`[draft, refine]`). Empty for ordinary single-model entries. A composite
 * entry carries no own `files`; the selection module resolves artifacts and
 * availability by following these ids (Appendix A row 11).
 */
composite_of: Array<ModelId>, };
