// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";

/**
 * Why a model artifact could not be resolved from the registry or verified.
 *
 * `#[non_exhaustive]`; callers must include a wildcard arm.
 */
export type ModelResolveError = { "kind": "unknown_model", "detail": ModelId } | { "kind": "fetch", "detail": { 
/**
 * The artifact path that failed.
 */
path: string, 
/**
 * Transport-reported message.
 */
message: string, } } | { "kind": "hash_mismatch", "detail": { 
/**
 * The artifact path.
 */
path: string, 
/**
 * The pinned sha256 from the registry.
 */
expected: string, 
/**
 * The sha256 actually computed over the fetched bytes.
 */
actual: string, } } | { "kind": "mutable_revision", "detail": ModelId };
