// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Settings-picker presentation for a user-selectable ASR engine (the `value`
 * persisted in `localStorage` + the option label shown), kept as registry data
 * so the picker stays "registry entry = zero code" (PRD R3).
 *
 * `value` is the stable selection key the UI persists (e.g. `voxtral`,
 * `nemotron`, an HF repo id for the Whisper/Moonshine families) — it is NOT the
 * registry [`Model::id`], because the shipping UI and `localStorage` already use
 * these short keys and that contract must not break (pixel-identical UX).
 */
export type ModelUi = { 
/**
 * The picker option `value` the UI persists in `localStorage` under
 * `settings.model` (e.g. `voxtral`, `nemotron`, `dual`, `sensevoice`, or an
 * HF repo id like `onnx-community/whisper-small.en`). Load-bearing: the
 * shipping `index.html` branches on these exact strings.
 */
value: string, 
/**
 * The exact option label shown in the picker (must match the shipping
 * option text verbatim for pixel-identical UX).
 */
label: string, 
/**
 * Position in the picker list (ascending). The shipping order is preserved
 * by these values; ties fall back to registry order.
 */
order: number, };
