// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The four live note-section counters the UI renders (Appendix A row 16,
 * "+ live counters"). `decisions` / `actions` / `keypoints` are running note
 * counts in that section; `questions` is the count of *unresolved* open
 * questions (the index.html `OpenQs` semantics).
 */
export type NoteCounters = { 
/**
 * Number of decision notes.
 */
decisions: number, 
/**
 * Number of action-item notes.
 */
actions: number, 
/**
 * Number of key-point notes.
 */
keypoints: number, 
/**
 * Number of *open* (unresolved) questions.
 */
questions: number, };
