// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteCategory } from "./NoteCategory";
import type { NoteCounters } from "./NoteCounters";

/**
 * An event the notes core emits to the UI (core → UI).
 */
export type NoteEvent = { "tag": "note_added", "payload": { 
/**
 * Stable note id (assigned by the core / storage).
 */
id: bigint, 
/**
 * The category section to render this note in.
 */
category: NoteCategory, 
/**
 * The triggering sentence text.
 */
text: string, 
/**
 * The regex that matched, as its source string — preserved
 * byte-identically from the index.html `pattern.source` (kept for
 * provenance / debugging; not rendered).
 */
trigger_phrase: string, } } | { "tag": "question_resolved", "payload": { 
/**
 * The note id of the question that is now resolved.
 */
id: bigint, } } | { "tag": "counters_changed", "payload": { 
/**
 * Current section counters.
 */
counters: NoteCounters, } };
