// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A command the UI issues to the notes core (UI → core).
 */
export type NoteCommand = { "tag": "analyze_line", "payload": { 
/**
 * The final transcript text for this line.
 */
text: string, } } | { "tag": "flush" } | { "tag": "set_trigger_detection", "payload": { 
/**
 * `true` enables live trigger notes; `false` disables them.
 */
enabled: boolean, } };
