// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A note category. The four categories render as Markdown sections in this
 * fixed order (decisions → actions → key points → open questions), matching the
 * JS `sections` array order in `notesToMarkdown` / `openMeetingDetail`.
 */
export type NoteCategory = "decisions" | "actions" | "keypoints" | "questions";
