// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `notes` row (a trigger note, AI note, or question).
 *
 * Dexie schema: `++id, meetingId, category, text, timestamp, triggerPhrase`.
 */
export type Note = { 
/**
 * Auto-incrementing primary key.
 */
id: number, 
/**
 * Foreign key to `meetings.id`.
 */
meetingId: number, 
/**
 * Category as the app writes it (`decisions`, `actions`, `keypoints`,
 * `questions` — see index.html:3810/2660). Kept as a free string so a future
 * category is preserved, not rejected.
 */
category: string, 
/**
 * Note text.
 */
text: string, 
/**
 * Offset milliseconds from meeting start.
 */
timestamp: number, 
/**
 * The phrase that triggered detection. `#[serde(default)]` because AI-final
 * notes and older rows may omit it (the trigger path always sets it,
 * index.html:2662, but the migration must not lose a note that lacks it).
 */
triggerPhrase: string, };
