// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The note category the trigger policy assigns. The four sections the UI
 * renders (Appendix A row 16): decisions, action items, key points, open
 * questions. Serialized `snake_case` to match the index.html category keys
 * (`decisions` / `actions` / `keypoints` / `questions`).
 */
export type NoteCategory = "decisions" | "actions" | "keypoints" | "questions";
