// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * R9 performance budgets, enforced as regression gates in the golden harness.
 *
 * All fields optional: a model declares only the gates that apply to it (an
 * embedder has no TTFT). The golden harness fails the build when a measured
 * value exceeds a declared budget.
 */
export type PerfBudget = { 
/**
 * Max time-to-first-text in the browser, milliseconds (Nemotron: 1000).
 */
ttft_ms_max: number | null, 
/**
 * Max real-time factor in the browser WASM path (Nemotron: 0.5).
 */
rtf_browser_max: number | null, 
/**
 * Max real-time factor on the native path (Nemotron: 0.2).
 */
rtf_native_max: number | null, 
/**
 * Whether a 10-minute session must hold flat memory (Voxtral two-cap
 * recycle; all engines: no unbounded heap growth).
 */
flat_memory_10min: boolean | null, };
