// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A command the UI / orchestrator issues to the questions+notes core (UI →
 * core).
 *
 * Mirrors the index.html interactions: live transcript accumulation feeding the
 * teleprompter, the manual reroll button, the minimize/expand toggle, and the
 * two stop-time passes (question recap + final notes).
 */
export type QuestionCommand = { "tag": "accumulate_transcript", "payload": { 
/**
 * The transcript fragment (already finalized text, not a partial).
 */
text: string, 
/**
 * Milliseconds from session start, the scheduler's clock (replaces
 * `Date.now()` so command-log replay is deterministic — PRD "The UI
 * boundary").
 */
now_ms: bigint, } } | { "tag": "reroll", "payload": { 
/**
 * Scheduler clock in milliseconds from session start.
 */
now_ms: bigint, } } | { "tag": "toggle_minimize" } | { "tag": "reset" } | { "tag": "request_recap" } | { "tag": "request_final_notes" } | { "tag": "worker_result", "payload": { 
/**
 * The id of the [`QuestionEvent::GenerateRequest`] this answers.
 */
request_id: number, 
/**
 * The model's raw output text (the policy strips/normalizes it).
 */
text: string, } };
