// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionType } from "./QuestionType";
import type { QwenNote } from "./QwenNote";
import type { RecapGroup } from "./RecapGroup";

/**
 * An event the questions+notes core emits to the UI / worker (core → UI).
 */
export type QuestionEvent = { "tag": "generate_request", "payload": { 
/**
 * Correlates the eventual [`QuestionCommand::WorkerResult`].
 */
request_id: number, 
/**
 * The rolling transcript window to condition on (already WINDOW_CHARS-capped).
 */
window: string, 
/**
 * The question type to generate (drives the worker's system prompt).
 */
kind: QuestionType, } } | { "tag": "question_ready", "payload": { 
/**
 * The question text to show.
 */
text: string, 
/**
 * The type chip label (clarify / risk / follow-up …).
 */
kind: QuestionType, 
/**
 * `true` when the bar is minimized, so the UI raises the new-question
 * badge dot (Appendix A row 21 "new-question badge").
 */
badge: boolean, } } | { "tag": "minimize_changed", "payload": { 
/**
 * `true` if now minimized.
 */
minimized: boolean, } } | { "tag": "recap_ready", "payload": { 
/**
 * The per-type recap groups.
 */
groups: Array<RecapGroup>, } } | { "tag": "final_notes_ready", "payload": { 
/**
 * The extracted notes (chunk order, deduped).
 */
notes: Array<QwenNote>, } };
