// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which smart-question type the policy is asking the worker to generate.
 *
 * The five rotation types ported from `SmartQ`'s `TYPES` array (index.html
 * `~2201`). The rotation order and the per-type system prompts are Rust policy
 * (`silent-notes`); this enum is the type label that travels on the wire and
 * renders in the teleprompter chip (`smartqType`).
 */
export type QuestionType = "clarify" | "risk" | "followup" | "coverage" | "deepen";
