// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One parsed Qwen note (`parseQwenNotes`).
 */
export type QwenNote = { 
/**
 * The note category as the UI list id: `decisions`, `actions`,
 * `keypoints`, or `questions`.
 */
cat: string, 
/**
 * The note text (length-capped at 160 chars with a trailing `…`).
 */
text: string, 
/**
 * The outline topic this note sits under (`None` until a `TOPIC|` line set
 * one in the same chunk).
 */
topic: string | null, };
