// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One per-type group of recap questions (`generateQuestionRecap`).
 */
export type RecapGroup = { 
/**
 * The display label for this group (for example `Clarifying`,
 * `Devil's Advocate`).
 */
label: string, 
/**
 * Up to 3 deduped questions for this group.
 */
questions: Array<string>, };
