// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Model } from "./Model";

/**
 * The top-level registry document: `[[model]]` array of entries.
 */
export type Registry = { 
/**
 * Every registered model. Parsed from `[[model]]` TOML tables.
 */
model: Array<Model>, };
