// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `old_id → new_id` entry in a recluster relabel map. A `Vec` of these
 * (rather than a `HashMap`) keeps the TypeScript a plain array the UI can
 * iterate deterministically.
 */
export type RelabelEntry = { 
/**
 * The pre-recluster speaker id.
 */
old_id: string, 
/**
 * The post-recluster canonical speaker id.
 */
new_id: string, };
