// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `screenshots` row.
 *
 * Dexie schema:
 * `++id, meetingId, timestamp, image, width, height, analyzed, analysis`.
 *
 * The `image` field is polymorphic in real data ([`ImageEncoding`]); the reader
 * always materializes the raw payload bytes into [`Screenshot::image`] and
 * records which encoding it found in [`Screenshot::image_encoding`].
 */
export type Screenshot = { 
/**
 * Auto-incrementing primary key.
 */
id: number, 
/**
 * Foreign key to `meetings.id`.
 */
meetingId: number, 
/**
 * Capture time offset milliseconds.
 */
timestamp: number, 
/**
 * Width of the captured frame in pixels.
 */
width: number, 
/**
 * Height of the captured frame in pixels.
 */
height: number, 
/**
 * Whether Claude-bridge analysis has run.
 */
analyzed: boolean, 
/**
 * Claude-bridge analysis text. `#[serde(default)]` because a fresh capture
 * has no `analysis` field at all (index.html:2817 omits it).
 */
analysis: string, };
