// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AsrError } from "./AsrError";
import type { EngineEvent } from "./EngineEvent";
import type { SessionState } from "./SessionState";

/**
 * An event emitted by the core to the UI to render.
 *
 * Carries engine activity ([`SessionEvent::Engine`]) plus session-level state
 * transitions the orchestrator owns.
 */
export type SessionEvent = { "tag": "state_changed", "payload": { 
/**
 * The new session state.
 */
state: SessionState, } } | { "tag": "engine", "payload": EngineEvent } | { "tag": "speaker_label", "payload": { 
/**
 * The speaker's cluster id.
 */
speaker_id: number, 
/**
 * The display name to show.
 */
name: string, } } | { "tag": "notice", "payload": { 
/**
 * Human-readable message.
 */
message: string, } } | { "tag": "error", "payload": AsrError };
