// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AsrError } from "./AsrError";
import type { EngineEvent } from "./EngineEvent";
import type { SessionState } from "./SessionState";
import type { StopHooks } from "./StopHooks";
import type { TimestampMode } from "./TimestampMode";

/**
 * An event emitted by the core to the UI to render.
 *
 * Carries engine activity ([`SessionEvent::Engine`]) plus session-level state
 * transitions the orchestrator owns.
 */
export type SessionEvent = { "tag": "state_changed", "payload": { 
/**
 * The new session state.
 */
state: SessionState, } } | { "tag": "engine", "payload": EngineEvent } | { "tag": "title_changed", "payload": { 
/**
 * The clamped, render-ready title.
 */
title: string, } } | { "tag": "sources_changed", "payload": { 
/**
 * Mic capture is active.
 */
mic: boolean, 
/**
 * Tab/system audio is mixed in.
 */
tab: boolean, } } | { "tag": "timestamp_mode_changed", "payload": { 
/**
 * The newly-active mode.
 */
mode: TimestampMode, } } | { "tag": "stop_hooks", "payload": StopHooks } | { "tag": "speaker_label", "payload": { 
/**
 * The speaker's cluster id.
 */
speaker_id: number, 
/**
 * The display name to show.
 */
name: string, } } | { "tag": "notice", "payload": { 
/**
 * Human-readable message.
 */
message: string, } } | { "tag": "error", "payload": AsrError };
