// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The recording-session state machine's externally-visible state (Appendix A
 * rows 1–3). The full machine lives in `silent-core`'s orchestrator (Phase 4);
 * this enum is the UI-facing projection.
 */
export type SessionState = "idle" | "loading" | "recording" | "stopped";
