// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `speakerNames` row: the durable per-meeting speaker-rename map
 * (Phase-F carry-forward).
 *
 * The diarization tracker holds the human labels the user assigns to raw
 * speaker ids (`S1`, `S2`, …) only in memory, so renames were lost on reload —
 * the Phase-F gap this record closes. One row per meeting, keyed by
 * `meeting_id` (NOT auto-increment): writing the same meeting's map again
 * `put`s over the row. `names` maps a raw speaker id to its assigned name; only
 * renamed speakers appear (an absent id falls back to the raw id, exactly as the
 * live tracker does).
 *
 * This is additive schema (a new store, no change to the four existing ones),
 * so it never affects the zero-loss migration.
 */
export type SpeakerName = { 
/**
 * Foreign key to `meetings.id` AND the store's primary key (one row per
 * meeting; `put` overwrites).
 */
meetingId: number, 
/**
 * Map of raw speaker id (`"S1"`) → assigned human name (`"Alice"`). Only
 * renamed speakers are stored; an id not present here keeps its raw label.
 */
names: { [key in string]?: string }, };
