// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A speaker cluster as the UI needs to render it. Carries the label and color
 * only — never the centroid/embedding (PRD R5/R7).
 */
export type SpeakerDescriptor = { 
/**
 * The cluster id (`S1`, `S2`, …).
 */
id: string, 
/**
 * The user-supplied display name, or empty if unnamed (show the id).
 */
name: string, 
/**
 * Hex color from the 8-color rotation (for example `#00d4aa`).
 */
color: string, 
/**
 * Number of utterances assigned to this speaker.
 */
count: number, };
