// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which stop-time passes the orchestrator decided to trigger (Appendix A rows
 * 15, 19, 21, 31), emitted inside [`SessionEvent::StopHooks`].
 *
 * These are *decisions*, computed from the session's [`SessionConfig`](crate::session::SessionConfig)
 * at Stop, exactly mirroring the guards in index.html's `stop()`:
 *
 * - `recluster` ← a tracker is loaded with `> 1` speaker (DIARIZATION.md §2).
 * - `final_notes` ← `aiFinalNotes !== false`.
 * - `question_recap` ← `smartQuestions !== false && smartqRecap !== false`.
 * - `auto_summary` ← the summary modal always opens at Stop; `autoSummary`
 *   additionally requests the on-device/bridge summary pass.
 *
 * The host layer runs each enabled pass; Rust owns *whether* to (R2).
 */
export type StopHooks = { 
/**
 * Run the stop-time global speaker recluster (Appendix A row 15).
 */
recluster: boolean, 
/**
 * Run the Qwen AI final-notes pass (Appendix A row 19).
 */
final_notes: boolean, 
/**
 * Run the smart-question stop-time recap (Appendix A row 21).
 */
question_recap: boolean, 
/**
 * Run the auto-summary pass (Appendix A row 31).
 */
auto_summary: boolean, };
