// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Row counts plus total screenshot payload bytes for a [`StorageSnapshot`].
 *
 * A migration must preserve every count and the byte total across a
 * Blob→`Uint8Array` normalization (the bytes are re-encoded, not changed).
 */
export type StorageCounts = { 
/**
 * `meetings` row count.
 */
meetings: number, 
/**
 * `transcriptChunks` row count.
 */
transcript_chunks: number, 
/**
 * `notes` row count.
 */
notes: number, 
/**
 * `screenshots` row count.
 */
screenshots: number, 
/**
 * Total bytes across all screenshot `image` payloads.
 */
screenshot_bytes: number, };
