// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MigrationStatus } from "./MigrationStatus";
import type { StorageCounts } from "./StorageCounts";

/**
 * A storage / migration event the core emits to the UI (core → UI).
 *
 * `#[non_exhaustive]`, tagged `{ "tag": ..., "payload": ... }`, `snake_case` —
 * the same boundary layout as [`crate::commands::SessionEvent`] and
 * [`crate::diarization::DiarizationEvent`].
 */
export type StorageEvent = { "tag": "backup_ready", "payload": { 
/**
 * `URL.createObjectURL` of the backup blob the UI links for download.
 */
object_url: string, 
/**
 * Suggested download filename, for example
 * `silent-notetaker-backup-<timestamp>.json`.
 */
filename: string, 
/**
 * Backup size in bytes (for the UI to show and to sanity-check the blob).
 */
size_bytes: number, 
/**
 * The row counts captured in the backup, so the UI can show "backed up
 * N meetings".
 */
counts: StorageCounts, } } | { "tag": "status_changed", "payload": { 
/**
 * The new migration status.
 */
status: MigrationStatus, } } | { "tag": "progress", "payload": { 
/**
 * Rows normalized so far (screenshots are the only normalized table).
 */
done: number, 
/**
 * Total rows to normalize.
 */
total: number, } } | { "tag": "completed", "payload": { 
/**
 * Row counts read from the source DB before migration.
 */
before: StorageCounts, 
/**
 * Row counts read back after migration; must equal `before`.
 */
after: StorageCounts, } } | { "tag": "failed", "payload": { 
/**
 * Human-readable reason.
 */
message: string, } };
