// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A half-open time span within a recording, in milliseconds from session start.
 *
 * Attached to transcript events ([`crate::events::EngineEvent::Partial`],
 * [`crate::events::EngineEvent::Final`], …) so the UI can place and re-time
 * text. `end_ms >= start_ms` is an expected invariant but is not enforced by
 * the type (a degenerate range is preferable to a panic on the hot path).
 */
export type TimeRange = { 
/**
 * Inclusive start, milliseconds from session start.
 */
start_ms: bigint, 
/**
 * Exclusive end, milliseconds from session start.
 */
end_ms: bigint, };
