// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The timestamp display mode for the header timer and per-line stamps
 * (Appendix A row 24). The cycle button rotates `elapsed → clock → ago →
 * elapsed`, matching the `timeFormat` setting in index.html.
 *
 * The variant order is the cycle order: [`TimestampMode::next`] advances one
 * step. Serialized `snake_case` (`"elapsed"`, `"clock"`, `"ago"`) so it round-
 * trips with the persisted `timeFormat` localStorage value unchanged.
 */
export type TimestampMode = "elapsed" | "clock" | "ago";
