// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The active per-line timestamp display mode (Appendix A row 24).
 *
 * The UI cycles through these in order via
 * [`crate::commands::UiCommand::CycleTimestampMode`]; [`TimestampMode::CYCLE`]
 * is the rotation order (`elapsed → clock → ago → elapsed`), matching the JS
 * `TIME_FORMATS = ['elapsed', 'clock', 'ago']`.
 */
export type TimestampMode = "elapsed" | "clock" | "ago";
