// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `transcriptChunks` row.
 *
 * Dexie schema: `++id, meetingId, timestamp, text, isFinal`.
 */
export type TranscriptChunk = { 
/**
 * Auto-incrementing primary key.
 */
id: number, 
/**
 * Foreign key to `meetings.id`.
 */
meetingId: number, 
/**
 * Offset milliseconds from meeting start (`Date.now()` at write time).
 */
timestamp: number, 
/**
 * Transcript text for this chunk.
 */
text: string, 
/**
 * `true` for a finalized (non-draft) chunk (index.html:4326 always writes
 * `true`; drafts are not persisted, but the field is read tolerantly).
 */
isFinal: boolean, };
