// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelId } from "./ModelId";

/**
 * A command issued by the UI to the core.
 *
 * Tagged `{ "tag": "...", "payload": ... }`, matching the [`SessionEvent`] and
 * [`EngineEvent`] discriminant layout the A3 spike validated.
 */
export type UiCommand = { "tag": "start_recording", "payload": { 
/**
 * Meeting title (auto date/time default, up to 120 chars per
 * Appendix A row 3).
 */
title: string, } } | { "tag": "stop_recording" } | { "tag": "resume_recording" } | { "tag": "new_meeting" } | { "tag": "set_title", "payload": { 
/**
 * The proposed title; clamped to 120 chars, empty falls back to the
 * default at start.
 */
title: string, } } | { "tag": "add_tab_audio" } | { "tag": "remove_tab_audio" } | { "tag": "select_asr_engine", "payload": { 
/**
 * Registry id of the chosen ASR model.
 */
model: ModelId, } } | { "tag": "select_notes_model", "payload": { 
/**
 * Registry id of the chosen notes model, or `None` to disable notes.
 */
model: ModelId | null, } } | { "tag": "rename_speaker", "payload": { 
/**
 * The speaker's current cluster id.
 */
speaker_id: number, 
/**
 * The new display name.
 */
name: string, } } | { "tag": "cycle_timestamp_mode" };
