// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Golden-fixture validation metadata (PRD R4 `validation`).
 */
export type Validation = { 
/**
 * Golden fixture ids exercised against this model (PRD "Golden tests":
 * every engine ships `goldens/<engine>/`).
 */
golden_fixtures: Array<string>, 
/**
 * Expected output for the golden fixture, where deterministic (a golden
 * transcript, or a cosine threshold expressed as text). Free-form per the
 * fixture; brittle exact strings are avoided unless deterministic.
 */
expected: string | null, };
